/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { createMiddleware } from 'hono/factory';
import { drizzle } from 'drizzle-orm/d1';
import { eq, and } from 'drizzle-orm';
import { createAuth, type Env } from '../lib/auth';
import type { AppContext } from '../lib/types';
import { verifyJwt, signJwt } from '../lib/jwt';
import { AuthErrors } from '../lib/errors';
import { member } from '../auth/schema';

/**
 * Auth middleware - extracts session or API key and populates AppContext
 */
export const authMiddleware = createMiddleware<{
  Bindings: Env;
  Variables: { ctx: AppContext };
}>(async (c, next) => {
  // Skip Better Auth routes - they handle their own authentication
  if (c.req.path.startsWith('/auth/v1/')) {
    c.set('ctx', { authenticated: false });
    return next();
  }

  // Skip CLI routes
  if (c.req.path.startsWith('/cli/')) {
    c.set('ctx', { authenticated: false });
    return next();
  }

  try {
    const auth = createAuth(c.env);

    // Check for API key via x-api-key header
    const apiKeyHeader = c.req.header('x-api-key');
    if (apiKeyHeader) {
      try {
        const keyResult = await (auth.api as any).verifyApiKey({
          body: { key: apiKeyHeader }
        });

        if (keyResult?.valid && keyResult.key) {
          // Parse metadata to get organizationId
          const metadata = keyResult.key.metadata
            ? (typeof keyResult.key.metadata === 'string'
                ? JSON.parse(keyResult.key.metadata)
                : keyResult.key.metadata)
            : {};

          const activeOrgId = metadata.organizationId as string | undefined;

          // Look up the user's actual role in the organization
          let roles: string[] = [];
          let verifiedOrgId = activeOrgId;
          if (activeOrgId) {
            try {
              const authDb = drizzle(c.env.AUTH_DB);
              const [row] = await authDb
                .select({ role: member.role })
                .from(member)
                .where(
                  and(
                    eq(member.userId, keyResult.key.referenceId),
                    eq(member.organizationId, activeOrgId)
                  )
                );
              if (row?.role) {
                roles = [row.role];
              } else {
                verifiedOrgId = undefined;
              }
            } catch (e) {
              console.error('[AUTH] Failed to look up member role:', e);
              verifiedOrgId = undefined;
            }
          }

          c.set('ctx', {
            authenticated: true,
            userId: keyResult.key.referenceId,
            activeOrgId: verifiedOrgId,
            activeTeamId: undefined,
            roles,
          });

          return next();
        } else if (keyResult?.error) {
          // Rate limit and expiry are hard failures
          if (keyResult.error.code === 'RATE_LIMIT_EXCEEDED') {
            c.set('ctx', { authenticated: false });
            return c.json(AuthErrors.rateLimited(), 429);
          }
          if (keyResult.error.message?.includes('expired')) {
            c.set('ctx', { authenticated: false });
            return c.json(AuthErrors.expired(), 401);
          }
          // Key not found — fall through to session auth
        }
      } catch {
        // API key verification failed — fall through to session auth
      }
    }

    // JWT fast-path — verify signature without database lookup
    const authHeader = c.req.header('Authorization');
    const bearerToken = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null;
    if (bearerToken?.startsWith('eyJ')) {
      try {
        const claims = await verifyJwt(bearerToken, c.env.BETTER_AUTH_SECRET);
        if (claims) {
          c.set('ctx', {
        authenticated: true,
        userId: claims.sub,
        userRole: claims.userRole,
        activeOrgId: claims.orgId,
        activeTeamId: undefined,
        roles: claims.role ? [claims.role] : [],
        user: { id: claims.sub, email: claims.email || '', name: claims.name },
          });
          return next();
        }
      } catch {
        // JWT verification failed — fall through to session auth
      }
    }

    // Fall back to session-based auth
    const session = await auth.api.getSession({ headers: c.req.raw.headers });

    if (!session) {
      c.set('ctx', { authenticated: false });
      return next();
    }

    // Extract organization and roles from session
    const activeOrg = (session.session as any).activeOrganizationId as string | undefined;
    const sessionMember = activeOrg
      ? await (auth.api as any).getFullOrganization({
          headers: c.req.raw.headers,
          query: { organizationId: activeOrg }
        }).then((org: any) => org?.members?.find((m: any) => m.userId === session.user.id))
      : null;
    const verifiedOrgId = sessionMember && activeOrg ? activeOrg : undefined;
    const userRole = (session.user as any).role || 'user';

    c.set('ctx', {
      authenticated: true,
      userId: session.user.id,
      userRole,
      activeOrgId: verifiedOrgId,
      activeTeamId: undefined,
      roles: sessionMember?.role ? [sessionMember.role] : [],
      user: session.user,
    });


    // Mint JWT for future requests (avoids DB lookups)
    try {
      const jwt = await signJwt({
        sub: session.user.id,
        email: session.user.email,
        name: session.user.name,
        orgId: verifiedOrgId,
        role: sessionMember?.role,
        userRole: userRole,
      }, c.env.BETTER_AUTH_SECRET);
      c.header('set-auth-token', jwt);
    } catch {
      // Non-fatal: session auth succeeded, JWT mint is optional
    }

    return next();
  } catch (error) {
    console.error('Auth middleware error:', error);
    c.set('ctx', { authenticated: false });
    return next();
  }
});

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
