/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { createMiddleware } from 'hono/factory';
import { authDb, db } from '../db';
import { createAuditDb } from '../lib/audit-wrapper';

/**
 * Database middleware - provides database instances
 * - authDb: Auth database (users, sessions, organizations, etc.)
 * - db: Features database (application tables)
 * Note: db is wrapped with audit auto-injection for createdBy/modifiedBy
 */
export const dbMiddleware = createMiddleware<{
  Variables: {
    authDb: typeof authDb;
    db: typeof db;
  };
}>(async (c, next) => {
  c.set('authDb', authDb);
  c.set('db', createAuditDb(db, () => (c as any).get('ctx')) as typeof db);
  return next();
});

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
