/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Runtime access evaluation helpers
export interface AppContext {
  authenticated: boolean;
  userId?: string;
  userRole?: string;  // User's role from user table (e.g., 'user', 'admin')
  activeOrgId?: string;
  activeTeamId?: string;
  roles?: string[];  // Organization member roles (e.g., 'owner', 'admin', 'member')
  user?: {
    id: string;
    email: string;
    name?: string;
    [key: string]: any;
  };
  [key: string]: any;
}

export type Access<TRecord = any> = DeclarativeAccess | FunctionAccess<TRecord>;

export interface DeclarativeAccess {
  roles?: string[];
  userRole?: string[];
  record?: RecordConditions;
  or?: DeclarativeAccess[];
  and?: DeclarativeAccess[];
}

export type RecordConditions = { [field: string]: FieldCondition };
export type FieldCondition =
  | { equals: string | number | boolean }
  | { notEquals: string | number | boolean }
  | { in: (string | number)[] }
  | { notIn: (string | number)[] };

export type FunctionAccess<TRecord> = (ctx: AppContext, record?: TRecord) => boolean | Promise<boolean>;

export async function evaluateAccess<TRecord = any>(
  access: Access<TRecord>,
  ctx: AppContext,
  record?: TRecord
): Promise<boolean> {
  if (typeof access === 'function') {
    return await access(ctx, record);
  }
  return evaluateDeclarativeAccess(access, ctx, record);
}

function evaluateDeclarativeAccess<TRecord>(
  access: DeclarativeAccess,
  ctx: AppContext,
  record?: TRecord
): boolean {
  if (access.or) {
    return access.or.some(a => evaluateDeclarativeAccess(a, ctx, record));
  }
  if (access.and) {
    return access.and.every(a => evaluateDeclarativeAccess(a, ctx, record));
  }

  // PUBLIC role grants access without authentication
  if (access.roles?.includes('PUBLIC')) return true;

  // Check roles (org-membership, ctx.roles)
  const rolesPassed = access.roles && access.roles.length > 0
    ? ctx.roles?.some(r => access.roles!.includes(r)) ?? false
    : true;

  // Check userRole (user-table role, ctx.userRole)
  const userRolePassed = access.userRole && access.userRole.length > 0
    ? !!ctx.userRole && access.userRole.includes(ctx.userRole)
    : true;

  // Check record conditions
  const recordPassed = access.record
    ? evaluateRecordConditions(access.record, record, ctx)
    : true;

  return rolesPassed && userRolePassed && recordPassed;
}

function evaluateRecordConditions<TRecord>(
  conditions: RecordConditions,
  record: TRecord | undefined,
  ctx: AppContext
): boolean {
  if (!record) return false;
  return Object.entries(conditions).every(([field, condition]) => {
    const value = (record as any)[field];
    return evaluateFieldCondition(condition, value, ctx);
  });
}

function evaluateFieldCondition(condition: FieldCondition, value: any, ctx: AppContext): boolean {
  if ('equals' in condition) {
    const expected = substituteCtxVar(condition.equals, ctx);
    return value === expected;
  }
  if ('notEquals' in condition) {
    const expected = substituteCtxVar(condition.notEquals, ctx);
    return value !== expected;
  }
  if ('in' in condition) {
    const resolved = condition.in.map((v: any) => substituteCtxVar(v, ctx));
    return resolved.includes(value);
  }
  if ('notIn' in condition) {
    const resolved = condition.notIn.map((v: any) => substituteCtxVar(v, ctx));
    return !resolved.includes(value);
  }
  return false;
}

function substituteCtxVar(val: string | number | boolean, ctx: AppContext): any {
  if (typeof val === 'string' && val.startsWith('$ctx.')) {
    const path = val.substring(5);
    return path.split('.').reduce((o, k) => o?.[k], ctx as any);
  }
  return val;
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
