/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Runtime access evaluation helpers
export interface AppContext {
  authenticated: boolean;
  userId?: string;
  userRole?: string;  // User's role from user table (e.g., 'user', 'admin')
  activeOrgId?: string;
  activeTeamId?: string;
  roles?: string[];  // Organization member roles (e.g., 'owner', 'admin', 'member')
  user?: {
    id: string;
    email: string;
    name?: string;
    [key: string]: any;
  };
  [key: string]: any;
}

export type Access<TRecord = any> = DeclarativeAccess | FunctionAccess<TRecord>;

export interface DeclarativeAccess {
  roles?: string[];
  userRole?: string[];
  record?: RecordConditions;
  or?: DeclarativeAccess[];
  and?: DeclarativeAccess[];
}

export type RecordConditions = { [field: string]: FieldCondition };
export type FieldCondition =
  | { equals: string | number | boolean }
  | { notEquals: string | number | boolean }
  | { in: (string | number)[] }
  | { notIn: (string | number)[] };

export type FunctionAccess<TRecord> = (ctx: AppContext, record?: TRecord) => boolean | Promise<boolean>;

export async function evaluateAccess<TRecord = any>(
  access: Access<TRecord>,
  ctx: AppContext,
  record?: TRecord
): Promise<boolean> {
  // Platform-admin (user.role === 'admin') tier is universal — bypasses
  // role/userRole/record checks. Distinct from org admin (member.role).
  // Lives in the runtime helper so cross-tenant requests by platform
  // admins (where ctx.roles is empty by construction) admit cleanly.
  if (ctx.userRole === 'admin') return true;
  if (typeof access === 'function') {
    return await access(ctx, record);
  }
  return evaluateDeclarativeAccess(access, ctx, record);
}

/**
 * Pre-query access check: evaluates role/userRole gates only and skips
 * `access.record` predicates. Returns true when there's no record-independent
 * way to reject the caller — used before a firewall query to fail fast on
 * role-only mismatches without leaking record existence (404 vs 403 probe).
 *
 * Function-form access is opaque to the pre-record phase, so it returns true
 * here and is fully evaluated post-record by `evaluateAccess`.
 */
export async function evaluateAccessPreRecord<TRecord = any>(
  access: Access<TRecord>,
  ctx: AppContext
): Promise<boolean> {
  // Platform-admin tier (mirrors evaluateAccess). The pre-record gate
  // runs before the firewall query, so admitting here also avoids a
  // useless DB roundtrip on every cross-tenant admin request.
  if (ctx.userRole === 'admin') return true;
  if (typeof access === 'function') return true;
  return evaluateDeclarativeAccessPreRecord(access, ctx);
}

function evaluateDeclarativeAccessPreRecord(
  access: DeclarativeAccess,
  ctx: AppContext
): boolean {
  if (access.or) {
    return access.or.some(a => evaluateDeclarativeAccessPreRecord(a, ctx));
  }
  if (access.and) {
    return access.and.every(a => evaluateDeclarativeAccessPreRecord(a, ctx));
  }
  if (access.roles?.includes('PUBLIC')) return true;
  const rolesPassed = access.roles && access.roles.length > 0
    ? ctx.roles?.some(r => access.roles!.includes(r)) ?? false
    : true;
  const userRolePassed = access.userRole && access.userRole.length > 0
    ? !!ctx.userRole && access.userRole.includes(ctx.userRole)
    : true;
  return rolesPassed && userRolePassed;
}

/**
 * Tagged access result. `null` = passed.
 * Used to split role failures (403 ROLE_REQUIRED) from record-precondition
 * failures (409 ACTION_NOT_ALLOWED_FOR_STATE) on record-action routes.
 */
export type AccessFailureReason = 'role' | 'userRole' | 'record' | null;

export async function evaluateAccessReason<TRecord = any>(
  access: Access<TRecord>,
  ctx: AppContext,
  record?: TRecord
): Promise<AccessFailureReason> {
  // Platform-admin tier (mirrors evaluateAccess). Pass without classifying
  // a failure reason — admins satisfy every clause.
  if (ctx.userRole === 'admin') return null;
  if (typeof access === 'function') {
    const ok = await access(ctx, record);
    return ok ? null : 'record';
  }
  return evaluateDeclarativeAccessReason(access, ctx, record);
}

function evaluateDeclarativeAccessReason<TRecord>(
  access: DeclarativeAccess,
  ctx: AppContext,
  record?: TRecord
): AccessFailureReason {
  if (access.or) {
    let lastReason: AccessFailureReason = 'role';
    for (const sub of access.or) {
      const r = evaluateDeclarativeAccessReason(sub, ctx, record);
      if (r === null) return null;
      if (r === 'record' || (r === 'userRole' && lastReason === 'role')) lastReason = r;
    }
    return lastReason;
  }
  if (access.and) {
    for (const sub of access.and) {
      const r = evaluateDeclarativeAccessReason(sub, ctx, record);
      if (r !== null) return r;
    }
    return null;
  }
  if (access.roles?.includes('PUBLIC')) return null;
  const rolesPassed = access.roles && access.roles.length > 0
    ? ctx.roles?.some(r => access.roles!.includes(r)) ?? false
    : true;
  if (!rolesPassed) return 'role';
  const userRolePassed = access.userRole && access.userRole.length > 0
    ? !!ctx.userRole && access.userRole.includes(ctx.userRole)
    : true;
  if (!userRolePassed) return 'userRole';
  if (access.record && !evaluateRecordConditions(access.record, record, ctx)) return 'record';
  return null;
}

function evaluateDeclarativeAccess<TRecord>(
  access: DeclarativeAccess,
  ctx: AppContext,
  record?: TRecord
): boolean {
  if (access.or) {
    return access.or.some(a => evaluateDeclarativeAccess(a, ctx, record));
  }
  if (access.and) {
    return access.and.every(a => evaluateDeclarativeAccess(a, ctx, record));
  }

  // PUBLIC role grants access without authentication
  if (access.roles?.includes('PUBLIC')) return true;

  // Check roles (org-membership, ctx.roles)
  const rolesPassed = access.roles && access.roles.length > 0
    ? ctx.roles?.some(r => access.roles!.includes(r)) ?? false
    : true;

  // Check userRole (user-table role, ctx.userRole)
  const userRolePassed = access.userRole && access.userRole.length > 0
    ? !!ctx.userRole && access.userRole.includes(ctx.userRole)
    : true;

  // Check record conditions
  const recordPassed = access.record
    ? evaluateRecordConditions(access.record, record, ctx)
    : true;

  return rolesPassed && userRolePassed && recordPassed;
}

function evaluateRecordConditions<TRecord>(
  conditions: RecordConditions,
  record: TRecord | undefined,
  ctx: AppContext
): boolean {
  if (!record) return false;
  return Object.entries(conditions).every(([field, condition]) => {
    const value = (record as any)[field];
    return evaluateFieldCondition(condition, value, ctx);
  });
}

function evaluateFieldCondition(condition: FieldCondition, value: any, ctx: AppContext): boolean {
  if ('equals' in condition) {
    const expected = substituteCtxVar(condition.equals, ctx);
    return value === expected;
  }
  if ('notEquals' in condition) {
    const expected = substituteCtxVar(condition.notEquals, ctx);
    return value !== expected;
  }
  if ('in' in condition) {
    const resolved = condition.in.map((v: any) => substituteCtxVar(v, ctx));
    return resolved.includes(value);
  }
  if ('notIn' in condition) {
    const resolved = condition.notIn.map((v: any) => substituteCtxVar(v, ctx));
    return !resolved.includes(value);
  }
  return false;
}

function substituteCtxVar(val: string | number | boolean, ctx: AppContext): any {
  if (typeof val === 'string' && val.startsWith('$ctx.')) {
    const path = val.substring(5);
    return path.split('.').reduce((o, k) => o?.[k], ctx as any);
  }
  return val;
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
