/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Audit DB Wrapper
 *
 * Wraps Drizzle db to auto-inject audit fields (createdBy, modifiedBy).
 * Uses lazy context access - context is resolved at execution time when
 * .insert() or .update() is called, not when the wrapper is created.
 *
 * Generated by Quickback Compiler.
 */

/**
 * Wraps a Drizzle db instance to automatically inject audit fields.
 *
 * @param db - The Drizzle database instance to wrap
 * @param getCtx - Lazy function to get the current context with userId
 * @returns Wrapped database that injects createdBy/modifiedBy automatically
 */
export function createAuditDb<T extends object>(
  db: T,
  getCtx: () => { userId?: string } | undefined
): T {
  return new Proxy(db, {
    get(target, prop, receiver) {
      const value = Reflect.get(target, prop, receiver);

      if (prop === 'insert') {
        const fn = value as Function;
        return (table: any) => wrapInsertBuilder(fn.call(target, table), getCtx);
      }
      if (prop === 'update') {
        const fn = value as Function;
        return (table: any) => wrapUpdateBuilder(fn.call(target, table), getCtx);
      }
      if (prop === 'transaction') {
        const fn = value as Function;
        return async (cb: Function) =>
          fn.call(target, (tx: any) => cb(createAuditDb(tx, getCtx)));
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  }) as T;
}

/**
 * Resolve the writer userId for audit injection. Fails closed when the
 * surrounding request has no user — every write path in generated routes
 * runs after the auth middleware sets ctx.userId, so a missing value here
 * means auth failed silently or the wrapper is being driven from an
 * unauthenticated path that should not be writing to features tables.
 *
 * If you need to write outside a request (cron, queue handler, seed
 * script), use the unwrapped db (createDb) directly instead of routing
 * through createAuditDb with no context.
 */
function resolveAuditUserId(getCtx: () => any, op: 'insert' | 'update'): string {
  const ctx = getCtx();
  const userId = ctx?.userId;
  if (typeof userId !== 'string' || userId.length === 0) {
    throw new Error(
      'audit-wrapper: ' + op + ' reached without ctx.userId. ' +
      'This indicates an unauthenticated write or auth-context loss. ' +
      'If this is an intentional system-side write, use the unwrapped db directly.'
    );
  }
  return userId;
}

/**
 * Wrap insert builder to inject createdBy and modifiedBy
 */
function wrapInsertBuilder(builder: any, getCtx: () => any) {
  return new Proxy(builder, {
    get(target, prop) {
      const value = Reflect.get(target, prop);
      if (prop === 'values') {
        return (data: any) => {
          const userId = resolveAuditUserId(getCtx, 'insert');
          const enrich = (item: any) => ({
            ...item,
            createdBy: item.createdBy ?? userId,
            modifiedBy: item.modifiedBy ?? userId,
          });
          return value.call(target, Array.isArray(data) ? data.map(enrich) : enrich(data));
        };
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}

/**
 * Wrap update builder to inject modifiedBy (and deletedBy for soft delete)
 */
function wrapUpdateBuilder(builder: any, getCtx: () => any) {
  return new Proxy(builder, {
    get(target, prop) {
      const value = Reflect.get(target, prop);
      if (prop === 'set') {
        return (data: any) => {
          const userId = resolveAuditUserId(getCtx, 'update');
          const enriched = { ...data, modifiedBy: data.modifiedBy ?? userId };
          // If deletedAt is being set, also set deletedBy (soft delete)
          if (data.deletedAt !== undefined) {
            enriched.deletedBy = data.deletedBy ?? userId;
          }
          return value.call(target, enriched);
        };
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
