/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { organization, admin } from "better-auth/plugins";
import { apiKey } from "@better-auth/api-key";



export const TRUSTED_ORIGINS = ["http://localhost:3000"] as const;

// Lazy-load database to avoid bun:sqlite import during CLI schema generation
// (The better-auth CLI runs on Node.js, not Bun)
let _db: any;
let _schema: any;

function getDb() {
    if (!_db) {
        try {
            // Dynamic require avoids top-level evaluation of bun:sqlite
            const mod = require("../db");
            _db = mod.authDb;
            _schema = mod.authSchema;
        } catch {
            // CLI mode — bun:sqlite not available, use dummy for schema generation
            _db = null;
            _schema = {};
        }
    }
    return { db: _db, schema: _schema };
}

export const auth = (() => {
    const { db, schema } = getDb();
    if (db) {
        // Runtime mode — use real database
        return betterAuth({
            
            secret: process.env?.BETTER_AUTH_SECRET,
        baseURL: process.env?.BETTER_AUTH_URL || TRUSTED_ORIGINS[0],
        basePath: '/auth/v1',
        trustedOrigins: TRUSTED_ORIGINS as unknown as string[],
        emailAndPassword: {
                enabled: true,
                autoSignIn: false
            },
        plugins: [organization({ organizationHooks: {
            afterUpdateMemberRole: async ({ member }: { member: any }) => {
              const realtimeUrl = process.env.REALTIME_URL;
              const accessToken = process.env.ACCESS_TOKEN;
              if (!realtimeUrl || !accessToken || !member?.organizationId) return;
              try {
                await fetch(`${realtimeUrl}/realtime/v1/api/broadcast?organizationId=${member.organizationId}`, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json', 'X-Internal-Call': '1', 'X-Internal-Secret': accessToken },
                  body: JSON.stringify({ type: 'broadcast', event: 'auth:token-invalidated', payload: { reason: 'role-changed' }, organizationId: member.organizationId, userId: member.userId }),
                });
              } catch {}
            },
          } }), admin(), apiKey({
          enableMetadata: true,
          enableSessionForAPIKeys: true,
          rateLimit: {
            enabled: true,
            timeWindow: 60,
            maxRequests: 100,
          },
        })],
        rateLimit: {
                enabled: true,
                window: 60,
                max: 100,
                customRules: {
                  "/sign-in/email": { window: 60, max: 10 },
                  "/sign-in/social": { window: 60, max: 10 },
                  "/device/init": { window: 60, max: 5 },
                  "/device/poll": { window: 60, max: 30 },
                  "/device/token": { window: 60, max: 10 }
                }
            },
        session: {
                expiresIn: 30 * 24 * 60 * 60,
                updateAge: 1 * 24 * 60 * 60
            },
        advanced: {
                defaultCookieAttributes: {
                    secure: true,
                    sameSite: 'lax'
                }
            },
    database: drizzleAdapter(db, {
            provider: "sqlite",
            schema,
            usePlural: true,
            debugLogs: false,
            camelCase: true,
        }),

        // Advanced configuration
        advanced: {
            ipAddress: {
                ipAddressHeaders: ["x-forwarded-for", "x-real-ip"],
            },
        },
        });
    }
    // CLI mode — dummy adapter for schema generation only
    return betterAuth({
        basePath: '/auth/v1',
        emailAndPassword: {
                enabled: true,
                autoSignIn: false
            },
        plugins: [organization(), admin(), apiKey({
          enableMetadata: true,
          enableSessionForAPIKeys: true,
          rateLimit: {
            enabled: true,
            timeWindow: 60,
            maxRequests: 100,
          },
        })],
        database: drizzleAdapter({} as D1Database, {
                  provider: "sqlite",
                  usePlural: true,
                  debugLogs: false,
                  camelCase: true
              }),
    });
})();

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
