/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { IncomingRequestCfProperties } from "@cloudflare/workers-types";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { organization, bearer, jwt, admin } from "better-auth/plugins";
import { apiKey } from "@better-auth/api-key";
import { drizzle } from "drizzle-orm/d1";
import type { CloudflareBindings } from "../env";
import * as schema from "../auth/schema";


// Uses AUTH_DB binding (dedicated auth database)

export const TRUSTED_ORIGINS = ["http://localhost:8787"] as const;

// Single auth configuration that handles both CLI and runtime scenarios
function createAuth(env?: CloudflareBindings, cf?: IncomingRequestCfProperties) {
    // Use actual DB for runtime, empty object for CLI
    const db = env ? drizzle(env.AUTH_DB, { schema }) : ({} as any);

    return betterAuth({
        
        secret: env?.BETTER_AUTH_SECRET,
        baseURL: env?.BETTER_AUTH_URL || TRUSTED_ORIGINS[0],
        basePath: '/auth/v1',
        trustedOrigins: TRUSTED_ORIGINS as unknown as string[],
        emailAndPassword: {
                enabled: true,
                autoSignIn: false
            },
        plugins: [organization({ organizationHooks: {
            afterUpdateMemberRole: async ({ member }: { member: any }) => {
              const realtimeUrl = env?.REALTIME_URL;
              const accessToken = env?.ACCESS_TOKEN;
              if (!realtimeUrl || !accessToken || !member?.organizationId) return;
              try {
                await fetch(`${realtimeUrl}/realtime/v1/api/broadcast?organizationId=${member.organizationId}`, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json', 'X-Internal-Call': '1', 'X-Internal-Secret': accessToken },
                  body: JSON.stringify({ type: 'broadcast', event: 'auth:token-invalidated', payload: { reason: 'role-changed' }, organizationId: member.organizationId, userId: member.userId }),
                });
              } catch {}
            },
          } }), bearer(), jwt(), admin(), apiKey({
          enableMetadata: true,
          enableSessionForAPIKeys: true,
          rateLimit: {
            enabled: true,
            timeWindow: 60,
            maxRequests: 100,
          },
        })],
        rateLimit: {
                enabled: true,
                window: 60,
                max: 100
            },
        session: {
                expiresIn: 7 * 24 * 60 * 60,
                updateAge: 1 * 24 * 60 * 60
            },
        advanced: {
                defaultCookieAttributes: {
                    secure: true,
                    sameSite: 'lax'
                }
            },
        database: drizzleAdapter(db, {
                provider: "sqlite",
                schema,
                usePlural: false,
                debugLogs: false,
            }),
    });
}

// Export for CLI schema generation
export const auth = createAuth();

// Export for runtime usage
export { createAuth };

// Export Env type alias for Hono app
export type Env = CloudflareBindings;

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
