/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { AuthDatabase } from '../db';
import { eq, and } from 'drizzle-orm';
import { authSchema } from '../db';

/**
 * Cross-database utility for looking up user data from auth database.
 * Use this in features that need user information.
 */
export async function getUserById(authDb: AuthDatabase, userId: string) {
  const [user] = await authDb
    .select({
      id: authSchema.user.id,
      name: authSchema.user.name,
      email: authSchema.user.email,
    })
    .from(authSchema.user)
    .where(eq(authSchema.user.id, userId));
  return user;
}

/**
 * Get user with organization membership
 */
export async function getUserWithOrg(
  authDb: AuthDatabase,
  userId: string,
  organizationId: string
) {
  const [user] = await authDb
    .select({
      id: authSchema.user.id,
      name: authSchema.user.name,
      email: authSchema.user.email,
    })
    .from(authSchema.user)
    .where(eq(authSchema.user.id, userId));

  if (!user) return null;

  const [member] = await authDb
    .select({
      role: authSchema.member.role,
    })
    .from(authSchema.member)
    .where(and(
      eq(authSchema.member.userId, userId),
      eq(authSchema.member.organizationId, organizationId)
    ));

  return {
    ...user,
    role: member?.role,
  };
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
