/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * ETag Support
 *
 * Compute a weak ETag from a JSON body string.
 * Uses Web Crypto API (available in Cloudflare Workers + Node 18+).
 */
async function computeEtag(body: string): Promise<string> {
  const data = new TextEncoder().encode(body);
  const hash = await crypto.subtle.digest('SHA-256', data);
  const hex = [...new Uint8Array(hash)].map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16);
  return 'W/"' + hex + '"';
}

/**
 * Return a JSON response with ETag support.
 * If the client sends a matching If-None-Match header, returns 304 Not Modified.
 */
export async function jsonWithEtag(c: any, data: any): Promise<Response> {
  const body = JSON.stringify(data);
  const etag = await computeEtag(body);

  const ifNoneMatch = c.req.header('If-None-Match');
  if (ifNoneMatch === etag) {
    return new Response(null, { status: 304, headers: { 'ETag': etag } });
  }

  return new Response(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
      'ETag': etag,
      'Cache-Control': 'no-cache',
    },
  });
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
