/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * JWT Authentication Helper
 *
 * Signs and verifies HMAC-SHA256 JWTs using Web Crypto API.
 * Zero external dependencies — works in Cloudflare Workers, Bun, and Node.
 *
 * Generated by quickback.dev
 */

export interface JwtPayload {
  /** User ID (subject) */
  sub: string;
  /** Active organization ID */
  orgId?: string;
  /** Organization member role (owner/admin/member) */
  role?: string;
  /** User-level role from admin plugin (user/admin) */
  userRole?: string;
  /** User email (for AppContext reconstruction) */
  email?: string;
  /** User display name */
  name?: string;
  /** Issued at (unix seconds) */
  iat: number;
  /** Expires at (unix seconds) */
  exp: number;
}

// ═══════════════════════════════════════════════════════════════════
// Base64url Encoding
// ═══════════════════════════════════════════════════════════════════

function base64urlEncode(data: Uint8Array | string): string {
  const bytes = typeof data === 'string' ? new TextEncoder().encode(data) : data;
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(bytes[i]);
  }
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function base64urlDecode(str: string): Uint8Array {
  let base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  while (base64.length % 4) base64 += '=';
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

// ═══════════════════════════════════════════════════════════════════
// HMAC-SHA256 Key Import
// ═══════════════════════════════════════════════════════════════════

async function importKey(secret: string, usage: KeyUsage): Promise<CryptoKey> {
  return crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    [usage]
  );
}

// ═══════════════════════════════════════════════════════════════════
// Sign & Verify
// ═══════════════════════════════════════════════════════════════════

/**
 * Sign a JWT with HMAC-SHA256
 *
 * @param payload - Claims to include (sub, orgId, role, etc.)
 * @param secret - Signing secret (BETTER_AUTH_SECRET)
 * @param expiresInSeconds - Token lifetime (default: 180 = 3 minutes).
 *   The fast-path verifier in middleware/auth.ts trusts the signature without
 *   re-checking session state, ban status, or current org membership — so a
 *   stolen or pre-revocation token works for the full TTL. Keeping the default
 *   tight bounds the worst-case bad-state window. Long-lived sessions remain
 *   valid via the session cookie; this is just the bearer-cache lifetime.
 * @returns Signed JWT string
 */
export async function signJwt(
  payload: Omit<JwtPayload, 'iat' | 'exp'>,
  secret: string,
  expiresInSeconds: number = 180
): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const fullPayload: JwtPayload = {
    ...payload,
    iat: now,
    exp: now + expiresInSeconds,
  };

  const header = base64urlEncode(JSON.stringify({ alg: 'HS256', typ: 'JWT' }));
  const body = base64urlEncode(JSON.stringify(fullPayload));
  const data = `${header}.${body}`;

  const key = await importKey(secret, 'sign');
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(data) as BufferSource);

  return `${data}.${base64urlEncode(new Uint8Array(signature))}`;
}

/**
 * Verify a JWT signature and check expiration
 *
 * @param token - JWT string to verify
 * @param secret - Signing secret (BETTER_AUTH_SECRET)
 * @returns Decoded payload if valid, null if invalid or expired
 */
export async function verifyJwt(token: string, secret: string): Promise<JwtPayload | null> {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;

    const [header, payload, signature] = parts;
    const data = `${header}.${payload}`;

    const key = await importKey(secret, 'verify');
    const valid = await crypto.subtle.verify(
      'HMAC',
      key,
      base64urlDecode(signature) as BufferSource,
      new TextEncoder().encode(data) as BufferSource
    );

    if (!valid) return null;

    const claims: JwtPayload = JSON.parse(new TextDecoder().decode(base64urlDecode(payload)));

    // Check expiration
    if (claims.exp && claims.exp < Math.floor(Date.now() / 1000)) {
      return null;
    }

    return claims;
  } catch {
    return null;
  }
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
