/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Built-in masking functions
export const masks = {
  /**
   * Mask email address
   * Example: paul@example.com -> p***@e******.com
   */
  email: (v: string): string => {
    if (!v || !v.includes('@')) return v;
    const [local, domain] = v.split('@');
    if (!local || !domain) return v;
    const domainParts = domain.split('.');
    if (domainParts.length === 0) return v;
    const tld = domainParts.pop();
    const domainBase = domainParts.join('.');
    if (!domainBase || !tld) return v;
    return `${local[0]}${'*'.repeat(Math.max(local.length - 1, 1))}@${domainBase[0]}${'*'.repeat(Math.max(domainBase.length - 1, 1))}.${tld}`;
  },

  /**
   * Mask phone number
   * Example: 555-123-4567 -> ******4567
   */
  phone: (v: string): string => {
    if (!v) return v;
    const digits = v.replace(/\D/g, '');
    if (digits.length < 4) return v;
    return `${'*'.repeat(digits.length - 4)}${digits.slice(-4)}`;
  },

  /**
   * Mask SSN (Social Security Number)
   * Example: 123-45-6789 -> *****6789
   */
  ssn: (v: string): string => {
    if (!v) return v;
    const cleaned = v.replace(/\D/g, '');
    if (cleaned.length < 4) return v;
    return `${'*'.repeat(cleaned.length - 4)}${cleaned.slice(-4)}`;
  },

  /**
   * Mask credit card number
   * Example: 4111111111111234 -> ************1234
   */
  creditCard: (v: string): string => {
    if (!v) return v;
    const cleaned = v.replace(/\D/g, '');
    if (cleaned.length < 4) return v;
    return `${'*'.repeat(cleaned.length - 4)}${cleaned.slice(-4)}`;
  },

  /**
   * Mask name (each word)
   * Example: John Doe -> J*** D**
   */
  name: (v: string): string => {
    if (!v) return v;
    return v.split(' ').map(n => n.length > 0 ? `${n[0]}${'*'.repeat(Math.max(n.length - 1, 1))}` : n).join(' ');
  },

  /**
   * Completely redact the value
   * Example: any value -> [REDACTED]
   */
  redact: (_v: string): string => '[REDACTED]',
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
