/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { ZodTypeAny, infer as ZodInfer } from 'zod';
import { formatZodErrors } from './errors';

export type ParseJsonResult<T> =
  | { ok: true; data: T }
  | {
      ok: false;
      code: 'INVALID_JSON' | 'VALIDATION_ERROR';
      error: string;
      fields?: Record<string, string>;
    };

/**
 * Parse request JSON and validate against a Zod schema.
 * Returns structured errors suitable for deterministic 400 responses.
 */
export async function parseJsonWithSchema<TSchema extends ZodTypeAny>(
  request: Request,
  schema: TSchema,
): Promise<ParseJsonResult<ZodInfer<TSchema>>> {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return {
      ok: false,
      code: 'INVALID_JSON',
      error: 'Request body must be valid JSON.',
    };
  }

  const parsed = schema.safeParse(body);
  if (!parsed.success) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      error: 'Request body validation failed.',
      fields: formatZodErrors(parsed.error.issues),
    };
  }

  return { ok: true, data: parsed.data };
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
