/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Scoped DB Wrapper
 *
 * Wraps a Drizzle db instance to automatically enforce security scoping
 * on all queries. Detection combines:
 *
 * - auth-provider defaults (organizationId / ownerId / teamId / deletedAt)
 * - firewall-derived column mappings from compiler config
 *
 * Usage:
 *   const db = createScopedDb(unsafeDb, ctx);
 *   // All queries now auto-filter by org, owner, team, and soft delete
 *   await db.select().from(claims).where(eq(claims.status, 'active'));
 *   // → WHERE status = 'active' AND tenant scopes + soft-delete scopes
 *
 * Escape hatch: use c.get('db') directly for unscoped access, or declare unsafe: true on actions.
 *
 * Generated by Quickback Compiler.
 */
import { eq, and, isNull } from 'drizzle-orm';

type ScopeRule = {
  column: string;
  ctxPath: string;
};

const ORG_SCOPE_RULES: ScopeRule[] = [
  {
    "column": "organizationId",
    "ctxPath": "activeOrgId"
  }
];
const OWNER_SCOPE_RULES: ScopeRule[] = [
  {
    "column": "ownerId",
    "ctxPath": "userId"
  }
];
const TEAM_SCOPE_RULES: ScopeRule[] = [
  {
    "column": "teamId",
    "ctxPath": "activeTeamId"
  }
];
const SOFT_DELETE_COLUMNS: string[] = [
  "deletedAt"
];

function getCtxValue(ctx: any, path: string): any {
  let current = ctx;
  for (const segment of path.split('.')) {
    if (current == null) return undefined;
    current = current[segment];
  }
  return current;
}

function applyScopeRuleConditions(
  conditions: any[],
  table: any,
  ctx: any,
  rules: ScopeRule[]
) {
  for (const rule of rules) {
    if (!(rule.column in table)) continue;
    const value = getCtxValue(ctx, rule.ctxPath);
    if (value !== undefined && value !== null) {
      conditions.push(eq(table[rule.column], value));
    }
  }
}

/**
 * Build scope conditions for a table based on configured/default ownership rules.
 *
 * Exported so record-action routes can compose a record-targeted WHERE clause
 * (`whereRecord(table)`) that AND-merges the same firewall + soft-delete
 * predicates the scoped DB would otherwise inject. Lets handlers write
 * protected-field updates with an *explicit* WHERE instead of trusting an
 * invisible wrapper.
 */
export function buildScopeConditions(table: any, ctx: any) {
  const conditions: any[] = [];

  applyScopeRuleConditions(conditions, table, ctx, ORG_SCOPE_RULES);
  applyScopeRuleConditions(conditions, table, ctx, OWNER_SCOPE_RULES);
  applyScopeRuleConditions(conditions, table, ctx, TEAM_SCOPE_RULES);

  for (const column of SOFT_DELETE_COLUMNS) {
    if (column in table) {
      conditions.push(isNull(table[column]));
    }
  }

  return conditions;
}

/**
 * Wraps a Drizzle db instance to automatically enforce security scoping.
 *
 * @param db - The Drizzle database instance to wrap
 * @param ctx - The application context (userId, activeOrgId, roles)
 * @returns Wrapped database that injects scope conditions automatically
 */
export function createScopedDb<T extends object>(db: T, ctx: any): T {
  return new Proxy(db, {
    get(target, prop, receiver) {
      const value = Reflect.get(target, prop, receiver);

      if (prop === 'select') {
        const fn = value as Function;
        return (...args: any[]) => wrapSelectBuilder(fn.apply(target, args), ctx);
      }
      if (prop === 'update') {
        const fn = value as Function;
        return (table: any) => {
          const builder = fn.call(target, table);
          const conditions = buildScopeConditions(table, ctx);
          return conditions.length > 0 ? wrapWhereBuilder(builder, conditions) : builder;
        };
      }
      if (prop === 'delete') {
        const fn = value as Function;
        return (table: any) => {
          const builder = fn.call(target, table);
          const conditions = buildScopeConditions(table, ctx);
          return conditions.length > 0 ? wrapWhereBuilder(builder, conditions) : builder;
        };
      }
      if (prop === 'insert') {
        const fn = value as Function;
        return (table: any) => {
          const builder = fn.call(target, table);
          return wrapInsertBuilder(builder, table, ctx);
        };
      }
      if (prop === 'transaction') {
        const fn = value as Function;
        return async (cb: Function) =>
          fn.call(target, (tx: any) => cb(createScopedDb(tx, ctx)));
      }
      return typeof value === 'function' ? (value as Function).bind(target) : value;
    },
  }) as T;
}

/**
 * Backwards-compatible wrapper — scopes by organizationId only.
 * Used by CRUD routes that pre-date the full scoped DB.
 */
export function createOrgScopedDb<T extends object>(db: T, orgId: string): T {
  return createScopedDb(db, { activeOrgId: orgId });
}

/**
 * Explicit scope for unsafe handlers.
 *
 * Attaches a .scopeTo(scope) method to an unscoped Drizzle client. Call it
 * when the handler derives the tenancy scope from somewhere other than the
 * ambient request ctx — inbound webhooks, cron jobs, admin tools that
 * impersonate a tenant. Firewall runs unchanged with a synthesized ctx; no
 * manual WHERE clauses or per-row scope fields required.
 *
 * Usage (unsafe action):
 *   execute: async ({ unsafeDb, ctx }) => {
 *     const mailbox = await unsafeDb.select().from(mailboxes)...;
 *     const db = unsafeDb.scopeTo({ organizationId: mailbox.organizationId });
 *     await db.insert(messages).values({ ... }); // scope applied
 *   }
 */
export function attachScopeTo<T extends object>(unsafeDb: T, ctx: any): T {
  (unsafeDb as any).scopeTo = (scope: {
    organizationId?: string;
    userId?: string;
    teamId?: string;
  }) => {
    const scopedCtx = {
      ...ctx,
      activeOrgId: scope.organizationId ?? ctx?.activeOrgId,
      userId: scope.userId ?? ctx?.userId,
      activeTeamId: scope.teamId ?? ctx?.activeTeamId,
    };
    return createScopedDb(unsafeDb, scopedCtx);
  };
  return unsafeDb;
}

/**
 * Wrap select builder to intercept .from(table)
 */
function wrapSelectBuilder(builder: any, ctx: any) {
  return new Proxy(builder, {
    get(target, prop) {
      const value = Reflect.get(target, prop);
      if (prop === 'from') {
        return (table: any, ...rest: any[]) => {
          const result = value.call(target, table, ...rest);
          const conditions = buildScopeConditions(table, ctx);
          return conditions.length > 0 ? wrapWhereBuilder(result, conditions) : result;
        };
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}

/**
 * Wrap a query builder (select/update/delete) to inject scope conditions into .where().
 *
 * Handles three cases:
 * 1. .where(condition) called → ANDs user condition with scope conditions
 * 2. .where() called with no args → injects scope conditions alone
 * 3. Query awaited without .where() → auto-injects via .then() interception
 *
 * Maintains proxy through method chains (.orderBy, .limit, etc.) so the
 * scope conditions are always applied regardless of chaining order.
 */
function wrapWhereBuilder(builder: any, scopeConditions: any[]) {
  let whereApplied = false;

  const combinedScope = scopeConditions.length === 1
    ? scopeConditions[0]
    : and(...scopeConditions);

  const proxy: any = new Proxy(builder, {
    get(target, prop) {
      if (prop === 'where') {
        return (...args: any[]) => {
          whereApplied = true;
          const userCond = args[0];
          const combined = userCond != null ? and(userCond, combinedScope) : combinedScope;
          Reflect.get(target, 'where').call(target, combined);
          return proxy;
        };
      }

      if (prop === 'then') {
        if (!whereApplied) {
          whereApplied = true;
          target.where(combinedScope);
        }
        return target.then.bind(target);
      }

      const value = Reflect.get(target, prop);
      if (typeof value === 'function') {
        return (...args: any[]) => {
          const result = value.apply(target, args);
          // Maintain proxy through chainable methods (they return 'this')
          if (result === target) return proxy;
          return result;
        };
      }

      return value;
    },
  });

  return proxy;
}

/**
 * Wrap insert builder to inject ownership fields into .values()
 */
function wrapInsertBuilder(builder: any, table: any, ctx: any) {
  const allRules = [...ORG_SCOPE_RULES, ...OWNER_SCOPE_RULES, ...TEAM_SCOPE_RULES];
  const hasManagedColumns = allRules.some((rule) => rule.column in table);

  if (!hasManagedColumns) return builder;

  return new Proxy(builder, {
    get(target, prop) {
      const value = Reflect.get(target, prop);
      if (prop === 'values') {
        return (data: any) => {
          const enrich = (item: any) => {
            const enriched = { ...item };

            for (const rule of allRules) {
              if (!(rule.column in table)) continue;
              const scopedValue = getCtxValue(ctx, rule.ctxPath);
              if (scopedValue !== undefined && scopedValue !== null) {
                enriched[rule.column] = scopedValue;
              }
            }

            return enriched;
          };
          return value.call(target, Array.isArray(data) ? data.map(enrich) : enrich(data));
        };
      }
      return typeof value === 'function' ? value.bind(target) : value;
    },
  });
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
