/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { drizzle } from 'drizzle-orm/d1';
import { auditEvents } from '../db/audit-schema';

export type SecurityAuditResult = 'success' | 'denied' | 'error';

export interface SecurityAuditEvent {
  actionName: string;
  resource: string;
  operation: string;
  reason: string;
  targetScope: 'organization' | 'all';
  result: SecurityAuditResult;
  targetOrgId?: string;
  targetRecordId?: string;
  rowCount?: number;
  errorCode?: string;
  errorMessage?: string;
  metadata?: Record<string, unknown>;
  resultData?: unknown;
}

function inferRowCount(value: unknown): number | undefined {
  if (Array.isArray(value)) return value.length;
  if (!value || typeof value !== 'object') return undefined;

  const rowCount = (value as any).rowCount;
  if (typeof rowCount === 'number') return rowCount;

  const affected = (value as any).affectedRows;
  if (typeof affected === 'number') return affected;

  return 1;
}

function normalizeRequestId(c: any): string {
  const requestId = c?.req?.header?.('x-request-id')
    || c?.req?.header?.('cf-ray')
    || c?.req?.header?.('x-correlation-id');
  if (requestId && typeof requestId === 'string') return requestId;
  return crypto.randomUUID();
}

export async function logSecurityAudit(c: any, event: SecurityAuditEvent): Promise<void> {
  const binding = c?.env?.AUDIT_DB;
  if (!binding) {
    throw new Error(
      'Missing AUDIT_DB binding. Unsafe cross-tenant actions require mandatory audit logging. ' +
      'Add compiler.migrations/audit DB config and bind the audit database.'
    );
  }

  const db = drizzle(binding);
  const ctx = c?.get?.('ctx') || {};
  const rowCount = typeof event.rowCount === 'number' ? event.rowCount : inferRowCount(event.resultData);

  await db.insert(auditEvents).values({
    id: crypto.randomUUID(),
    requestId: normalizeRequestId(c),
    actorUserId: ctx.userId || null,
    actorUserRole: ctx.userRole || null,
    actorOrgId: ctx.activeOrgId || null,
    actionName: event.actionName,
    resource: event.resource,
    operation: event.operation,
    targetScope: event.targetScope,
    targetOrgId: event.targetOrgId || null,
    targetRecordId: event.targetRecordId || null,
    unsafeReason: event.reason,
    result: event.result,
    rowCount: typeof rowCount === 'number' ? rowCount : null,
    errorCode: event.errorCode || null,
    errorMessage: event.errorMessage || null,
    metadata: event.metadata ? JSON.stringify(event.metadata) : null,
    createdAt: new Date(),
  });
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
