/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Generated security helpers for jobPostings
import { eq, and, isNull, type SQL } from 'drizzle-orm';
import type { Context } from 'hono';
import { jobPostings } from './schema';
import type { AppContext } from '../../lib/types';

/**
 * Firewall conditions for jobPostings
 * 2 predicates
 */
export function buildFirewallConditions(ctx: AppContext): SQL | undefined {
  return and(eq(jobPostings.organizationId, ctx.activeOrgId!), isNull(jobPostings.deletedAt));
}

/**
 * Helper for manual routes — wraps handler with auth check and firewall
 */
export async function withFirewall<T>(
  c: Context,
  handler: (ctx: AppContext, firewall: SQL | undefined) => Promise<T>
): Promise<Response | T> {
  const ctx = c.get('ctx') as AppContext;
  if (!ctx?.userId) {
    return c.json({ error: 'Unauthorized', code: 'AUTH_REQUIRED' }, 401);
  }
  const firewall = buildFirewallConditions(ctx);
  return handler(ctx, firewall);
}

/**
 * Guards configuration for field modification rules
 */
export const GUARDS_CONFIG = {
  createable: new Set<string>(['jobId', 'slug', 'headline', 'summary', 'location', 'employmentType']),
  updatable: new Set<string>(['slug', 'headline', 'summary', 'location', 'employmentType']),
  protected: {} as Record<string, Set<string>>,
  immutable: new Set<string>(['jobId']),
  systemManaged: new Set<string>(['createdAt', 'createdBy', 'modifiedAt', 'modifiedBy', 'deletedAt', 'deletedBy', 'organizationId']),
};

/**
 * Validates field input for CREATE operations.
 *
 * Rules:
 * - System-managed fields are rejected
 * - Protected fields are rejected (can only be set via actions)
 * - Must be either createable or immutable
 *
 * @param input - Input data from client
 * @returns Validation result with categorized errors
 */
export function validateCreate(input: Record<string, any>): {
  valid: boolean;
  systemManaged: string[];
  protected: Array<{ field: string; actions: string[] }>;
  notCreateable: string[];
} {
  const systemManaged: string[] = [];
  const protectedFields: Array<{ field: string; actions: string[] }> = [];
  const notCreateable: string[] = [];

  for (const field of Object.keys(input)) {
    // Reject system-managed fields
    if (GUARDS_CONFIG.systemManaged.has(field)) {
      systemManaged.push(field);
      continue;
    }

    // Reject protected fields on create
    if (field in GUARDS_CONFIG.protected) {
      const actions = [...GUARDS_CONFIG.protected[field]];
      protectedFields.push({ field, actions });
      continue;
    }

    // Check if field is createable or immutable (both allowed on create)
    if (!GUARDS_CONFIG.createable.has(field) && !GUARDS_CONFIG.immutable.has(field)) {
      notCreateable.push(field);
    }
  }

  const valid = systemManaged.length === 0 && protectedFields.length === 0 && notCreateable.length === 0;

  return { valid, systemManaged, protected: protectedFields, notCreateable };
}

/**
 * Validates field input for UPDATE operations.
 *
 * Rules:
 * - System-managed fields are rejected
 * - Immutable fields are rejected
 * - Protected fields are rejected (with hint about which actions can modify them)
 * - Must be in updatable list
 *
 * @param input - Input data from client
 * @returns Validation result with categorized errors
 */
export function validateUpdate(input: Record<string, any>): {
  valid: boolean;
  systemManaged: string[];
  immutable: string[];
  protected: Array<{ field: string; actions: string[] }>;
  notUpdatable: string[];
} {
  const systemManaged: string[] = [];
  const immutable: string[] = [];
  const protectedFields: Array<{ field: string; actions: string[] }> = [];
  const notUpdatable: string[] = [];

  for (const field of Object.keys(input)) {
    // Reject system-managed fields
    if (GUARDS_CONFIG.systemManaged.has(field)) {
      systemManaged.push(field);
      continue;
    }

    // Reject immutable fields
    if (GUARDS_CONFIG.immutable.has(field)) {
      immutable.push(field);
      continue;
    }

    // Reject protected fields with hint
    if (field in GUARDS_CONFIG.protected) {
      const actions = [...GUARDS_CONFIG.protected[field]];
      protectedFields.push({ field, actions });
      continue;
    }

    // Check if field is updatable
    if (!GUARDS_CONFIG.updatable.has(field)) {
      notUpdatable.push(field);
    }
  }

  const valid = systemManaged.length === 0 && immutable.length === 0 && protectedFields.length === 0 && notUpdatable.length === 0;

  return { valid, systemManaged, immutable, protected: protectedFields, notUpdatable };
}

// CRUD Access
export const CRUD_ACCESS = {
  "create": {
    "access": {
      "roles": [
        "admin",
        "owner"
      ]
    }
  },
  "update": {
    "access": {
      "roles": [
        "admin",
        "owner"
      ]
    }
  },
  "delete": {
    "access": {
      "roles": [
        "owner"
      ]
    },
    "mode": "soft"
  }
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
