/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { index, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from 'drizzle-orm';
import { jobs } from "../jobs/schema";

// Generated schema for job-postings
// Combined from 1 table definition(s)

// Table: jobPostings
/**
 * Job postings — the *public* face of an open role.
 *
 * Distinct from `jobs` (which is the internal record with salary range,
 * draft state, etc.). A `jobPosting` is the curated, careers-page-friendly
 * projection: a slug, a headline, a marketing-copy summary, and a target
 * application form.
 *
 * Exercises the parts of the access model nothing else in the example
 * does:
 *
 *  - `roles: ["PUBLIC"]` — read endpoints are *unauthenticated*. Anyone
 *    can hit `GET /api/v1/job-postings?organizationId=org_xyz` and the
 *    careers page renders. The firewall still applies, so the
 *    `organizationId` query param is mandatory (otherwise 400
 *    `ORG_REQUIRED`).
 *  - **Mandatory audit logging on every PUBLIC invocation.** The
 *    runtime automatically inserts an `audit_events` row (IP, input,
 *    result, timing) for every call to a PUBLIC route — no opt-in
 *    needed. Use cases: rate-limit visibility, abuse forensics,
 *    careers-page analytics.
 *  - **PUBLIC + org-scoped together.** Common pattern for B2B
 *    "tenant-owned public surfaces": each tenant has their own
 *    careers page; the firewall isolates one tenant's postings from
 *    another's.
 *  - Auth-gated mutations layered on top — the same resource exposes
 *    `POST` / `PATCH` / `DELETE` to admins/owners only, so the
 *    careers-page UI is read-only and the CMS handles writes.
 *  - Composite uniqueness on `(organizationId, slug)` so two tenants
 *    can both have `/careers/senior-engineer` without colliding.
 *
 * Why a separate feature instead of a view on `jobs`: views project
 * fields but don't change the auth gate — a PUBLIC view on a
 * member-only feature would be rejected by the validator (the view's
 * roles must be a subset of the parent's). Decoupling lets the
 * public-facing fields evolve without ever touching the internal
 * `jobs` schema, and any data leak risk is bounded to the columns
 * declared here.
 */
export const jobPostings = sqliteTable("jobPostings", {
  id: text("id").primaryKey(),
  jobId: text("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }),
  slug: text("slug").notNull(),
  headline: text("headline").notNull(),
  summary: text("summary"),
  location: text("location"),
  employmentType: text("employment_type", { enum: ["full-time", "part-time", "contract", "internship"] as const }).default("full-time").notNull(),
  organizationId: text("organization_id").notNull(),

    createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    modifiedAt: text("modified_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text("deleted_at"),
    createdBy: text("created_by"),
    modifiedBy: text("modified_by"),
    deletedBy: text("deleted_by"),
  }, (t) => ({
  jobPostings_organizationId_slug_unique: uniqueIndex("jobPostings_organizationId_slug_unique").on(t.organizationId, t.slug),
  jobPostings_organization_id_deleted_at_idx: index("jobPostings_organization_id_deleted_at_idx").on(t.organizationId, t.deletedAt),
  jobPostings_job_id_idx: index("jobPostings_job_id_idx").on(t.jobId)
}));

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
