--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
CREATE UNIQUE INDEX `applications_jobId_candidateId_unique` ON `applications` (`job_id`,`candidate_id`);
CREATE INDEX `applications_organization_id_deleted_at_idx` ON `applications` (`organization_id`,`deleted_at`);
CREATE INDEX `applications_job_id_idx` ON `applications` (`job_id`);
CREATE INDEX `applications_candidate_id_idx` ON `applications` (`candidate_id`);
CREATE UNIQUE INDEX `candidates_organizationId_email_unique` ON `candidates` (`organization_id`,`email`);
CREATE INDEX `candidates_organization_id_deleted_at_idx` ON `candidates` (`organization_id`,`deleted_at`);
CREATE INDEX `candidates_created_at_idx` ON `candidates` (`created_at`);
CREATE INDEX `candidates_name_idx` ON `candidates` (`name`);
CREATE INDEX `candidates_email_idx` ON `candidates` (`email`);
CREATE INDEX `jobs_organization_id_deleted_at_idx` ON `jobs` (`organization_id`,`deleted_at`);

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
