--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
PRAGMA foreign_keys=OFF;
CREATE TABLE `__new_applications` (
	`id` text PRIMARY KEY NOT NULL,
	`job_id` text NOT NULL,
	`candidate_id` text NOT NULL,
	`status` text DEFAULT 'applied' NOT NULL,
	`applied_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
	`notes` text,
	`organization_id` text NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`modified_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	`created_by` text,
	`modified_by` text,
	`deleted_by` text,
	FOREIGN KEY (`job_id`) REFERENCES `jobs`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`candidate_id`) REFERENCES `candidates`(`id`) ON UPDATE no action ON DELETE cascade
);

INSERT INTO `__new_applications`("id", "job_id", "candidate_id", "status", "applied_at", "notes", "organization_id", "created_at", "modified_at", "deleted_at", "created_by", "modified_by", "deleted_by") SELECT "id", "job_id", "candidate_id", "status", "applied_at", "notes", "organization_id", "created_at", "modified_at", "deleted_at", "created_by", "modified_by", "deleted_by" FROM `applications`;
DROP TABLE `applications`;
ALTER TABLE `__new_applications` RENAME TO `applications`;
PRAGMA foreign_keys=ON;
CREATE INDEX `applications_status_idx` ON `applications` (`status`);
CREATE UNIQUE INDEX `applications_jobId_candidateId_unique` ON `applications` (`job_id`,`candidate_id`);
CREATE INDEX `applications_organization_id_deleted_at_idx` ON `applications` (`organization_id`,`deleted_at`);
CREATE INDEX `applications_job_id_idx` ON `applications` (`job_id`);
CREATE INDEX `applications_candidate_id_idx` ON `applications` (`candidate_id`);

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
