--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
CREATE TABLE `custom_view` (
	`id` text PRIMARY KEY NOT NULL,
	`table_name` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`layout_config` text NOT NULL,
	`is_shared` integer DEFAULT 0 NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`modified_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	`created_by` text,
	`modified_by` text,
	`deleted_by` text
);

ALTER TABLE `candidates` ADD `legal_name` text;
ALTER TABLE `candidates` ADD `government_id` text;

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
