--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
CREATE TABLE `interview_scores` (
	`id` text PRIMARY KEY NOT NULL,
	`interview_id` text NOT NULL,
	`scorer_id` text NOT NULL,
	`rating` integer NOT NULL,
	`recommendation` text NOT NULL,
	`comments` text(2000),
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`modified_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	`created_by` text,
	`modified_by` text,
	`deleted_by` text,
	`organization_id` text NOT NULL
);

CREATE INDEX `interview_scores_organization_id_deleted_at_idx` ON `interview_scores` (`organization_id`,`deleted_at`);
CREATE TABLE `interviews` (
	`id` text PRIMARY KEY NOT NULL,
	`application_id` text NOT NULL,
	`scheduled_by` text NOT NULL,
	`organization_id` text NOT NULL,
	`scheduled_at` text NOT NULL,
	`duration_min` integer DEFAULT 30 NOT NULL,
	`location` text,
	`status` text DEFAULT 'scheduled' NOT NULL,
	`private_notes` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`modified_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`deleted_at` text,
	`created_by` text,
	`modified_by` text,
	`deleted_by` text,
	FOREIGN KEY (`application_id`) REFERENCES `applications`(`id`) ON UPDATE no action ON DELETE cascade
);

CREATE INDEX `interviews_status_idx` ON `interviews` (`status`);
CREATE INDEX `interviews_organization_id_deleted_at_idx` ON `interviews` (`organization_id`,`deleted_at`);
CREATE INDEX `interviews_application_id_idx` ON `interviews` (`application_id`);

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
