/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * MCP-over-HTTP server — auto-generated from this project's OpenAPI spec.
 *
 * Do not edit by hand; re-run `quickback compile` to refresh the tool list.
 *
 * One JSON-RPC 2.0 endpoint at POST /mcp. One MCP tool per OpenAPI
 * operation; each tool call re-enters the same Hono app via
 * `app.request(...)`, so auth + firewall + guards + masking all apply.
 */

import type { Hono } from 'hono';
import type { Env } from '../lib/auth';
import type { AppContext } from '../lib/types';
import type { Services } from '../lib/services';

type HonoAppType = Hono<{ Bindings: Env; Variables: { ctx: AppContext; db: any; services: Services; requestId: string } }>;

type RpcId = string | number | null | undefined;
interface RpcMessage {
  jsonrpc: '2.0';
  id?: RpcId;
  method?: string;
  params?: Record<string, unknown>;
}

interface ToolEntry {
  name: string;
  description: string;
  inputSchema: unknown;
  annotations?: Record<string, unknown>;
  _method: string;
  _path: string;
  _pathParams: string[];
  _queryParams: string[];
  _bodyFields: string[] | null;
  _unsafe?: boolean;
}

const TOOLS: ToolEntry[] = [
  {
    "name": "acceptInvitation",
    "description": "Accept an organization invitation",
    "inputSchema": {
      "type": "object",
      "properties": {
        "invitationId": {
          "type": "string"
        }
      },
      "required": [
        "invitationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/accept-invitation",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "invitationId"
    ]
  },
  {
    "name": "adminBanUser",
    "description": "Ban a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/ban-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId"
    ]
  },
  {
    "name": "adminCreateUser",
    "description": "Create a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "minLength": 8
        },
        "name": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password",
        "name"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/create-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "email",
      "password",
      "name",
      "role"
    ]
  },
  {
    "name": "adminImpersonateUser",
    "description": "Impersonate a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/impersonate-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId"
    ]
  },
  {
    "name": "adminListUsers",
    "description": "List all users (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/admin/list-users",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "adminRemoveUser",
    "description": "Remove a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/remove-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId"
    ]
  },
  {
    "name": "adminRevokeUserSession",
    "description": "Revoke all sessions for a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/revoke-user-session",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId"
    ]
  },
  {
    "name": "adminSetRole",
    "description": "Set user role (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": [
        "userId",
        "role"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/set-role",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId",
      "role"
    ]
  },
  {
    "name": "adminStopImpersonating",
    "description": "Stop impersonating a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/stop-impersonating",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "adminUnbanUser",
    "description": "Unban a user (admin only)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/admin/unban-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "userId"
    ]
  },
  {
    "name": "applicationsAdvance",
    "description": "Move an application forward in the pipeline.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "nextStatus": {
          "type": "string",
          "enum": [
            "screening",
            "interview",
            "offer"
          ]
        },
        "notes": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications/{id}/advance",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "nextStatus",
      "notes"
    ]
  },
  {
    "name": "applicationsHire",
    "description": "Finalize an offer — the candidate accepted.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications/{id}/hire",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": []
  },
  {
    "name": "applicationsReject",
    "description": "Reject an application with an optional reason.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "reason": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications/{id}/reject",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "reason"
    ]
  },
  {
    "name": "applicationsWithdraw",
    "description": "Candidate withdrew their application.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications/{id}/withdraw",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": []
  },
  {
    "name": "batchCreateApplications",
    "description": "Batch create Applications records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/ApplicationsCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateAtsImports",
    "description": "Batch create AtsImports records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/AtsImportsCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/ats-imports/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateCandidates",
    "description": "Batch create Candidates records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/CandidatesCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/candidates/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateCustomView",
    "description": "Batch create CustomView records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/CustomViewCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/custom-view/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateInterviews",
    "description": "Batch create Interviews records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/InterviewsCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/interviews/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateJobPostings",
    "description": "Batch create JobPostings records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/JobPostingsCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/job-postings/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchCreateJobs",
    "description": "Batch create Jobs records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/components/schemas/JobsCreate"
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/jobs/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchDeleteApplications",
    "description": "Batch delete Applications records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/applications/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteAtsImports",
    "description": "Batch delete AtsImports records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/ats-imports/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteCandidates",
    "description": "Batch delete Candidates records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/candidates/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteCustomView",
    "description": "Batch delete CustomView records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/custom-view/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteInterviews",
    "description": "Batch delete Interviews records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/interviews/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteJobPostings",
    "description": "Batch delete JobPostings records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/job-postings/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchDeleteJobs",
    "description": "Batch delete Jobs records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "ids": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        }
      },
      "required": [
        "ids"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/jobs/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "ids"
    ]
  },
  {
    "name": "batchUpdateApplications",
    "description": "Batch update Applications records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/ApplicationsUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/applications/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateAtsImports",
    "description": "Batch update AtsImports records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/AtsImportsUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/ats-imports/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateCandidates",
    "description": "Batch update Candidates records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/CandidatesUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/candidates/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateCustomView",
    "description": "Batch update CustomView records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/CustomViewUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/custom-view/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateInterviews",
    "description": "Batch update Interviews records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/InterviewsUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/interviews/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateJobPostings",
    "description": "Batch update JobPostings records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/JobPostingsUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/job-postings/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "batchUpdateJobs",
    "description": "Batch update Jobs records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid"
              },
              "data": {
                "$ref": "#/components/schemas/JobsUpdate"
              }
            }
          }
        }
      },
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/jobs/batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "items"
    ]
  },
  {
    "name": "cancelInvitation",
    "description": "Cancel a pending invitation",
    "inputSchema": {
      "type": "object",
      "properties": {
        "invitationId": {
          "type": "string"
        }
      },
      "required": [
        "invitationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/cancel-invitation",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "invitationId"
    ]
  },
  {
    "name": "changeEmail",
    "description": "Change the current user email",
    "inputSchema": {
      "type": "object",
      "properties": {
        "newEmail": {
          "type": "string",
          "format": "email"
        }
      },
      "required": [
        "newEmail"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/change-email",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "newEmail"
    ]
  },
  {
    "name": "changePassword",
    "description": "Change the current user password",
    "inputSchema": {
      "type": "object",
      "properties": {
        "currentPassword": {
          "type": "string"
        },
        "newPassword": {
          "type": "string",
          "minLength": 8
        }
      },
      "required": [
        "currentPassword",
        "newPassword"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/change-password",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "currentPassword",
      "newPassword"
    ]
  },
  {
    "name": "createApiKey",
    "description": "Create a new API key",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "expiresIn": {
          "type": "integer",
          "description": "Expiry in seconds"
        },
        "metadata": {
          "type": "object"
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/api-key/create",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "name",
      "expiresIn",
      "metadata"
    ]
  },
  {
    "name": "createApplications",
    "description": "Create a new Applications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "jobId": {
          "type": "string"
        },
        "candidateId": {
          "type": "string"
        },
        "notes": {
          "type": "string"
        }
      },
      "required": [
        "jobId",
        "candidateId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/applications",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "jobId",
      "candidateId",
      "notes"
    ]
  },
  {
    "name": "createAtsImports",
    "description": "Create a new AtsImports",
    "inputSchema": {
      "type": "object",
      "properties": {
        "externalId": {
          "type": "string"
        },
        "sourceSystem": {
          "type": "string"
        },
        "payload": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "externalId",
        "sourceSystem",
        "payload",
        "organizationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/ats-imports",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "externalId",
      "sourceSystem",
      "payload",
      "error",
      "organizationId"
    ]
  },
  {
    "name": "createCandidates",
    "description": "Create a new Candidates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "resumeUrl": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "internalNotes": {
          "type": "string"
        },
        "legalName": {
          "type": "string"
        },
        "governmentId": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "source"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/candidates",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "name",
      "email",
      "phone",
      "resumeUrl",
      "source",
      "internalNotes",
      "legalName",
      "governmentId"
    ]
  },
  {
    "name": "createCustomView",
    "description": "Create a new CustomView",
    "inputSchema": {
      "type": "object",
      "properties": {
        "tableName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "layoutConfig": {
          "type": "string"
        }
      },
      "required": [
        "tableName",
        "name",
        "layoutConfig"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/custom-view",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "tableName",
      "name",
      "description",
      "layoutConfig"
    ]
  },
  {
    "name": "createInterviews",
    "description": "Create a new Interviews",
    "inputSchema": {
      "type": "object",
      "properties": {
        "applicationId": {
          "type": "string"
        },
        "scheduledAt": {
          "type": "string"
        },
        "durationMin": {
          "type": "integer"
        },
        "location": {
          "type": "string"
        },
        "privateNotes": {
          "type": "string"
        }
      },
      "required": [
        "applicationId",
        "durationMin"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/interviews",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "applicationId",
      "scheduledAt",
      "durationMin",
      "location",
      "privateNotes"
    ]
  },
  {
    "name": "createJobPostings",
    "description": "Create a new JobPostings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "jobId": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "headline": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "employmentType": {
          "type": "string"
        }
      },
      "required": [
        "jobId",
        "slug",
        "headline",
        "employmentType"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/job-postings",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "jobId",
      "slug",
      "headline",
      "summary",
      "location",
      "employmentType"
    ]
  },
  {
    "name": "createJobs",
    "description": "Create a new Jobs",
    "inputSchema": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "salaryMin": {
          "type": "integer"
        },
        "salaryMax": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "department",
        "status"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/jobs",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "title",
      "department",
      "status",
      "salaryMin",
      "salaryMax",
      "description"
    ]
  },
  {
    "name": "createOrganization",
    "description": "Create a new organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "logo": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "name",
        "slug"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/create",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "name",
      "slug",
      "logo"
    ]
  },
  {
    "name": "deleteApiKey",
    "description": "Delete an API key",
    "inputSchema": {
      "type": "object",
      "properties": {
        "keyId": {
          "type": "string"
        }
      },
      "required": [
        "keyId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/api-key/delete",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "keyId"
    ]
  },
  {
    "name": "deleteApplications",
    "description": "Delete a Applications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/applications/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteAtsImports",
    "description": "Delete a AtsImports",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/ats-imports/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteCandidates",
    "description": "Delete a Candidates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/candidates/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteCustomView",
    "description": "Delete a CustomView",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/custom-view/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteInterviews",
    "description": "Delete a Interviews",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/interviews/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteJobPostings",
    "description": "Delete a JobPostings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/job-postings/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteJobs",
    "description": "Delete a Jobs",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "delete",
    "_path": "/api/v1/jobs/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "deleteOrganization",
    "description": "Delete an organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/delete",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId"
    ]
  },
  {
    "name": "deleteUser",
    "description": "Delete the current user account",
    "inputSchema": {
      "type": "object",
      "properties": {
        "password": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/delete-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "password"
    ]
  },
  {
    "name": "forgetPassword",
    "description": "Request a password reset email",
    "inputSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "redirectTo": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "email"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/forget-password",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "email",
      "redirectTo"
    ]
  },
  {
    "name": "getApplications",
    "description": "Get a Applications by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/applications/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getApplicationsViewPipeline",
    "description": "Get Applications pipeline view",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/applications/views/pipeline",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getAtsImports",
    "description": "Get a AtsImports by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/ats-imports/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getCandidates",
    "description": "Get a Candidates by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/candidates/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getCandidatesViewFull",
    "description": "Get Candidates full view",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/candidates/views/full",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getCandidatesViewPipeline",
    "description": "Get Candidates pipeline view",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/candidates/views/pipeline",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getCustomView",
    "description": "Get a CustomView by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/custom-view/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getFullOrganization",
    "description": "Get organization with members and invitations",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/organization/get-full-organization",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getInterviews",
    "description": "Get a Interviews by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/interviews/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getJobPostings",
    "description": "Get a JobPostings by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/job-postings/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getJobs",
    "description": "Get a Jobs by ID",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/jobs/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "getSession",
    "description": "Get current session and user",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/get-session",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "interviewsComplete",
    "description": "Finalize an interview with a score and recommendation.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "rating": {
          "type": "integer"
        },
        "recommendation": {
          "type": "string",
          "enum": [
            "strong-no",
            "no",
            "neutral",
            "yes",
            "strong-yes"
          ]
        },
        "comments": {
          "type": "string",
          "nullable": true
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/interviews/{id}/complete",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "rating",
      "recommendation",
      "comments"
    ]
  },
  {
    "name": "interviewsReschedule",
    "description": "Move an interview to a new datetime.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "scheduledAt": {
          "type": "string",
          "format": "date-time"
        },
        "durationMin": {
          "type": "integer",
          "nullable": true
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/interviews/{id}/reschedule",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "scheduledAt",
      "durationMin"
    ]
  },
  {
    "name": "inviteMember",
    "description": "Invite a user to the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "role": {
          "type": "string",
          "enum": [
            "owner",
            "admin",
            "member"
          ]
        }
      },
      "required": [
        "organizationId",
        "email",
        "role"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/invite-member",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId",
      "email",
      "role"
    ]
  },
  {
    "name": "listApiKeys",
    "description": "List API keys for the current user",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/api-key/list",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "listApplications",
    "description": "List Applications records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "jobId": {
          "type": "string",
          "description": "Filter by jobId (exact match)"
        },
        "candidateId": {
          "type": "string",
          "description": "Filter by candidateId (exact match)"
        },
        "status": {
          "type": "string",
          "description": "Filter by status (exact match)"
        },
        "notes": {
          "type": "string",
          "description": "Filter by notes (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/applications",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "jobId",
      "candidateId",
      "status",
      "notes",
      "organizationId",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listAtsImports",
    "description": "List AtsImports records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "externalId": {
          "type": "string",
          "description": "Filter by externalId (exact match)"
        },
        "sourceSystem": {
          "type": "string",
          "description": "Filter by sourceSystem (exact match)"
        },
        "payload": {
          "type": "string",
          "description": "Filter by payload (exact match)"
        },
        "status": {
          "type": "string",
          "description": "Filter by status (exact match)"
        },
        "error": {
          "type": "string",
          "description": "Filter by error (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/ats-imports",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "externalId",
      "sourceSystem",
      "payload",
      "status",
      "error",
      "organizationId",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listCandidates",
    "description": "List Candidates records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "name": {
          "type": "string",
          "description": "Filter by name (exact match)"
        },
        "email": {
          "type": "string",
          "description": "Filter by email (exact match)"
        },
        "phone": {
          "type": "string",
          "description": "Filter by phone (exact match)"
        },
        "resumeUrl": {
          "type": "string",
          "description": "Filter by resumeUrl (exact match)"
        },
        "source": {
          "type": "string",
          "description": "Filter by source (exact match)"
        },
        "internalNotes": {
          "type": "string",
          "description": "Filter by internalNotes (exact match)"
        },
        "legalName": {
          "type": "string",
          "description": "Filter by legalName (exact match)"
        },
        "governmentId": {
          "type": "string",
          "description": "Filter by governmentId (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/candidates",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "name",
      "email",
      "phone",
      "resumeUrl",
      "source",
      "internalNotes",
      "legalName",
      "governmentId",
      "organizationId",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listCustomView",
    "description": "List CustomView records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "tableName": {
          "type": "string",
          "description": "Filter by tableName (exact match)"
        },
        "name": {
          "type": "string",
          "description": "Filter by name (exact match)"
        },
        "description": {
          "type": "string",
          "description": "Filter by description (exact match)"
        },
        "layoutConfig": {
          "type": "string",
          "description": "Filter by layoutConfig (exact match)"
        },
        "isShared": {
          "type": "integer",
          "description": "Filter by isShared (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        },
        "isShared.gt": {
          "type": "integer",
          "description": "Filter isShared gt"
        },
        "isShared.gte": {
          "type": "integer",
          "description": "Filter isShared gte"
        },
        "isShared.lt": {
          "type": "integer",
          "description": "Filter isShared lt"
        },
        "isShared.lte": {
          "type": "integer",
          "description": "Filter isShared lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/custom-view",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "tableName",
      "name",
      "description",
      "layoutConfig",
      "isShared",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte",
      "isShared.gt",
      "isShared.gte",
      "isShared.lt",
      "isShared.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listInterviews",
    "description": "List Interviews records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "applicationId": {
          "type": "string",
          "description": "Filter by applicationId (exact match)"
        },
        "scheduledBy": {
          "type": "string",
          "description": "Filter by scheduledBy (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "durationMin": {
          "type": "integer",
          "description": "Filter by durationMin (exact match)"
        },
        "location": {
          "type": "string",
          "description": "Filter by location (exact match)"
        },
        "status": {
          "type": "string",
          "description": "Filter by status (exact match)"
        },
        "privateNotes": {
          "type": "string",
          "description": "Filter by privateNotes (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        },
        "durationMin.gt": {
          "type": "integer",
          "description": "Filter durationMin gt"
        },
        "durationMin.gte": {
          "type": "integer",
          "description": "Filter durationMin gte"
        },
        "durationMin.lt": {
          "type": "integer",
          "description": "Filter durationMin lt"
        },
        "durationMin.lte": {
          "type": "integer",
          "description": "Filter durationMin lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/interviews",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "applicationId",
      "scheduledBy",
      "organizationId",
      "durationMin",
      "location",
      "status",
      "privateNotes",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte",
      "durationMin.gt",
      "durationMin.gte",
      "durationMin.lt",
      "durationMin.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listJobPostings",
    "description": "List JobPostings records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "jobId": {
          "type": "string",
          "description": "Filter by jobId (exact match)"
        },
        "slug": {
          "type": "string",
          "description": "Filter by slug (exact match)"
        },
        "headline": {
          "type": "string",
          "description": "Filter by headline (exact match)"
        },
        "summary": {
          "type": "string",
          "description": "Filter by summary (exact match)"
        },
        "location": {
          "type": "string",
          "description": "Filter by location (exact match)"
        },
        "employmentType": {
          "type": "string",
          "description": "Filter by employmentType (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/job-postings",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "jobId",
      "slug",
      "headline",
      "summary",
      "location",
      "employmentType",
      "organizationId",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listJobs",
    "description": "List Jobs records",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid",
          "description": "Filter by id (exact match)"
        },
        "createdAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by createdAt (exact match)"
        },
        "createdBy": {
          "type": "string",
          "description": "Filter by createdBy (exact match)"
        },
        "modifiedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by modifiedAt (exact match)"
        },
        "modifiedBy": {
          "type": "string",
          "description": "Filter by modifiedBy (exact match)"
        },
        "deletedAt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter by deletedAt (exact match)"
        },
        "title": {
          "type": "string",
          "description": "Filter by title (exact match)"
        },
        "department": {
          "type": "string",
          "description": "Filter by department (exact match)"
        },
        "status": {
          "type": "string",
          "description": "Filter by status (exact match)"
        },
        "salaryMin": {
          "type": "integer",
          "description": "Filter by salaryMin (exact match)"
        },
        "salaryMax": {
          "type": "integer",
          "description": "Filter by salaryMax (exact match)"
        },
        "description": {
          "type": "string",
          "description": "Filter by description (exact match)"
        },
        "organizationId": {
          "type": "string",
          "description": "Filter by organizationId (exact match)"
        },
        "createdAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gt"
        },
        "createdAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt gte"
        },
        "createdAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lt"
        },
        "createdAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter createdAt lte"
        },
        "modifiedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gt"
        },
        "modifiedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt gte"
        },
        "modifiedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lt"
        },
        "modifiedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter modifiedAt lte"
        },
        "deletedAt.gt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gt"
        },
        "deletedAt.gte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt gte"
        },
        "deletedAt.lt": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lt"
        },
        "deletedAt.lte": {
          "type": "string",
          "format": "date-time",
          "description": "Filter deletedAt lte"
        },
        "salaryMin.gt": {
          "type": "integer",
          "description": "Filter salaryMin gt"
        },
        "salaryMin.gte": {
          "type": "integer",
          "description": "Filter salaryMin gte"
        },
        "salaryMin.lt": {
          "type": "integer",
          "description": "Filter salaryMin lt"
        },
        "salaryMin.lte": {
          "type": "integer",
          "description": "Filter salaryMin lte"
        },
        "salaryMax.gt": {
          "type": "integer",
          "description": "Filter salaryMax gt"
        },
        "salaryMax.gte": {
          "type": "integer",
          "description": "Filter salaryMax gte"
        },
        "salaryMax.lt": {
          "type": "integer",
          "description": "Filter salaryMax lt"
        },
        "salaryMax.lte": {
          "type": "integer",
          "description": "Filter salaryMax lte"
        }
      },
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/jobs",
    "_pathParams": [],
    "_queryParams": [
      "id",
      "createdAt",
      "createdBy",
      "modifiedAt",
      "modifiedBy",
      "deletedAt",
      "title",
      "department",
      "status",
      "salaryMin",
      "salaryMax",
      "description",
      "organizationId",
      "createdAt.gt",
      "createdAt.gte",
      "createdAt.lt",
      "createdAt.lte",
      "modifiedAt.gt",
      "modifiedAt.gte",
      "modifiedAt.lt",
      "modifiedAt.lte",
      "deletedAt.gt",
      "deletedAt.gte",
      "deletedAt.lt",
      "deletedAt.lte",
      "salaryMin.gt",
      "salaryMin.gte",
      "salaryMin.lt",
      "salaryMin.lte",
      "salaryMax.gt",
      "salaryMax.gte",
      "salaryMax.lt",
      "salaryMax.lte"
    ],
    "_bodyFields": null
  },
  {
    "name": "listOrganizations",
    "description": "List organizations the current user belongs to",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/organization/list",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "listSessions",
    "description": "List all active sessions for the current user",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/list-sessions",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "rejectInvitation",
    "description": "Reject an organization invitation",
    "inputSchema": {
      "type": "object",
      "properties": {
        "invitationId": {
          "type": "string"
        }
      },
      "required": [
        "invitationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/reject-invitation",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "invitationId"
    ]
  },
  {
    "name": "removeMember",
    "description": "Remove a member from the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "memberIdOrEmail": {
          "type": "string"
        }
      },
      "required": [
        "organizationId",
        "memberIdOrEmail"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/remove-member",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId",
      "memberIdOrEmail"
    ]
  },
  {
    "name": "resetPassword",
    "description": "Reset password using a token",
    "inputSchema": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        },
        "newPassword": {
          "type": "string",
          "minLength": 8
        }
      },
      "required": [
        "token",
        "newPassword"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/reset-password",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "token",
      "newPassword"
    ]
  },
  {
    "name": "revokeOtherSessions",
    "description": "Revoke all sessions except the current one",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/revoke-other-sessions",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "revokeSession",
    "description": "Revoke a specific session by token",
    "inputSchema": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      },
      "required": [
        "token"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/revoke-session",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "token"
    ]
  },
  {
    "name": "scoreSummary",
    "description": "Aggregate average rating per interview across the org.",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/interviews/score-summary",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": []
  },
  {
    "name": "sesStatus",
    "description": "Check SES email configuration status",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/auth/v1/ses/status",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "setActiveOrganization",
    "description": "Set the active organization for the current session",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "organizationId"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/set-active",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId"
    ]
  },
  {
    "name": "signInEmail",
    "description": "Sign in with email and password",
    "inputSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/sign-in/email",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "email",
      "password"
    ]
  },
  {
    "name": "signOut",
    "description": "Sign out and invalidate session",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/sign-out",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": null
  },
  {
    "name": "signUpEmail",
    "description": "Sign up with email and password",
    "inputSchema": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email"
        },
        "password": {
          "type": "string",
          "minLength": 8
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password",
        "name"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/sign-up/email",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "email",
      "password",
      "name"
    ]
  },
  {
    "name": "stats",
    "description": "Count applications by status across the org",
    "inputSchema": {
      "type": "object",
      "properties": {},
      "additionalProperties": false
    },
    "_method": "get",
    "_path": "/api/v1/applications/stats",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": []
  },
  {
    "name": "updateApplications",
    "description": "Update a Applications",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "notes": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/applications/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "notes"
    ]
  },
  {
    "name": "updateAtsImports",
    "description": "Update a AtsImports",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "externalId": {
          "type": "string"
        },
        "sourceSystem": {
          "type": "string"
        },
        "payload": {
          "type": "string"
        },
        "error": {
          "type": "string"
        },
        "organizationId": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/ats-imports/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "externalId",
      "sourceSystem",
      "payload",
      "error",
      "organizationId"
    ]
  },
  {
    "name": "updateCandidates",
    "description": "Update a Candidates",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "resumeUrl": {
          "type": "string"
        },
        "source": {
          "type": "string"
        },
        "internalNotes": {
          "type": "string"
        },
        "legalName": {
          "type": "string"
        },
        "governmentId": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/candidates/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "name",
      "email",
      "phone",
      "resumeUrl",
      "source",
      "internalNotes",
      "legalName",
      "governmentId"
    ]
  },
  {
    "name": "updateCustomView",
    "description": "Update a CustomView",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "tableName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "layoutConfig": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/custom-view/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "tableName",
      "name",
      "description",
      "layoutConfig"
    ]
  },
  {
    "name": "updateInterviews",
    "description": "Update a Interviews",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "scheduledAt": {
          "type": "string"
        },
        "durationMin": {
          "type": "integer"
        },
        "location": {
          "type": "string"
        },
        "privateNotes": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/interviews/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "scheduledAt",
      "durationMin",
      "location",
      "privateNotes"
    ]
  },
  {
    "name": "updateJobPostings",
    "description": "Update a JobPostings",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "slug": {
          "type": "string"
        },
        "headline": {
          "type": "string"
        },
        "summary": {
          "type": "string"
        },
        "location": {
          "type": "string"
        },
        "employmentType": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/job-postings/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "slug",
      "headline",
      "summary",
      "location",
      "employmentType"
    ]
  },
  {
    "name": "updateJobs",
    "description": "Update a Jobs",
    "inputSchema": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "title": {
          "type": "string"
        },
        "department": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "salaryMin": {
          "type": "integer"
        },
        "salaryMax": {
          "type": "integer"
        },
        "description": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ],
      "additionalProperties": false
    },
    "_method": "patch",
    "_path": "/api/v1/jobs/{id}",
    "_pathParams": [
      "id"
    ],
    "_queryParams": [],
    "_bodyFields": [
      "title",
      "department",
      "status",
      "salaryMin",
      "salaryMax",
      "description"
    ]
  },
  {
    "name": "updateMemberRole",
    "description": "Update a member role in the organization",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "memberId": {
          "type": "string"
        },
        "role": {
          "type": "string",
          "enum": [
            "owner",
            "admin",
            "member"
          ]
        }
      },
      "required": [
        "organizationId",
        "memberId",
        "role"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/update-member-role",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId",
      "memberId",
      "role"
    ]
  },
  {
    "name": "updateOrganization",
    "description": "Update organization details",
    "inputSchema": {
      "type": "object",
      "properties": {
        "organizationId": {
          "type": "string"
        },
        "data": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "slug": {
              "type": "string"
            },
            "logo": {
              "type": "string",
              "format": "uri"
            }
          }
        }
      },
      "required": [
        "organizationId",
        "data"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/organization/update",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "organizationId",
      "data"
    ]
  },
  {
    "name": "updateUser",
    "description": "Update current user profile",
    "inputSchema": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "image": {
          "type": "string",
          "format": "uri"
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/update-user",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "name",
      "image"
    ]
  },
  {
    "name": "upsertBatch",
    "description": "Idempotent batch upsert from an ATS feed.",
    "inputSchema": {
      "type": "object",
      "properties": {
        "sourceSystem": {
          "type": "string",
          "enum": [
            "greenhouse",
            "lever",
            "workday",
            "other"
          ]
        },
        "externalId": {
          "type": "string"
        },
        "payload": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/api/v1/ats-imports/upsert-batch",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "sourceSystem",
      "externalId",
      "payload"
    ]
  },
  {
    "name": "verifyEmail",
    "description": "Verify email address with token",
    "inputSchema": {
      "type": "object",
      "properties": {
        "token": {
          "type": "string"
        }
      },
      "required": [
        "token"
      ],
      "additionalProperties": false
    },
    "_method": "post",
    "_path": "/auth/v1/verify-email",
    "_pathParams": [],
    "_queryParams": [],
    "_bodyFields": [
      "token"
    ]
  }
];

const PROTOCOL_VERSION = '2025-03-26';
const SERVER_INFO = {
  name: "quickback-example-recruitment",
  title: "quickback-example-recruitment (MCP)",
  version: '1.0.0',
};

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization, Mcp-Session-Id, Mcp-Protocol-Version',
  'Access-Control-Expose-Headers': 'Mcp-Session-Id',
  'Access-Control-Max-Age': '86400',
};

function ok(id: RpcId, result: unknown) {
  return { jsonrpc: '2.0', id: id ?? null, result };
}

function err(id: RpcId, code: number, message: string) {
  return { jsonrpc: '2.0', id: id ?? null, error: { code, message } };
}

function publicToolView(t: ToolEntry) {
  const view: Record<string, unknown> = {
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  };
  if (t.annotations) view.annotations = t.annotations;
  return view;
}

function substitutePathParams(template: string, args: Record<string, unknown>): string {
  return template.replace(/\{([^}]+)\}/g, (_, key: string) => {
    const value = args[key];
    if (value === undefined || value === null) return '';
    return encodeURIComponent(String(value));
  });
}

function buildInternalRequest(
  tool: ToolEntry,
  args: Record<string, unknown>,
  parent: Request,
): Request {
  const origin = new URL(parent.url).origin;
  const interpolated = substitutePathParams(tool._path, args);
  const url = new URL('/api/v1' + interpolated, origin);
  for (const q of tool._queryParams) {
    const v = args[q];
    if (v !== undefined && v !== null) url.searchParams.set(q, String(v));
  }

  const headers = new Headers();
  const auth = parent.headers.get('Authorization');
  if (auth) headers.set('Authorization', auth);
  const cookie = parent.headers.get('Cookie');
  if (cookie) headers.set('Cookie', cookie);

  let body: BodyInit | undefined;
  if (tool._bodyFields && tool._bodyFields.length > 0) {
    if (tool._bodyFields.length === 1 && tool._bodyFields[0] === 'body') {
      body = JSON.stringify(args.body ?? null);
    } else {
      const payload: Record<string, unknown> = {};
      for (const field of tool._bodyFields) {
        if (field in args) payload[field] = args[field];
      }
      body = JSON.stringify(payload);
    }
    headers.set('Content-Type', 'application/json');
  }

  return new Request(url.toString(), {
    method: tool._method.toUpperCase(),
    headers,
    body,
  });
}

async function callTool(
  app: HonoAppType,
  parent: Request,
  name: string,
  args: Record<string, unknown>,
) {
  const tool = TOOLS.find((t) => t.name === name);
  if (!tool) throw new Error(`Unknown tool: ${name}`);

  const internalReq = buildInternalRequest(tool, args, parent);
  const res = await app.request(internalReq);
  const text = await res.text();

  if (!res.ok) {
    return {
      isError: true,
      content: [
        {
          type: 'text',
          text: `HTTP ${res.status} ${res.statusText}\n\n${text}`,
        },
      ],
    };
  }

  return {
    content: [{ type: 'text', text }],
  };
}

async function handleRpc(
  app: HonoAppType,
  parent: Request,
  rpc: RpcMessage,
): Promise<unknown | null> {
  const { id, method, params } = rpc;
  const isNotification = id === undefined || id === null;

  try {
    switch (method) {
      case 'initialize':
        return ok(id, {
          protocolVersion: PROTOCOL_VERSION,
          capabilities: { tools: { listChanged: false } },
          serverInfo: SERVER_INFO,
        });

      case 'notifications/initialized':
      case 'notifications/cancelled':
        return null;

      case 'ping':
        return ok(id, {});

      case 'tools/list':
        return ok(id, { tools: TOOLS.map(publicToolView) });

      case 'tools/call': {
        const toolName = String((params as { name?: unknown })?.name ?? '');
        const args = ((params as { arguments?: Record<string, unknown> })
          ?.arguments ?? {}) as Record<string, unknown>;
        const result = await callTool(app, parent, toolName, args);
        return ok(id, result);
      }

      default:
        if (isNotification) return null;
        return err(id, -32601, `Method not found: ${method}`);
    }
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    if (isNotification) return null;
    return err(id, -32603, message);
  }
}

async function handle(app: HonoAppType, request: Request): Promise<Response> {
  if (request.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }

  if (request.method === 'GET') {
    return Response.json(
      {
        ...SERVER_INFO,
        protocolVersion: PROTOCOL_VERSION,
        transport: 'streamable-http',
        endpoint: new URL(request.url).origin + '/mcp',
        tools: TOOLS.map((t) => t.name),
      },
      { headers: CORS_HEADERS },
    );
  }

  if (request.method !== 'POST') {
    return new Response('Method not allowed', {
      status: 405,
      headers: { ...CORS_HEADERS, Allow: 'GET, POST, OPTIONS' },
    });
  }

  let body: RpcMessage | RpcMessage[];
  try {
    body = (await request.json()) as RpcMessage | RpcMessage[];
  } catch {
    return Response.json(
      { jsonrpc: '2.0', id: null, error: { code: -32700, message: 'Parse error' } },
      { headers: CORS_HEADERS },
    );
  }

  if (Array.isArray(body)) {
    const responses = (
      await Promise.all(body.map((m) => handleRpc(app, request, m)))
    ).filter((r) => r !== null);
    if (responses.length === 0) {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }
    return Response.json(responses, { headers: CORS_HEADERS });
  }

  const response = await handleRpc(app, request, body);
  if (response === null) {
    return new Response(null, { status: 204, headers: CORS_HEADERS });
  }
  return Response.json(response, { headers: CORS_HEADERS });
}

/**
 * Mount the MCP endpoints on the given Hono app.
 */
export function mountMcp(app: HonoAppType) {
  app.get('/.well-known/mcp.json', (c) => {
    const origin = new URL(c.req.url).origin;
    return c.json({
      name: SERVER_INFO.name,
      title: SERVER_INFO.title,
      description:
        'Model Context Protocol server auto-generated from this API\'s OpenAPI spec.',
      version: SERVER_INFO.version,
      protocolVersion: PROTOCOL_VERSION,
      url: origin + '/mcp',
      transport: 'streamable-http',
      capabilities: { tools: true },
    });
  });

  app.all('/mcp', (c) => handle(app, c.req.raw));
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
