/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { ActionExecutor } from "../../../lib/types";
import { atsImports } from "../schema";

export const execute: ActionExecutor = async ({ db, ctx, input, auditFields }) => {
  // SQLite UPSERT against the composite unique
  // (organizationId, sourceSystem, externalId).
  //
  // The batch is processed row-at-a-time rather than in one
  // multi-row INSERT … ON CONFLICT … because Drizzle's set: clause
  // can't reference `excluded.<col>` from the inserted batch
  // through its query builder, and the compiler refuses raw
  // `sql\`excluded.payload\`` without `allowRawSql: true` on the
  // action. Per-row upsert is fine for `records.max(100)`; if you
  // need higher throughput, opt into raw SQL on this action and
  // collapse to a single statement.
  let upserted = 0;
  for (const r of input.records as Array<{ externalId: string; payload: string }>) {
    await db
      .insert(atsImports)
      .values({
        id: crypto.randomUUID(),
        externalId: r.externalId,
        sourceSystem: input.sourceSystem,
        payload: r.payload,
        status: "pending" as const,
      })
      .onConflictDoUpdate({
        target: [atsImports.organizationId, atsImports.sourceSystem, atsImports.externalId],
        set: {
          payload: r.payload,
          status: "pending",
          error: null,
          modifiedAt: auditFields!.modifiedAt,
          modifiedBy: ctx.userId,
        },
      });
    upserted++;
  }

  return { upserted, sourceSystem: input.sourceSystem };
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
