/**
 * Interview scores — Drizzle interop demo.
 *
 * This file is in the `interviews/` feature directory but exports ONLY a
 * `sqliteTable`, not a `defineTable`. That makes it an *internal* child
 * table:
 *
 *  - No CRUD routes are generated (no `:id` GET/POST/PATCH/DELETE)
 *  - No security pillar config (no firewall, masking, guards)
 *  - It still participates in migrations and shows up in the schema
 *  - Audit fields (`createdAt` / `modifiedAt` / `deletedAt` / `*By`) are
 *    auto-injected by the compiler exactly as on `defineTable` features
 *  - `organizationId` is auto-injected because the parent feature
 *    (`interviews`) is org-scoped — so scoped queries from action
 *    handlers (`db` is already org-tenanted) work without ceremony
 *
 * Used by the `complete` action handler: when an interviewer finalizes
 * an interview, the handler INSERTs a row here and then flips the
 * parent's status. Reading happens via a custom standalone action
 * (`scoreSummary`) that aggregates per-interview averages.
 *
 * Why Drizzle interop and not q-DSL: this table doesn't need any
 * security config (it's only ever written from inside trusted action
 * handlers running with the scoped `db`), and writing it as a plain
 * `sqliteTable` keeps it lightweight + opens the door to dialect-only
 * Drizzle features (e.g. SQLite-specific column types) that the q DSL
 * doesn't surface.
 */
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const interviewScores = sqliteTable("interview_scores", {
  id: text("id").primaryKey(),
  // FK to interviews.id — declared as a plain `text` rather than via
  // `.references(...)` because the parent table object is generated by
  // the compiler from the q-DSL and isn't importable at this layer.
  // The column is still indexed below; cascade behavior comes from the
  // soft-delete cascade machinery the compiler synthesises for the
  // parent feature, not a SQL FK.
  interviewId: text("interview_id").notNull(),
  // The user who scored. NOT a `q.scope("owner")` because this is a
  // pure Drizzle interop file (no q DSL); we just write a plain text
  // column and the action handler stamps it from `ctx.userId` on
  // INSERT.
  scorerId: text("scorer_id").notNull(),
  // 1–5 rating. Bounded at the action layer (Zod input schema) — no
  // CHECK constraint because SQLite's `text() with enum` only works on
  // strings; we keep the column as an integer for arithmetic in the
  // aggregate query.
  rating: integer("rating").notNull(),
  recommendation: text("recommendation", {
    enum: ["strong-no", "no", "neutral", "yes", "strong-yes"] as const,
  }).notNull(),
  comments: text("comments", { length: 2000 }),
});
