/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { index, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import { sql } from 'drizzle-orm';

// Generated schema for candidates
// Combined from 1 table definition(s)

// Table: candidates
/**
 * Candidates — the people being considered for jobs.
 *
 * Exercises:
 *  - Column DSL: `.filterable()` / `.searchable()` opt-ins
 *  - `q.scope("organization")` declares a tenant-scope column in one place;
 *    the compiler auto-derives the firewall predicate AND adds it to
 *    systemManaged guards, so the explicit `firewall: [...]` block can drop
 *    its organization clause (soft-delete still ridges in via auto-detection
 *    on `deletedAt`)
 *  - PII masking with a single `query.roles` role gate that covers ?filter,
 *    ?sort, and ?search uniformly. Non-admins see masked payloads AND can't
 *    enumerate via query strings. The `full` view re-opens all three for
 *    admins via its own `query.{cap}` allowlist — the validator enforces
 *    `view.access.roles ∩ masking.query.roles ≠ ∅` before permitting the
 *    opt-in (with `show.roles` as the fallback when `query` is omitted).
 *  - Unified read pipeline with named views and per-view query allowlists
 *  - `feature()` single-export sugar
 */
export const candidates = sqliteTable("candidates", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  resumeUrl: text("resume_url"),
  source: text("source", { enum: ["linkedin", "referral", "careers-page", "other"] as const }).default("other").notNull(),
  internalNotes: text("internal_notes"),
  legalName: text("legal_name"),
  governmentId: text("government_id"),
  organizationId: text("organization_id").notNull(),

    createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    modifiedAt: text("modified_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text("deleted_at"),
    createdBy: text("created_by"),
    modifiedBy: text("modified_by"),
    deletedBy: text("deleted_by"),
  }, (t) => ({
  candidates_organizationId_email_unique: uniqueIndex("candidates_organizationId_email_unique").on(t.organizationId, t.email),
  candidates_organization_id_deleted_at_idx: index("candidates_organization_id_deleted_at_idx").on(t.organizationId, t.deletedAt),
  candidates_created_at_idx: index("candidates_created_at_idx").on(t.createdAt),
  candidates_name_idx: index("candidates_name_idx").on(t.name),
  candidates_email_idx: index("candidates_email_idx").on(t.email)
}));

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
