/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Generated actions for applications
import { z } from 'zod';
import type { AppContext } from '../../lib/types';
import type { Services } from '../../lib/services';

// Handler imports
import { execute as advanceExecute } from './handlers/advance';
import { execute as hireExecute } from './handlers/hire';
import { execute as rejectExecute } from './handlers/reject';
import { execute as withdrawExecute } from './handlers/withdraw';
import { execute as statsExecute } from './handlers/stats';

export const actions = {
  "advance": {
    description: "Move an application forward in the pipeline.",
    input: z.object({
      nextStatus: z.enum(["screening", "interview", "offer"]),
      notes: z.string().max(2000).optional(),
    }),
    access: {
          "roles": [
                "owner",
                "admin"
          ]
    },
    transition: {
          "field": "status",
          "via": "nextStatus",
          "fromTo": {
                "applied": [
                      "screening"
                ],
                "screening": [
                      "interview"
                ],
                "interview": [
                      "offer"
                ]
          }
    },
    execute: advanceExecute,
  },
  "hire": {
    description: "Finalize an offer — the candidate accepted.",
    input: z.object({}),
    access: {
          "roles": [
                "owner"
          ]
    },
    transition: {
          "field": "status",
          "to": "hired",
          "fromTo": {
                "offer": [
                      "hired"
                ]
          }
    },
    execute: hireExecute,
  },
  "reject": {
    description: "Reject an application with an optional reason.",
    input: z.object({
      // Bounded — reject's handler appends to existing notes, so unbounded
      // reason text compounds across rejections.
      reason: z.string().max(500).optional(),
    }),
    access: {
          "roles": [
                "owner",
                "admin"
          ]
    },
    transition: {
          "field": "status",
          "to": "rejected",
          "fromTo": {
                "applied": [
                      "rejected"
                ],
                "screening": [
                      "rejected"
                ],
                "interview": [
                      "rejected"
                ],
                "offer": [
                      "rejected"
                ]
          }
    },
    execute: rejectExecute,
  },
  "withdraw": {
    description: "Candidate withdrew their application.",
    input: z.object({}),
    access: {
          "roles": [
                "owner",
                "admin"
          ]
    },
    transition: {
          "field": "status",
          "to": "withdrawn",
          "fromTo": {
                "applied": [
                      "withdrawn"
                ],
                "screening": [
                      "withdrawn"
                ],
                "interview": [
                      "withdrawn"
                ],
                "offer": [
                      "withdrawn"
                ]
          }
    },
    execute: withdrawExecute,
  },
  "stats": {
    description: "Count applications by status across the org",
    input: z.object({}),
    access: {
          "roles": [
                "owner",
                "admin",
                "member"
          ]
    },
    execute: statsExecute,
  }
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
