/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { index, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { sql } from 'drizzle-orm';
import { jobs } from "../jobs/schema";
import { candidates } from "../candidates/schema";

// Generated schema for applications
// Combined from 1 table definition(s)

// Table: applications
/**
 * Applications — the association between a candidate and a job.
 *
 * Exercises:
 *  - Foreign keys: `jobId → jobs.id`, `candidateId → candidates.id`
 *  - Status column that's *protected* — only specific actions can mutate it
 *  - `references` mapping so the CMS resolves FK labels in list/get
 *  - Multi-scope WHERE: firewall.organization + softDelete
 *
 * Status lifecycle — `applied → screening → interview → offer → hired`, or
 * any state → `rejected` / `withdrawn`. Transitions are enforced by the
 * actions in `actions.ts`; clients can't set `status` directly via PATCH.
 */

export const applications = sqliteTable("applications", {
  id: text("id").primaryKey(),
  jobId: text("jobId").notNull().references(() => jobs.id, { onDelete: "cascade" }),
  candidateId: text("candidateId").notNull().references(() => candidates.id, { onDelete: "cascade" }),
  status: text("status", { enum: ["applied", "screening", "interview", "offer", "hired", "rejected", "withdrawn"] as const }).default("applied").notNull(),
  appliedAt: text("appliedAt"),
  notes: text("notes"),
  organizationId: text("organizationId").notNull(),

    createdAt: text("createdAt").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    modifiedAt: text("modifiedAt").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text("deletedAt"),
    createdBy: text("createdBy"),
    modifiedBy: text("modifiedBy"),
    deletedBy: text("deletedBy"),
  }, (t) => ({
  applications_status_idx: index("applications_status_idx").on(t.status),
}));

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
