/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Webhook Provider Interface
 *
 * Defines the contract for inbound webhook providers (Stripe, Paddle, GitHub, etc.)
 * Each provider handles signature verification and event parsing for its platform.
 */

export interface ParsedWebhookEvent {
  /** Event type (e.g., 'checkout.session.completed', 'invoice.paid') */
  type: string;
  /** Parsed event data */
  data: unknown;
  /** Provider's event ID (for idempotency) */
  externalId?: string;
}

export interface InboundProvider {
  /** Provider name (e.g., 'stripe', 'paddle', 'github') */
  name: string;

  /**
   * Verify the webhook signature
   * @param payload - Raw request body as string
   * @param signature - Signature header value
   * @param secret - Webhook secret for this provider
   * @returns true if signature is valid
   */
  verifySignature(payload: string, signature: string, secret: string): Promise<boolean>;

  /**
   * Parse the webhook payload into a structured event
   * @param payload - Raw request body as string
   * @returns Parsed event with type and data
   */
  parseEvent(payload: string): ParsedWebhookEvent;
}

// Provider registry
const providers = new Map<string, InboundProvider>();

/**
 * Register a webhook provider
 */
export function registerProvider(provider: InboundProvider): void {
  providers.set(provider.name, provider);
}

/**
 * Get a registered provider by name
 */
export function getProvider(name: string): InboundProvider | undefined {
  return providers.get(name);
}

/**
 * Get all registered provider names
 */
export function getProviderNames(): string[] {
  return Array.from(providers.keys());
}

// Re-export provider implementations
export { stripeProvider } from "./stripe";

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
