/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Stripe Webhook Provider
 *
 * Handles Stripe webhook signature verification and event parsing.
 * Uses Stripe's webhook signing algorithm (HMAC-SHA256 with timestamp).
 */

import type { InboundProvider, ParsedWebhookEvent } from "./index";

/**
 * Compute HMAC-SHA256 signature using Web Crypto API
 */
async function computeHmacSha256(secret: string, payload: string): Promise<string> {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );

  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    encoder.encode(payload)
  );

  return Array.from(new Uint8Array(signature))
    .map(b => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Parse Stripe signature header
 * Format: t=timestamp,v1=signature
 */
function parseSignatureHeader(header: string): { timestamp: number; signatures: string[] } {
  const parts = header.split(",");
  let timestamp = 0;
  const signatures: string[] = [];

  for (const part of parts) {
    const [key, value] = part.split("=");
    if (key === "t") {
      timestamp = parseInt(value, 10);
    } else if (key === "v1") {
      signatures.push(value);
    }
  }

  return { timestamp, signatures };
}

/**
 * Constant-time string comparison to prevent timing attacks
 */
function secureCompare(a: string, b: string): boolean {
  if (a.length !== b.length) return false;

  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}

export const stripeProvider: InboundProvider = {
  name: "stripe",

  async verifySignature(payload: string, signature: string, secret: string): Promise<boolean> {
    try {
      const { timestamp, signatures } = parseSignatureHeader(signature);

      // Check if timestamp is within tolerance (5 minutes)
      const tolerance = 300; // 5 minutes in seconds
      const now = Math.floor(Date.now() / 1000);
      if (Math.abs(now - timestamp) > tolerance) {
        console.warn(`Stripe webhook timestamp outside tolerance: ${timestamp} vs ${now}`);
        return false;
      }

      // Compute expected signature
      const signedPayload = `${timestamp}.${payload}`;
      const expectedSignature = await computeHmacSha256(secret, signedPayload);

      // Check if any provided signature matches
      for (const sig of signatures) {
        if (secureCompare(sig, expectedSignature)) {
          return true;
        }
      }

      return false;
    } catch (error) {
      console.error("Stripe signature verification failed:", error);
      return false;
    }
  },

  parseEvent(payload: string): ParsedWebhookEvent {
    const event = JSON.parse(payload);

    return {
      type: event.type,
      data: event.data?.object || event.data,
      externalId: event.id,
    };
  },
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
