--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
CREATE TABLE `webhook_deliveries` (
	`id` text PRIMARY KEY NOT NULL,
	`endpoint_id` text NOT NULL,
	`event_type` text NOT NULL,
	`payload` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`attempts` integer DEFAULT 0,
	`last_attempt_at` integer,
	`next_retry_at` integer,
	`response_status` integer,
	`response_body` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);

CREATE INDEX `webhook_deliveries_endpoint_idx` ON `webhook_deliveries` (`endpoint_id`);
CREATE INDEX `webhook_deliveries_status_idx` ON `webhook_deliveries` (`status`);
CREATE INDEX `webhook_deliveries_next_retry_idx` ON `webhook_deliveries` (`next_retry_at`);
CREATE TABLE `webhook_endpoints` (
	`id` text PRIMARY KEY NOT NULL,
	`organization_id` text,
	`user_id` text,
	`name` text,
	`url` text NOT NULL,
	`secret` text NOT NULL,
	`events` text NOT NULL,
	`enabled` integer DEFAULT true,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer
);

CREATE INDEX `webhook_endpoints_org_idx` ON `webhook_endpoints` (`organization_id`);
CREATE INDEX `webhook_endpoints_user_idx` ON `webhook_endpoints` (`user_id`);
CREATE INDEX `webhook_endpoints_enabled_idx` ON `webhook_endpoints` (`enabled`);
CREATE TABLE `webhook_events` (
	`id` text PRIMARY KEY NOT NULL,
	`provider` text NOT NULL,
	`event_type` text NOT NULL,
	`external_id` text,
	`payload` text NOT NULL,
	`status` text DEFAULT 'received' NOT NULL,
	`attempts` integer DEFAULT 0,
	`processed_at` integer,
	`error` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL
);

CREATE INDEX `webhook_events_provider_idx` ON `webhook_events` (`provider`);
CREATE INDEX `webhook_events_status_idx` ON `webhook_events` (`status`);
CREATE INDEX `webhook_events_external_id_idx` ON `webhook_events` (`external_id`);

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
