/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { Hono } from 'hono';
import { eq, and, or, gt, gte, lt, lte, ne, like, inArray, asc, desc, count, sql, type SQL } from 'drizzle-orm';
import { atsImports } from './schema';
import type { AppContext } from '../../lib/types';
import type { CloudflareBindings } from '../../env';
import { 
  buildFirewallConditions,
  CRUD_ACCESS
} from './ats-imports.resource';
import { actions } from './actions';
import { createScopedDb, buildScopeConditions } from '../../lib/scoped-db';
import { jsonWithEtag } from '../../lib/etag';
import { evaluateAccess, evaluateAccessPreRecord, evaluateAccessReason } from '../../lib/access';
import { AuthErrors, FirewallErrors, AccessErrors, GuardErrors, BatchErrors } from '../../lib/errors';
import { z } from 'zod';
import { parseJsonWithSchema } from '../../lib/request-validation';

// Helper function to parse filter values from query strings
function parseFilterValue(value: string): string | number | boolean {
  // Boolean
  if (value === 'true') return true;
  if (value === 'false') return false;

  // Number
  const num = Number(value);
  if (!isNaN(num) && value !== '') return num;

  // Date (ISO format) - return as string for SQL comparison
  if (/^\d{4}-\d{2}-\d{2}/.test(value)) return value;

  // Default to string
  return value;
}

// Escape SQL LIKE wildcards in user input. Without this, '%' or '_' in a
// search query would change pattern semantics and let callers probe across
// columns more aggressively than the API contract allows.
function escapeLike(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/%/g, '\\%').replace(/_/g, '\\_');
}

// Request body schemas — derived from the q DSL column Zods.
const CreateBodySchema = z.object({
  externalId: z.string().max(200),
  sourceSystem: z.enum(["greenhouse", "lever", "workday", "other"] as const),
  payload: z.string().max(16000),
  status: z.enum(["pending", "processed", "failed"] as const).optional(),
  error: z.string().max(4000).optional(),
}).strict();
const UpdateBodySchema = z.object({
  externalId: z.string().max(200).optional(),
  sourceSystem: z.enum(["greenhouse", "lever", "workday", "other"] as const).optional(),
  payload: z.string().max(16000).optional(),
  status: z.enum(["pending", "processed", "failed"] as const).optional(),
  error: z.string().max(4000).optional(),
}).strict();
const BatchUpdateRecordSchema = z.object({
  externalId: z.string().max(200).optional(),
  sourceSystem: z.enum(["greenhouse", "lever", "workday", "other"] as const).optional(),
  payload: z.string().max(16000).optional(),
  status: z.enum(["pending", "processed", "failed"] as const).optional(),
  error: z.string().max(4000).optional(),
}).extend({ id: z.string() }).strict();
const BatchOptionsSchema = z.object({ failFast: z.boolean() }).strict().optional();
const BatchCreateBodySchema = z.object({ records: z.array(CreateBodySchema), options: BatchOptionsSchema }).strict();
const BatchUpdateBodySchema = z.object({ records: z.array(BatchUpdateRecordSchema), options: BatchOptionsSchema }).strict();
const BatchDeleteBodySchema = z.object({ ids: z.array(z.string()), options: BatchOptionsSchema }).strict();

const app = new Hono<{ Bindings: CloudflareBindings; Variables: { ctx: AppContext; db: any; services: any; authDb: any; requestId: string } }>();

// ═══════════════════════════════════════════════════════

// STANDALONE ACTIONS

// ═══════════════════════════════════════════════════════

// Idempotent batch upsert from an ATS feed.
// UPSERTBATCH: POST /ats-imports/upsert-batch
app.post('/ats-imports/upsert-batch', async (c) => {
  const ctx = c.get('ctx');
  const unsafeDb = c.get('db');
  const services = c.get('services');

  // Authentication check
  if (!ctx.authenticated) {
    return c.json(AuthErrors.missing(), 401);
  }
  // Organization check
  if (!ctx.activeOrgId) {
    
    return c.json(AccessErrors.noOrg(), 403);
  }
  // Role check
  if (!ctx.roles?.some(r => ["admin","owner"].includes(r))) {
    
    return c.json(AccessErrors.roleRequired(["admin","owner"], ctx.roles), 403);
  }
  // Scoped DB — auto-enforces org isolation, owner filtering, and soft delete
  const db = createScopedDb(unsafeDb, ctx);


  // Input validation — route through parseJsonWithSchema so malformed
  // JSON returns INVALID_JSON 400 (rather than silently coercing to {})
  // and the body size cap fires before we hand the bytes to JSON.parse.
  const parseResult = await parseJsonWithSchema(c.req.raw, actions["upsertBatch"].input);
  if (!parseResult.ok) {
    const status = parseResult.code === 'PAYLOAD_TOO_LARGE' ? 413 : 400;
    return c.json({
      error: parseResult.error,
      code: parseResult.code,
      layer: 'validation',
      ...(parseResult.fields ? { fields: parseResult.fields } : {}),
    }, status);
  }
  // Zod's inferred type for the validated input is structurally compatible with
  // the handler's declared TInput at runtime, but TS won't accept e.g. {} where
  // a handler annotates ActionExecutor<Record<string, never>>. The validation
  // is already enforced above; widen here so the call line typechecks regardless
  // of how strictly the handler typed its input.
  const input: any = parseResult.data;

  // Prepare audit fields for action handlers that create/update records
  // Note: createdBy/modifiedBy are auto-injected by the audit DB wrapper
  const now = new Date().toISOString();
  const auditFields = { createdAt: now, modifiedAt: now };

  // Execute action
  try {
    const result = await actions["upsertBatch"].execute({ db, unsafeDb: undefined, env: c.env, ctx, record: undefined, input, services, c, auditFields });
    
    return c.json(result);
  } catch (error: any) {
    
    if (error?.name === 'ActionError') {
      return c.json({
        error: error.message,
        code: error.code,
        ...(error.details ? { details: error.details } : {}),
      }, error.statusCode || 400);
    }
    throw error;
  }
});

// ═══════════════════════════════════════════════════════
// READ: GET /atsImports
// Unified handler dispatched by ?view=<name>. Supports:
//   ?limit=10&offset=0
//   ?sort=createdAt,-name
//   ?total=true
//   ?fields=id,name,email           (when no view selected)
//   ?search=text
//   ?<field>=value | ?<field>.<op>=value
//   ?organizationId=<orgId>         (member-of-org check; effective scope)
// ═══════════════════════════════════════════════════════
const READ_ACCESS: any = {
  "roles": [
    "admin",
    "owner"
  ]
};
const VIEWS = {
  "__default": {}
} as const;
const DEFAULT_VIEW = "__default";
const DEFAULT_SEARCHABLE: string[] = ["sourceSystem","payload","status","error"];
// Closed allowlist of *declared* column names. Used for ?sort=, ?fields=,
// and ?<col>= filter validation in place of `field in <table>`, which
// admitted Drizzle's internal keys (`_`, `getSQL`, etc.). Unknown fields
// no-op cleanly without ever touching the runtime table object.
const KNOWN_COLUMNS: ReadonlySet<string> = new Set(["id","externalId","sourceSystem","payload","status","error","organizationId"]);
// Per-column filter parsers — generated from the q DSL column kinds so a
// "123" passed for a TEXT column stays a string instead of being coerced to
// a number by the generic parseFilterValue.
const FILTER_PARSERS: Record<string, (v: string) => unknown> = {
  "id": (v: string) => v,
  "externalId": (v: string) => v,
  "sourceSystem": (v: string) => v,
  "payload": (v: string) => v,
  "status": (v: string) => v,
  "error": (v: string) => v,
  "organizationId": (v: string) => v
};

app.get('/', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Parse query parameters
  const url = new URL(c.req.url);
  const params = Object.fromEntries(url.searchParams.entries());

  // Resolve the view. Empty/missing param falls back to the configured
  // default; if no default is configured (named views without
  // `read.defaultView`), bare `GET /` returns VIEW_REQUIRED.
  const viewName = (params.view || DEFAULT_VIEW) as keyof typeof VIEWS;
  const view = VIEWS[viewName];
  if (!view) {
    return c.json({ error: 'Unknown view', code: 'VIEW_NOT_FOUND', view: params.view }, 400);
  }

  // Active-org scope (cross-org reads gated to platform admins).
  // See helpers/cross-tenant.ts for the full rationale.
  const requestedOrgId = params.organizationId || ctx.activeOrgId;
  if (!requestedOrgId) {
    return c.json({
      error: 'Organization required',
      code: 'ORG_REQUIRED',
      hint: 'Pass organizationId query param or set active organization in session'
    }, 400);
  }
  let effectiveCtx = ctx;
  // Only fire the cross-tenant guard when the caller HAS an active org
  // and is asking to leave it. Unauthenticated PUBLIC callers and
  // signed-in users with no active org just specify the tenant via
  // ?organizationId=; that's not a "switch", it's the only addressing
  // they have. The firewall WHERE clause uses requestedOrgId, so the
  // scope is still enforced.
  if (params.organizationId && ctx.activeOrgId && params.organizationId !== ctx.activeOrgId) {
    if (ctx.userRole !== 'admin') {
      return c.json(AccessErrors.crossTenantForbidden(), 403);
    }
    effectiveCtx = { ...ctx, activeOrgId: requestedOrgId, roles: [] };
  } else if (params.organizationId && !ctx.activeOrgId) {
    effectiveCtx = { ...ctx, activeOrgId: requestedOrgId };
  }

  // Access gate. View-level access wins over read-level access.
  const accessConfig: any = (view as any).access ?? READ_ACCESS ?? null;
  if (accessConfig) {
    if (!await evaluateAccess(accessConfig, effectiveCtx)) {
      return c.json(AccessErrors.roleRequired((accessConfig as any).roles || [], effectiveCtx.roles, (accessConfig as any).userRole, effectiveCtx.userRole), 403);
    }
  }

  // Pagination
  const limit = Math.min(Math.max(parseInt(params.limit) || 50, 1), 100);
  const offset = Math.max(parseInt(params.offset) || 0, 0);

  // Sort allowlist (per-view), with table-wide fallback when the view doesn't declare one.
  const sortAllowlist: ReadonlySet<string> | null = (view as any).query?.sortable
    ? new Set<string>((view as any).query.sortable)
    : null;
  const sortOrders: { column: any; direction: typeof asc }[] = [];
  const sortParam = params.sort || (view as any).query?.defaultSort || 'createdAt';
  const isMultiSort = sortParam.includes(',') || sortParam.startsWith('-');
  const acceptSort = (fieldName: string) =>
    KNOWN_COLUMNS.has(fieldName) && (sortAllowlist === null || sortAllowlist.has(fieldName));
  if (isMultiSort) {
    for (const part of sortParam.split(',')) {
      const trimmed = part.trim();
      if (!trimmed) continue;
      const isDesc = trimmed.startsWith('-');
      const fieldName = isDesc ? trimmed.slice(1) : trimmed;
      if (!acceptSort(fieldName)) continue;
      const col = atsImports[fieldName as keyof typeof atsImports] as any;
      if (typeof col === 'object' && col) {
        sortOrders.push({ column: col, direction: isDesc ? desc : asc });
      }
    }
  } else {
    const sortOrder = params.order === 'asc' ? asc : desc;
    if (acceptSort(sortParam)) {
      const col = atsImports[sortParam as keyof typeof atsImports] as any;
      if (typeof col === 'object' && col) {
        sortOrders.push({ column: col, direction: sortOrder });
      }
    }
  }

  // Field selection. View.fields takes precedence; ?fields= is honored only
  // when the default view is in play (no per-view projection).
  let selectFields: Record<string, any> | undefined;
  const viewFields = (view as any).fields as string[] | undefined;
  if (viewFields && viewFields.length > 0) {
    const projected: Record<string, any> = {};
    for (const f of viewFields) {
      if (KNOWN_COLUMNS.has(f)) projected[f] = atsImports[f as keyof typeof atsImports];
    }
    if (Object.keys(projected).length > 0) selectFields = projected;
  } else if (params.fields) {
    const requested: Record<string, any> = {};
    for (const f of params.fields.split(',')) {
      const fieldName = f.trim();
      if (fieldName && KNOWN_COLUMNS.has(fieldName)) {
        requested[fieldName] = atsImports[fieldName as keyof typeof atsImports];
      }
    }
    if (Object.keys(requested).length > 0) selectFields = requested;
  }

  // Filter conditions. Firewall always applies first.
  const filterConditions: SQL[] = [];
  const firewallCond = buildFirewallConditions(effectiveCtx);
  if (firewallCond) filterConditions.push(firewallCond);

  // Per-view filterable allowlist; null means "no allowlist declared, accept any column".
  const filterAllowlist: ReadonlySet<string> | null = (view as any).query?.filterable
    ? new Set<string>((view as any).query.filterable)
    : null;
  const reservedParams = new Set(['limit', 'offset', 'sort', 'order', 'organizationId', 'fields', 'search', 'view', 'total']);
  for (const [key, value] of Object.entries(params)) {
    if (reservedParams.has(key)) continue;

    const [field, op] = key.split('.');
    if (!KNOWN_COLUMNS.has(field)) continue;
    if (filterAllowlist !== null && !filterAllowlist.has(field)) continue;

    const column = atsImports[field as keyof typeof atsImports] as any;
    if (typeof column !== 'object' || !column) continue;

    const parseField = FILTER_PARSERS[field] ?? parseFilterValue;

    switch (op) {
      case 'gt':
        filterConditions.push(gt(column, parseField(value)));
        break;
      case 'gte':
        filterConditions.push(gte(column, parseField(value)));
        break;
      case 'lt':
        filterConditions.push(lt(column, parseField(value)));
        break;
      case 'lte':
        filterConditions.push(lte(column, parseField(value)));
        break;
      case 'ne':
        filterConditions.push(ne(column, parseField(value)));
        break;
      case 'like':
        // ESCAPE '\' is required — SQLite has no default escape character,
        // and Postgres in standard_conforming_strings mode also requires the
        // explicit clause. Without it, escapeLike()'s '\%' / '\_' output is
        // re-interpreted as wildcard, defeating the escape entirely.
        filterConditions.push(sql`${column} LIKE ${`%${escapeLike(value)}%`} ESCAPE '\\'`);
        break;
      case 'in':
        filterConditions.push(inArray(column, value.split(',').map((v) => parseField(v))));
        break;
      case undefined:
        filterConditions.push(eq(column, parseField(value)));
        break;
    }
  }

  // Search: ?search=text, OR'd LIKE across the per-view searchable allowlist.
  // Each branch carries an ESCAPE '\' clause — see the like-case above for
  // why it matters.
  const searchableColumns: string[] = (view as any).query?.searchable ?? DEFAULT_SEARCHABLE;
  if (params.search && searchableColumns.length > 0) {
    const searchTerm = `%${escapeLike(params.search)}%`;
    const searchConditions = searchableColumns
      .filter((col: string) => KNOWN_COLUMNS.has(col))
      .map((col: string) => sql`${atsImports[col as keyof typeof atsImports] as any} LIKE ${searchTerm} ESCAPE '\\'`);
    if (searchConditions.length > 0) {
      filterConditions.push(or(...searchConditions)!);
    }
  }

  // Build & execute query.
  let query = selectFields ? db.select(selectFields).from(atsImports) : db.select().from(atsImports);
  if (filterConditions.length > 0) {
    query = query.where(and(...filterConditions));
  }
  if (sortOrders.length > 0) {
    query = query.orderBy(...sortOrders.map(s => s.direction(s.column)));
  }

  // Total count is opt-in via ?total=true to keep hot reads cheap.
  let total: number | null = null;
  if (params.total === 'true') {
    let countQuery = db.select({ value: count() }).from(atsImports);
    if (filterConditions.length > 0) {
      countQuery = countQuery.where(and(...filterConditions));
    }
    const [countResult] = await countQuery;
    total = countResult?.value ?? 0;
  }

  // Over-fetch by one row to determine hasMore reliably. A flat
  // results.length === limit check would lie on a final page that
  // exactly fills the limit; the +1 probe distinguishes "more rows
  // exist" from "this page happens to be full".
  query = query.limit(limit + 1).offset(offset);
  const _rawResults = await query;
  const _hasMoreFromProbe = _rawResults.length > limit;
  const results = _hasMoreFromProbe ? _rawResults.slice(0, limit) : _rawResults;

  // Pagination metadata. When ?total=true was passed we report counted totals;
  // otherwise we report a hasMore signal computed from the over-fetch probe.
  const pagination = total !== null
    ? {
        total,
        count: results.length,
        page: Math.floor(offset / limit) + 1,
        pageSize: limit,
        totalPages: Math.ceil(total / limit),
        hasMore: (Math.floor(offset / limit) + 1) < Math.ceil(total / limit),
      }
    : {
        count: results.length,
        page: Math.floor(offset / limit) + 1,
        pageSize: limit,
        hasMore: _hasMoreFromProbe,
      };

  return jsonWithEtag(c, {
    data: results,
    view: (viewName as string) === '__default' ? null : viewName,
    pagination,
  });
});

// ═══════════════════════════════════════════════════════
// BATCH CREATE: POST /atsImports/batch
// ═══════════════════════════════════════════════════════
app.post('/batch', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');

  // Universal auth gate. Even if the access check below is missing or
  // buggy, unauthenticated callers cannot reach the batch insert. PUBLIC
  // opt-in would be expressed via an explicit access config.
  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Pre-query access check
  const batchCreateAccess = {"roles":["admin","owner"]};
  if (!await evaluateAccessPreRecord(batchCreateAccess, ctx)) {
    return c.json(AccessErrors.roleRequired((batchCreateAccess as any).roles || [], ctx.roles), 403);
  }

  if (!ctx.activeOrgId) {
    return c.json({
      error: 'Organization required',
      code: 'ORG_REQUIRED',
      hint: 'Set active organization in session before creating records'
    }, 400);
  }
const parseResult = await parseJsonWithSchema(c.req.raw, BatchCreateBodySchema);
  if (!parseResult.ok) {
    return c.json({ error: parseResult.error, code: parseResult.code, layer: 'validation', fields: parseResult.fields }, 400);
  }
  const body = parseResult.data as any;
  const records = body.records || [];
  const options = body.options || {};
  const failFast = options.failFast === true;

  // Validate batch size
  if (records.length > 100) {
    return c.json(BatchErrors.sizeExceeded(100, records.length), 400);
  }

  // Empty batch - return empty success
  if (records.length === 0) {
    return c.json({
      success: [],
      errors: [],
      meta: { total: 0, succeeded: 0, failed: 0, failFast: false }
    }, 200);
  }

  const now = new Date().toISOString();
  // Track the original input index alongside each post-guards record so that
  // a downstream insert failure can attribute its errors to the right input
  // index — the bulk insert path doesn't know which post-validation slot
  // corresponds to which caller-supplied record otherwise.
  const validRecords: { originalIndex: number; data: any }[] = [];
  const errors: any[] = [];

  // Process each record
  for (let i = 0; i < records.length; i++) {
    const record = records[i];




    // Apply defaults, ownership, computed fields, and audit fields
    const data = {
      id: 'ats_' + crypto.randomUUID().replace(/-/g, ''),
      ...record,
      ...{},
    organizationId: ctx.activeOrgId,
    createdAt: now,
    modifiedAt: now,
    };

    validRecords.push({ originalIndex: i, data });
  }

  // Fail-fast mode: if any guards rejected a record, stop here. NOTE: this
  // is fail-fast, not transactional rollback — earlier records that pass
  // guards are still inserted by the bulk write below if we proceed.
  if (failFast && errors.length > 0) {
    return c.json(BatchErrors.failFastStopped(errors[0].index, errors[0].error), 400);
  }

  let success: any[] = [];

  // Execute bulk insert if we have valid records
  if (validRecords.length > 0) {
    try {
      success = await db.insert(atsImports).values(validRecords.map((v) => v.data)).returning();
    } catch (error: any) {
      // Search full error chain (D1/Drizzle may nest the real error in cause)
      const errMsg = [error?.message, error?.cause?.message, String(error)].filter(Boolean).join(' ');
      const isNotNull = errMsg.includes('NOT NULL constraint failed');
      const isUnique = errMsg.includes('UNIQUE constraint failed');
      const code = isNotNull ? 'NOT_NULL_VIOLATION' : isUnique ? 'UNIQUE_VIOLATION' : 'INSERT_FAILED';
      const label = isNotNull ? 'Missing required field' : isUnique ? 'Duplicate value' : 'Database insert failed';

      if (failFast) {
        return c.json({
          error: label,
          layer: 'database',
          code: 'BATCH_' + code,
        }, 400);
      }
      for (const v of validRecords) {
        errors.push({
          index: v.originalIndex,
          record: records[v.originalIndex],
          error: { error: label, layer: 'database', code }
        });
      }
    }
  }

  // Apply masking to success array
  const maskedSuccess = success;

  // Bulk INSERT is a single SQL statement, atomic at the DB level — either
  // every record is inserted or none is. No tx wrapper needed.
  const meta = {
    total: records.length,
    succeeded: success.length,
    failed: errors.length,
    failFast,
    transactional: true
  };

  const statusCode = errors.length > 0 ? 207 : 201;
  return c.json({ success: maskedSuccess, errors, meta }, statusCode);
});

// ═══════════════════════════════════════════════════════
// BATCH UPDATE: PATCH /atsImports/batch
// ═══════════════════════════════════════════════════════
app.patch('/batch', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Pre-query access check (role gate only)
  const batchUpdateAccess = {"roles":["admin","owner"]};
  if (!await evaluateAccessPreRecord(batchUpdateAccess, ctx)) {
    return c.json(AccessErrors.roleRequired((batchUpdateAccess as any).roles || [], ctx.roles, (batchUpdateAccess as any).userRole, ctx.userRole), 403);
  }

  const parseResult = await parseJsonWithSchema(c.req.raw, BatchUpdateBodySchema);
  if (!parseResult.ok) {
    return c.json({ error: parseResult.error, code: parseResult.code, layer: 'validation', fields: parseResult.fields }, 400);
  }
  const body = parseResult.data as any;
  const records = body.records || [];
  const options = body.options || {};
  const failFast = options.failFast === true;

  // Validate batch size
  if (records.length > 100) {
    return c.json(BatchErrors.sizeExceeded(100, records.length), 400);
  }

  // Empty batch - return empty success
  if (records.length === 0) {
    return c.json({
      success: [],
      errors: [],
      meta: { total: 0, succeeded: 0, failed: 0, failFast: false }
    }, 200);
  }

  // Validate all records have IDs
  const missingIds: number[] = [];
  for (let i = 0; i < records.length; i++) {
    if (!records[i].id) {
      missingIds.push(i);
    }
  }
  if (missingIds.length > 0) {
    return c.json(BatchErrors.missingIds(missingIds), 400);
  }

  // Extract IDs for batch fetch
  const ids = records.map((r: any) => r.id);

  // Batch fetch existing records with firewall
  const existingRecords = await db.select().from(atsImports)
    .where(and(buildFirewallConditions(ctx), inArray(atsImports.id, ids)));

  // Create lookup map for O(1) access
  const recordMap = new Map<string, any>();
  for (const record of existingRecords) {
    recordMap.set(record.id, record);
  }

  const now = new Date().toISOString();
  const errors: any[] = [];
  const success: any[] = [];
  const ownershipFields = ["organizationId"];
  let failFastIndex = -1;
  let failFastError: any = null;

  // Per-record loop, accepts a db OR tx handle so the tx-wrapping branch
  // below can replay the same body inside a transaction. Throws on the
  // first DB error when failFast=true so the tx aborts and rolls back.
  const processBatch = async (handle: any) => {
    for (let i = 0; i < records.length; i++) {
      const record = records[i];
      // Split id off the patch payload up front. `record` keeps the full
      // shape for error reporting and the firewall write clause; `patch`
      // is what reaches validateUpdate and the SET clause — id is the
      // WHERE-clause identifier, not a writable column, so it has no
      // business in either.
      const { id: _id, ...patch } = record;
      const existingRecord = recordMap.get(record.id);

      // Check if record exists
      if (!existingRecord) {
        errors.push({
          index: i,
          record,
          error: { ...FirewallErrors.notFound(), details: { id: record.id } }
        });
        continue;
      }

        // Default: Authenticated access required
      if (!ctx.authenticated) {
        errors.push({
          index: i,
          record,
          error: { error: 'Unauthorized', code: 'UNAUTHORIZED' }
        });
        continue;
      }

  
      // Block ownership scope reassignment (system-managed by auth context)
      const attemptedOwnershipFields = ownershipFields.filter((field) => Object.prototype.hasOwnProperty.call(record, field));
      if (attemptedOwnershipFields.length > 0) {
        errors.push({
          index: i,
          record,
          error: GuardErrors.systemManaged(attemptedOwnershipFields)
        });
        continue;
      }
  

      // Apply audit fields. Use the id-stripped `patch` so we don't
      // emit UPDATE x SET id = $1 — the WHERE clause already pins the row.
      const data = {
        ...patch,
    modifiedAt: new Date().toISOString(),
      };

      // Execute update
      try {
        const result = await handle.update(atsImports)
          .set(data)
          .where(and(buildFirewallConditions(ctx), eq(atsImports.id, record.id)))
          .returning();

        if (result[0]) {
          success.push(result[0]);
        }
      } catch (error: any) {
        const errMsg = [error?.message, error?.cause?.message, String(error)].filter(Boolean).join(' ');
        const isNotNull = errMsg.includes('NOT NULL constraint failed');
        const isUnique = errMsg.includes('UNIQUE constraint failed');
        const code = isNotNull ? 'NOT_NULL_VIOLATION' : isUnique ? 'UNIQUE_VIOLATION' : 'UPDATE_FAILED';
        const label = isNotNull ? 'Missing required field' : isUnique ? 'Duplicate value' : 'Update failed';
        errors.push({
          index: i,
          record,
          error: { error: label, layer: 'database', code }
        });

        if (failFast) {
          // Stop on first DB error. The outer tx wrapper (if any) will
          // catch the throw and roll back; on D1 the throw is caught by
          // the outer try and the partially-committed records remain.
          failFastIndex = i;
          failFastError = errors[errors.length - 1].error;
          throw error;
        }
      }
    }
  };

  let transactional = false;
  try {
    await processBatch(db);
  } catch (err) {
    return c.json(BatchErrors.failFastStopped(failFastIndex, failFastError), 400);
  }

  // Apply masking to success array
  const maskedSuccess = success;

  const meta = {
    total: records.length,
    succeeded: success.length,
    failed: errors.length,
    failFast,
    transactional
  };

  const statusCode = errors.length > 0 ? 207 : 200;
  return c.json({ success: maskedSuccess, errors, meta }, statusCode);
});

// ═══════════════════════════════════════════════════════
// BATCH DELETE: DELETE /atsImports/batch
// ═══════════════════════════════════════════════════════
app.delete('/batch', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Pre-query access check (role gate only)
  const batchDeleteAccess = {"roles":["owner"]};
  if (!await evaluateAccessPreRecord(batchDeleteAccess, ctx)) {
    return c.json(AccessErrors.roleRequired((batchDeleteAccess as any).roles || [], ctx.roles, (batchDeleteAccess as any).userRole, ctx.userRole), 403);
  }

  const parseResult = await parseJsonWithSchema(c.req.raw, BatchDeleteBodySchema);
  if (!parseResult.ok) {
    return c.json({ error: parseResult.error, code: parseResult.code, layer: 'validation', fields: parseResult.fields }, 400);
  }
  const body = parseResult.data as any;
  const ids = body.ids || [];
  const options = body.options || {};
  const failFast = options.failFast === true;

  // Validate batch size
  if (ids.length > 100) {
    return c.json(BatchErrors.sizeExceeded(100, ids.length), 400);
  }

  // Empty batch - return empty success
  if (ids.length === 0) {
    return c.json({
      success: [],
      errors: [],
      meta: { total: 0, succeeded: 0, failed: 0, failFast: false }
    }, 200);
  }

  // Batch fetch existing records with firewall
  const existingRecords = await db.select().from(atsImports)
    .where(and(buildFirewallConditions(ctx), inArray(atsImports.id, ids)));

  // Create lookup map for O(1) access
  const recordMap = new Map<string, any>();
  for (const record of existingRecords) {
    recordMap.set(record.id, record);
  }

  const errors: any[] = [];
  // Track each id alongside its original input index so that a downstream
  // bulk-delete failure can attribute its errors back to ids[i] in the
  // request body (records that fail the existence / access gate above
  // already get the right index from the loop counter).
  const validEntries: Array<{ id: string; originalIndex: number }> = [];
  const validIds: string[] = [];

  // Process each ID
  for (let i = 0; i < ids.length; i++) {
    const id = ids[i];
    const existingRecord = recordMap.get(id);

    // Check if record exists
    if (!existingRecord) {
      errors.push({
        index: i,
        id,
        error: { ...FirewallErrors.notFound(), details: { id } }
      });
      continue;
    }

    // Default: Authenticated access required
    if (!ctx.authenticated) {
      errors.push({
        index: i,
        id,
        error: { error: 'Unauthorized', code: 'UNAUTHORIZED' }
      });
      continue;
    }

    validIds.push(id);
    validEntries.push({ id, originalIndex: i });
  }

  // Fail-fast mode: stop on first existence/access error. Earlier deletes
  // executed by a previous request remain — this is fail-fast, not rollback.
  if (failFast && errors.length > 0) {
    return c.json(BatchErrors.failFastStopped(errors[0].index, errors[0].error), 400);
  }

  let success: any[] = [];

    // Soft delete - batch update
    if (validIds.length > 0) {
      try {
        const result = await db.update(atsImports)
          .set({
    deletedAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
          })
          .where(and(buildFirewallConditions(ctx), inArray(atsImports.id, validIds)))
          .returning();

        success = result;
      } catch (error: any) {
        // Database error during delete
        if (failFast) {
          return c.json({
            error: 'Batch delete failed',
            layer: 'validation',
            code: 'BATCH_DELETE_FAILED',
            details: { reason: error.message }
          }, 400);
        }
        // In partial success mode, fan the database error out to each id
        // that made it past the existence/access gate. Use the original
        // input index (tracked alongside the id) so the response matches
        // ids[i] in the request body.
        for (const v of validEntries) {
          errors.push({
            index: v.originalIndex,
            id: v.id,
            error: {
              error: 'Database delete failed',
              layer: 'validation',
              code: 'DELETE_FAILED',
              details: { reason: error.message }
            }
          });
        }
      }
    }

  // Bulk DELETE / UPDATE is a single SQL statement, atomic at the DB level —
  // either every validId is deleted or none is. The pre-bulk validation
  // errors don't touch the DB, so the write step is transactional regardless
  // of provider (including D1).
  const meta = {
    total: ids.length,
    succeeded: success.length,
    failed: errors.length,
    failFast,
    transactional: true
  };

  const statusCode = errors.length > 0 ? 207 : 200;
  return c.json({ success, errors, meta }, statusCode);
});

// ═══════════════════════════════════════════════════════
// GET: GET /atsImports/:id
// Supports: ?fields=id,name,email
// Order: 1. auth gate → 2. pre-query access (role-only) →
//        3. firewall query → 4. post-query access (record-aware) → 5. masking
// ═══════════════════════════════════════════════════════
// Closed allowlist of *declared* column names — gates ?fields= against
// real columns instead of Drizzle's internal table keys (`_`, `getSQL`,
// the column symbol bag) which a `field in <table>` check would admit.
const KNOWN_COLUMNS_GET: ReadonlySet<string> = new Set(["id","externalId","sourceSystem","payload","status","error","organizationId"]);

app.get('/:id', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');
  const id = c.req.param('id');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Active-org scope (cross-org access gated to platform admins).
  // See helpers/cross-tenant.ts for the full rationale.
  let effectiveCtx = ctx;
  const _xtRequestedOrgId = c.req.query('organizationId');
  // Same constraint as the list path: only fire when the caller has
  // an active org and is asking to leave it. PUBLIC + per-record
  // routes can still address by id without a session.
  if (_xtRequestedOrgId && ctx.activeOrgId && _xtRequestedOrgId !== ctx.activeOrgId) {
    if (ctx.userRole !== 'admin') {
      return c.json(AccessErrors.crossTenantForbidden(), 403);
    }
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId, roles: [] };
  } else if (_xtRequestedOrgId && !ctx.activeOrgId) {
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId };
  }

  // Pre-query access check (role gate only)
  const getAccess = {"roles":["admin","owner"]};
  if (!await evaluateAccessPreRecord(getAccess, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((getAccess as any).roles || [], effectiveCtx.roles, (getAccess as any).userRole, effectiveCtx.userRole), 403);
  }

  // Field selection: ?fields=id,name,email
  const url = new URL(c.req.url);
  const fieldsParam = url.searchParams.get('fields');
  let selectFields: Record<string, any> | undefined;
  if (fieldsParam) {
    const requested: Record<string, any> = {};
    for (const f of fieldsParam.split(',')) {
      const fieldName = f.trim();
      if (fieldName && KNOWN_COLUMNS_GET.has(fieldName)) {
        requested[fieldName] = atsImports[fieldName as keyof typeof atsImports];
      }
    }
    if (Object.keys(requested).length > 0) {
      selectFields = requested;
    }
  }

  // Query with firewall
  const baseQuery = selectFields ? db.select(selectFields).from(atsImports) : db.select().from(atsImports);
  const [record] = await baseQuery.where(and(buildFirewallConditions(effectiveCtx), eq(atsImports.id, id)));

  if (!record) {
    return c.json(FirewallErrors.notFound(), 403);
  }

  // Access check
  const getAccessFull = {"roles":["admin","owner"]};
  if (!await evaluateAccess(getAccessFull, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((getAccessFull as any).roles || [], effectiveCtx.roles, (getAccessFull as any).userRole, effectiveCtx.userRole), 403);
  }

  // Apply masking
  return jsonWithEtag(c, record);
});

// ═══════════════════════════════════════════════════════
// CREATE: POST /atsImports
// ═══════════════════════════════════════════════════════
app.post('/', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Access check
  if (!await evaluateAccess(CRUD_ACCESS.create.access, ctx)) {
    return c.json(AccessErrors.roleRequired((CRUD_ACCESS.create.access as any).roles || [], ctx.roles, (CRUD_ACCESS.create.access as any).userRole, ctx.userRole), 403);
  }

  if (!ctx.activeOrgId) {
    return c.json({
      error: 'Organization required',
      code: 'ORG_REQUIRED',
      hint: 'Set active organization in session before creating records'
    }, 400);
  }
const parseResult = await parseJsonWithSchema(c.req.raw, CreateBodySchema);
  if (!parseResult.ok) {
    return c.json({ error: parseResult.error, code: parseResult.code, layer: 'validation', fields: parseResult.fields }, 400);
  }
  const body = parseResult.data;
  


  // Apply defaults, ownership, and audit fields
  const now = new Date().toISOString();
  const data = {
    id: 'ats_' + crypto.randomUUID().replace(/-/g, ''),
    ...body,
    ...{},
    organizationId: ctx.activeOrgId,
    createdAt: now,
    modifiedAt: now,
  };

  try {
    const result = await db.insert(atsImports).values(data).returning();
    return c.json(result[0], 201);
  } catch (error: any) {
    // Search full error chain (D1/Drizzle may nest the real error in cause)
    const errMsg = [error?.message, error?.cause?.message, String(error)].filter(Boolean).join(' ');
    if (errMsg.includes('NOT NULL constraint failed')) {
      const match = errMsg.match(/NOT NULL constraint failed: \w+\.(\w+)/);
      const column = match?.[1];
      return c.json({
        error: 'Missing required field',
        layer: 'database',
        code: 'NOT_NULL_VIOLATION',
        details: { column },
        hint: column ? `The field "${column}" is required and cannot be null` : 'A required field is missing',
      }, 400);
    }
    if (errMsg.includes('UNIQUE constraint failed')) {
      const match = errMsg.match(/UNIQUE constraint failed: \w+\.(\w+)/);
      const column = match?.[1];
      return c.json({
        error: 'Duplicate value',
        layer: 'database',
        code: 'UNIQUE_VIOLATION',
        details: { column },
        hint: column ? `A record with this "${column}" already exists` : 'A unique constraint was violated',
      }, 409);
    }
    console.error('[CREATE] Database error:', error);
    return c.json({
      error: 'Insert failed',
      layer: 'database',
      code: 'INSERT_FAILED',
    }, 500);
  }
});

// ═══════════════════════════════════════════════════════
// UPDATE: PATCH /atsImports/:id
// Order: 1. auth gate → 2. pre-query access (role-only) → 3. firewall query
//        → 4. post-query access (record-aware) → 5. guards → 6. update → 7. masking
// ═══════════════════════════════════════════════════════
app.patch('/:id', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');
  const id = c.req.param('id');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Active-org scope (cross-org access gated to platform admins).
  // See helpers/cross-tenant.ts for the full rationale.
  let effectiveCtx = ctx;
  const _xtRequestedOrgId = c.req.query('organizationId');
  // Same constraint as the list path: only fire when the caller has
  // an active org and is asking to leave it. PUBLIC + per-record
  // routes can still address by id without a session.
  if (_xtRequestedOrgId && ctx.activeOrgId && _xtRequestedOrgId !== ctx.activeOrgId) {
    if (ctx.userRole !== 'admin') {
      return c.json(AccessErrors.crossTenantForbidden(), 403);
    }
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId, roles: [] };
  } else if (_xtRequestedOrgId && !ctx.activeOrgId) {
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId };
  }

  // Pre-query access check (role gate only — closes 404 vs 403 ID probes)
  if (!await evaluateAccessPreRecord(CRUD_ACCESS.update.access, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((CRUD_ACCESS.update.access as any).roles || [], effectiveCtx.roles, (CRUD_ACCESS.update.access as any).userRole, effectiveCtx.userRole), 403);
  }

  // Fetch with firewall
  const [record] = await db.select().from(atsImports)
    .where(and(buildFirewallConditions(effectiveCtx), eq(atsImports.id, id)));

  if (!record) {
    return c.json(FirewallErrors.notFound(), 403);
  }

  // Access check
  if (!await evaluateAccess(CRUD_ACCESS.update.access, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((CRUD_ACCESS.update.access as any).roles || [], effectiveCtx.roles, (CRUD_ACCESS.update.access as any).userRole, effectiveCtx.userRole), 403);
  }

  const parseResult = await parseJsonWithSchema(c.req.raw, UpdateBodySchema);
  if (!parseResult.ok) {
    return c.json({ error: parseResult.error, code: parseResult.code, layer: 'validation', fields: parseResult.fields }, 400);
  }
  const body = parseResult.data;
  // Block ownership scope reassignment (system-managed by auth context)
  const ownershipFields = ["organizationId"];
  const attemptedOwnershipFields = ownershipFields.filter((field) => Object.prototype.hasOwnProperty.call(body, field));
  if (attemptedOwnershipFields.length > 0) {
    return c.json(GuardErrors.systemManaged(attemptedOwnershipFields), 400);
  }
  

  // Apply audit fields
  const data = {
    ...body,
    modifiedAt: new Date().toISOString(),
  };

  try {
    const result = await db.update(atsImports).set(data)
      .where(and(buildFirewallConditions(effectiveCtx), eq(atsImports.id, id))).returning();

    return c.json(result[0]);
  } catch (error: any) {
    // Search full error chain (D1/Drizzle may nest the real error in cause)
    const errMsg = [error?.message, error?.cause?.message, String(error)].filter(Boolean).join(' ');
    if (errMsg.includes('NOT NULL constraint failed')) {
      const match = errMsg.match(/NOT NULL constraint failed: \w+\.(\w+)/);
      const column = match?.[1];
      return c.json({
        error: 'Missing required field',
        layer: 'database',
        code: 'NOT_NULL_VIOLATION',
        details: { column },
        hint: column ? `The field "${column}" is required and cannot be null` : 'A required field is missing',
      }, 400);
    }
    if (errMsg.includes('UNIQUE constraint failed')) {
      const match = errMsg.match(/UNIQUE constraint failed: \w+\.(\w+)/);
      const column = match?.[1];
      return c.json({
        error: 'Duplicate value',
        layer: 'database',
        code: 'UNIQUE_VIOLATION',
        details: { column },
        hint: column ? `A record with this "${column}" already exists` : 'A unique constraint was violated',
      }, 409);
    }
    console.error('[UPDATE] Database error:', error);
    return c.json({
      error: 'Update failed',
      layer: 'database',
      code: 'UPDATE_FAILED',
    }, 500);
  }
});

// ═══════════════════════════════════════════════════════
// DELETE: DELETE /atsImports/:id
// Order: 1. auth gate → 2. pre-query access (role-only) →
//        3. firewall query → 4. post-query access (record-aware) → 5. delete
// ═══════════════════════════════════════════════════════
app.delete('/:id', async (c) => {
  const ctx = c.get('ctx');
  const db = c.get('db');
  const id = c.req.param('id');

  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized', code: 'UNAUTHORIZED' }, 401);
  }

  // Active-org scope (cross-org access gated to platform admins).
  // See helpers/cross-tenant.ts for the full rationale.
  let effectiveCtx = ctx;
  const _xtRequestedOrgId = c.req.query('organizationId');
  // Same constraint as the list path: only fire when the caller has
  // an active org and is asking to leave it. PUBLIC + per-record
  // routes can still address by id without a session.
  if (_xtRequestedOrgId && ctx.activeOrgId && _xtRequestedOrgId !== ctx.activeOrgId) {
    if (ctx.userRole !== 'admin') {
      return c.json(AccessErrors.crossTenantForbidden(), 403);
    }
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId, roles: [] };
  } else if (_xtRequestedOrgId && !ctx.activeOrgId) {
    effectiveCtx = { ...ctx, activeOrgId: _xtRequestedOrgId };
  }

  // Pre-query access check (role gate only — closes 404 vs 403 ID probes)
  if (!await evaluateAccessPreRecord(CRUD_ACCESS.delete.access, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((CRUD_ACCESS.delete.access as any).roles || [], effectiveCtx.roles, (CRUD_ACCESS.delete.access as any).userRole, effectiveCtx.userRole), 403);
  }

  // Fetch with firewall
  const [record] = await db.select().from(atsImports)
    .where(and(buildFirewallConditions(effectiveCtx), eq(atsImports.id, id)));

  if (!record) {
    return c.json(FirewallErrors.notFound(), 403);
  }

  // Access check
  if (!await evaluateAccess(CRUD_ACCESS.delete.access, effectiveCtx)) {
    return c.json(AccessErrors.roleRequired((CRUD_ACCESS.delete.access as any).roles || [], effectiveCtx.roles, (CRUD_ACCESS.delete.access as any).userRole, effectiveCtx.userRole), 403);
  }
  
  // Soft delete
  await db.update(atsImports).set({
    deletedAt: new Date().toISOString(),
    modifiedAt: new Date().toISOString(),
  }).where(and(buildFirewallConditions(effectiveCtx), eq(atsImports.id, id)));

  return c.json({ success: true });
});

export default app;

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
