/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { ActionExecutor } from "../../../lib/types";
import { count } from "drizzle-orm";
import { applications } from "../schema";

export const execute: ActionExecutor = async ({ db }) => {
  const rows = await db
    .select({ status: applications.status, n: count() })
    .from(applications)
    .groupBy(applications.status);

  const byStatus: Record<string, number> = {};
  let total = 0;
  for (const r of rows as Array<{ status: string; n: number }>) {
    byStatus[r.status] = r.n;
    total += r.n;
  }
  return { byStatus, total };
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
