/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Webhook Event Emission
 *
 * Provides functions to emit outbound webhook events to registered endpoints.
 * Events are queued for reliable delivery with retry support.
 */

import { eq, and } from "drizzle-orm";
import type { CloudflareBindings } from "../../env";
import { createWebhooksDb, webhooksSchema } from "../../db";
import type { OutboundWebhookMessage } from "./routes";

const { webhookEndpoints, webhookDeliveries } = webhooksSchema;

export interface EmitWebhookOptions {
  /** Organization ID for scoping (optional) */
  organizationId?: string;
  /** User ID for scoping (optional) */
  userId?: string;
}

/**
 * Emit a webhook event to all matching endpoints
 *
 * Events are queued for asynchronous delivery. Each matching endpoint
 * will receive a separate delivery attempt.
 *
 * @param eventType - The event type (e.g., "user.created", "subscription.updated")
 * @param payload - The event payload (will be JSON stringified)
 * @param options - Scoping options (organizationId, userId)
 * @param env - Cloudflare environment bindings
 * @returns Number of endpoints queued for delivery
 *
 * @example
 * // Emit to all org endpoints
 * await emitWebhookEvent("user.created", { id: user.id, email: user.email }, { organizationId }, env);
 *
 * // Emit to user's endpoints
 * await emitWebhookEvent("subscription.changed", subscription, { userId }, env);
 */
export async function emitWebhookEvent(
  eventType: string,
  payload: unknown,
  options: EmitWebhookOptions,
  env: CloudflareBindings
): Promise<number> {
  const db = createWebhooksDb(env.WEBHOOKS_DB);

  // Find matching endpoints
  const endpoints = await findMatchingEndpoints(db, eventType, options);

  if (endpoints.length === 0) {
    return 0;
  }

  // Stringify payload once
  const payloadString = JSON.stringify({
    type: eventType,
    data: payload,
    createdAt: new Date().toISOString(),
  });

  // Create delivery records and queue messages
  const now = new Date();
  const deliveries: { id: string; endpointId: string }[] = [];

  for (const endpoint of endpoints) {
    const deliveryId = `whd_${crypto.randomUUID().replace(/-/g, "")}`;

    // Create delivery record
    await db.insert(webhookDeliveries).values({
      id: deliveryId,
      endpointId: endpoint.id,
      eventType,
      payload: payloadString,
      status: "pending",
      createdAt: now,
    });

    deliveries.push({ id: deliveryId, endpointId: endpoint.id });
  }

  // Queue all deliveries
  for (const delivery of deliveries) {
    const message: OutboundWebhookMessage = {
      type: "outbound",
      deliveryId: delivery.id,
      endpointId: delivery.endpointId,
      eventType,
      payload: payloadString,
    };

    await env.WEBHOOKS_QUEUE.send(message);
  }

  return deliveries.length;
}

/**
 * Find endpoints that match the event type and scope
 */
async function findMatchingEndpoints(
  db: ReturnType<typeof createWebhooksDb>,
  eventType: string,
  options: EmitWebhookOptions
): Promise<Array<{ id: string; url: string; secret: string; events: string }>> {
  // Build scope conditions
  const conditions: any[] = [eq(webhookEndpoints.enabled, true)];

  if (options.organizationId) {
    conditions.push(eq(webhookEndpoints.organizationId, options.organizationId));
  } else if (options.userId) {
    conditions.push(eq(webhookEndpoints.userId, options.userId));
  }

  // Get all enabled endpoints for the scope
  const endpoints = await db
    .select({
      id: webhookEndpoints.id,
      url: webhookEndpoints.url,
      secret: webhookEndpoints.secret,
      events: webhookEndpoints.events,
    })
    .from(webhookEndpoints)
    .where(and(...conditions));

  // Filter by event type (supports wildcards like "user.*")
  return endpoints.filter(endpoint => {
    const subscribedEvents = JSON.parse(endpoint.events) as string[];
    return matchesEventType(eventType, subscribedEvents);
  });
}

/**
 * Check if an event type matches any of the subscribed patterns
 *
 * Supports:
 * - Exact match: "user.created" matches "user.created"
 * - Wildcard: "user.*" matches "user.created", "user.updated"
 * - All events: "*" matches everything
 */
function matchesEventType(eventType: string, patterns: string[]): boolean {
  for (const pattern of patterns) {
    if (pattern === "*") {
      return true;
    }

    if (pattern === eventType) {
      return true;
    }

    // Wildcard pattern: "user.*" matches "user.created"
    if (pattern.endsWith(".*")) {
      const prefix = pattern.slice(0, -2);
      if (eventType.startsWith(prefix + ".")) {
        return true;
      }
    }
  }

  return false;
}

/**
 * Get available event types for documentation
 *
 * @returns List of event types that can be subscribed to
 */
export function getAvailableEventTypes(): string[] {
  return [
    // User events
    "user.created",
    "user.updated",
    "user.deleted",

    // Subscription events
    "subscription.created",
    "subscription.updated",
    "subscription.cancelled",
    "subscription.renewed",

    // Organization events
    "organization.created",
    "organization.updated",
    "organization.deleted",
    "organization.member_added",
    "organization.member_removed",

    // File events
    "file.uploaded",
    "file.deleted",

    // Wildcards
    "user.*",
    "subscription.*",
    "organization.*",
    "file.*",
    "*",
  ];
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
