/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Webhooks Module
 *
 * Provides infrastructure for both inbound (from external providers)
 * and outbound (to customer endpoints) webhooks.
 *
 * Features:
 * - Provider abstraction (Stripe, Paddle, GitHub, etc.)
 * - Signature verification
 * - Queue-based processing
 * - Event handler registry
 * - Delivery tracking with retries
 */

// Core exports
export { default as webhookRoutes } from "./routes";
export { handleWebhookMessage } from "./routes";
export type { WebhookMessage, InboundWebhookMessage, OutboundWebhookMessage } from "./routes";

// Provider exports
export {
  registerProvider,
  getProvider,
  getProviderNames,
  stripeProvider,
} from "./providers";
export type { InboundProvider, ParsedWebhookEvent } from "./providers";

// Handler exports
export {
  onWebhookEvent,
  dispatchEvent,
  hasHandlers,
  getRegisteredPatterns,
  clearHandlers,
} from "./handlers";
export type { WebhookEventContext, WebhookEventHandler } from "./handlers";

// Signing exports
export {
  signPayload,
  verifySignature,
  generateWebhookSecret,
} from "./sign";

// Emission exports
export {
  emitWebhookEvent,
  getAvailableEventTypes,
} from "./emit";
export type { EmitWebhookOptions } from "./emit";

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
