/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/**
 * Webhook Routes
 *
 * Handles both inbound (from external providers) and outbound (to customer endpoints) webhooks.
 *
 * Inbound Routes:
 * - POST /webhooks/v1/inbound/:provider - Receive webhook from external provider
 * - GET /webhooks/v1/inbound/events - List inbound events (admin)
 * - POST /webhooks/v1/inbound/events/:id/retry - Retry failed event (admin)
 *
 * Outbound Routes:
 * - GET /webhooks/v1/endpoints - List registered endpoints
 * - POST /webhooks/v1/endpoints - Register new endpoint
 * - GET /webhooks/v1/endpoints/:id - Get endpoint details
 * - PATCH /webhooks/v1/endpoints/:id - Update endpoint
 * - DELETE /webhooks/v1/endpoints/:id - Delete endpoint
 * - GET /webhooks/v1/endpoints/:id/deliveries - List delivery attempts
 * - POST /webhooks/v1/endpoints/:id/test - Send test event
 */

import { Hono } from "hono";
import { eq, desc, and } from "drizzle-orm";
import { z } from "zod";
import type { CloudflareBindings } from "../../env";
import type { AppContext } from "../types";
import { createWebhooksDb, webhooksSchema } from "../../db";
import { getProvider, registerProvider, stripeProvider } from "./providers";
import { dispatchEvent } from "./handlers";
import { signPayload, generateWebhookSecret } from "./sign";
import { getAvailableEventTypes } from "./emit";
import { getOrgMemberRole } from "../org-access";
import { parseJsonWithSchema } from "../request-validation";

const { webhookEvents, webhookEndpoints, webhookDeliveries } = webhooksSchema;

// Register default providers
registerProvider(stripeProvider);

// Roles allowed to manage org-scoped webhook endpoints
const WEBHOOK_ADMIN_ROLES: string[] = ["owner","admin"];
const MAX_WEBHOOK_EVENTS = 100;

const endpointCreateSchema = z.object({
  url: z.string().url().max(2048),
  events: z.array(z.string().min(1).max(120)).min(1).max(MAX_WEBHOOK_EVENTS),
  name: z.string().trim().min(1).max(120).optional(),
  organizationId: z.string().min(1).max(128).optional(),
}).strict();

const endpointPatchSchema = z.object({
  url: z.string().url().max(2048).optional(),
  events: z.array(z.string().min(1).max(120)).min(1).max(MAX_WEBHOOK_EVENTS).optional(),
  name: z.union([z.string().trim().min(1).max(120), z.null()]).optional(),
  enabled: z.boolean().optional(),
}).strict().refine(
  (payload) => Object.keys(payload).length > 0,
  { message: "At least one field must be provided for update.", path: ["body"] },
);

/**
 * Webhook queue message types
 */
export interface InboundWebhookMessage {
  type: "inbound";
  eventId: string;
  provider: string;
  eventType: string;
  payload: string;
}

export interface OutboundWebhookMessage {
  type: "outbound";
  deliveryId: string;
  endpointId: string;
  eventType: string;
  payload: string;
}

export type WebhookMessage = InboundWebhookMessage | OutboundWebhookMessage;

const app = new Hono<{
  Bindings: CloudflareBindings;
  Variables: { ctx: AppContext; authDb: any; requestId: string };
}>();

// ═══════════════════════════════════════════════════════════════════
// Provider Secret Configuration
// ═══════════════════════════════════════════════════════════════════

/**
 * Get the webhook secret for a provider from environment
 */
function getProviderSecret(provider: string, env: CloudflareBindings): string | undefined {
  switch (provider) {
    case "stripe":
      return env.STRIPE_WEBHOOK_SECRET;
    default:
      return undefined;
  }
}

async function requireOrgMember(c: any, organizationId: string, requiredRoles?: string[]) {
  const ctx = c.get("ctx");
  if (ctx.userRole === "admin") {
    return { ok: true, role: "admin" as string | null };
  }
  const authDb = c.get("authDb");
  if (!authDb) {
    return { ok: false, response: c.json({ error: "Auth database unavailable" }, 500) };
  }
  const role = await getOrgMemberRole(authDb, ctx.userId, organizationId);
  if (!role) {
    return { ok: false, response: c.json({ error: "Forbidden" }, 403) };
  }
  if (requiredRoles && !requiredRoles.includes(role)) {
    return { ok: false, response: c.json({ error: "Forbidden - insufficient role" }, 403) };
  }
  return { ok: true, role };
}

/**
 * Validate a webhook URL is safe for server-side fetch (anti-SSRF)
 */
function isAllowedWebhookUrl(urlStr: string): boolean {
  try {
    const parsed = new URL(urlStr);
    // Default policy is https-only. Insecure http: is gated by the
    // `webhooks.allowInsecure` compiler config (off by default).
    if (parsed.protocol !== "https:") return false;
    const hostname = parsed.hostname.toLowerCase();
    // Block localhost and loopback
    if (hostname === "localhost" || hostname === "127.0.0.1" || hostname === "::1" || hostname === "[::1]") return false;
    // Block link-local and metadata IPs
    if (hostname === "169.254.169.254" || hostname === "metadata.google.internal") return false;
    // Block private IPv4 ranges
    const parts = hostname.split(".");
    if (parts.length === 4 && parts.every(p => /^\d+$/.test(p))) {
      const [a, b] = parts.map(Number);
      if (a === 10) return false;                          // 10.0.0.0/8
      if (a === 172 && b >= 16 && b <= 31) return false;   // 172.16.0.0/12
      if (a === 192 && b === 168) return false;             // 192.168.0.0/16
      if (a === 169 && b === 254) return false;             // 169.254.0.0/16
      if (a === 0) return false;                            // 0.0.0.0/8
    }
    // Block internal Cloudflare service hostnames
    if (hostname.endsWith(".internal") || hostname.endsWith(".local")) return false;
    return true;
  } catch {
    return false;
  }
}

async function assertEndpointAccess(c: any, endpoint: any) {
  const ctx = c.get("ctx");
  if (endpoint.organizationId) {
    const check = await requireOrgMember(c, endpoint.organizationId, WEBHOOK_ADMIN_ROLES);
    if (!check.ok) return check.response;
    return null;
  }
  if (endpoint.userId) {
    if (endpoint.userId !== ctx.userId && ctx.userRole !== "admin") {
      return c.json({ error: "Forbidden" }, 403);
    }
    return null;
  }
  // No scope at all — refuse by default. Endpoints today always have a scope
  // set on create (organizationId or userId), but a future migration that
  // dropped that invariant would otherwise fall through and silently allow.
  return c.json({ error: "Forbidden" }, 403);
}

// ═══════════════════════════════════════════════════════════════════
// Inbound Webhooks
// ═══════════════════════════════════════════════════════════════════

/**
 * POST /webhooks/v1/inbound/:provider
 *
 * Receive webhook from external provider.
 * 1. Verify signature
 * 2. Log event to database
 * 3. Queue for processing
 * 4. Return 200 immediately
 */
app.post("/inbound/:provider", async (c) => {
  const providerName = c.req.param("provider");
  const provider = getProvider(providerName);

  if (!provider) {
    return c.json({ error: `Unknown provider: ${providerName}` }, 400);
  }

  // Get the webhook secret for this provider
  const secret = getProviderSecret(providerName, c.env);
  if (!secret) {
    console.error(`Webhook secret not configured for provider: ${providerName}`);
    return c.json({ error: "Webhook not configured" }, 500);
  }

  // Get raw body and signature
  const payload = await c.req.text();
  const signature = c.req.header("stripe-signature") ||
                    c.req.header("x-webhook-signature") ||
                    c.req.header("x-hub-signature-256") ||
                    "";

  // Verify signature
  const isValid = await provider.verifySignature(payload, signature, secret);
  if (!isValid) {
    console.warn(`Invalid webhook signature from ${providerName}`);
    return c.json({ error: "Invalid signature" }, 401);
  }

  // Parse the event
  const event = provider.parseEvent(payload);

  // Create database connection
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  // Generate event ID
  const eventId = `whe_${crypto.randomUUID().replace(/-/g, "")}`;

  // Idempotency: insert collapses on the unique (provider, externalId) index.
  // If a concurrent delivery already inserted the same external event, the
  // ON CONFLICT DO NOTHING returns no row and we short-circuit before
  // enqueueing — handlers run exactly once per externalId.
  // Events with NULL externalId are not subject to dedup (SQLite treats
  // NULL as distinct in unique indexes).
  const [inserted] = await db
    .insert(webhookEvents)
    .values({
      id: eventId,
      provider: providerName,
      eventType: event.type,
      externalId: event.externalId,
      payload,
      status: "received",
    })
    .onConflictDoNothing({
      target: [webhookEvents.provider, webhookEvents.externalId],
    })
    .returning({ id: webhookEvents.id });

  if (!inserted) {
    return c.json({ received: true, duplicate: true });
  }

  // Queue for processing
  const message: InboundWebhookMessage = {
    type: "inbound",
    eventId,
    provider: providerName,
    eventType: event.type,
    payload,
  };

  await c.env.WEBHOOKS_QUEUE.send(message);

  return c.json({ received: true, eventId });
});

/**
 * GET /webhooks/v1/inbound/events
 *
 * List inbound webhook events (admin only)
 */
app.get("/inbound/events", async (c) => {
  const ctx = c.get("ctx");

  if (ctx.userRole !== "admin") {
    return c.json({ error: "Admin access required" }, 403);
  }

  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const url = new URL(c.req.url);
  const limit = Math.min(parseInt(url.searchParams.get("limit") || "50"), 100);
  const offset = parseInt(url.searchParams.get("offset") || "0");
  const provider = url.searchParams.get("provider");
  const status = url.searchParams.get("status");

  let query = db.select().from(webhookEvents);

  const conditions = [];
  if (provider) {
    conditions.push(eq(webhookEvents.provider, provider));
  }
  if (status) {
    conditions.push(eq(webhookEvents.status, status));
  }

  if (conditions.length > 0) {
    query = query.where(and(...conditions)) as typeof query;
  }

  const events = await query
    .orderBy(desc(webhookEvents.createdAt))
    .limit(limit)
    .offset(offset);

  return c.json({
    data: events,
    pagination: { limit, offset, count: events.length },
  });
});

/**
 * POST /webhooks/v1/inbound/events/:id/retry
 *
 * Retry a failed webhook event (admin only)
 */
app.post("/inbound/events/:id/retry", async (c) => {
  const ctx = c.get("ctx");

  if (ctx.userRole !== "admin") {
    return c.json({ error: "Admin access required" }, 403);
  }

  const eventId = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [event] = await db
    .select()
    .from(webhookEvents)
    .where(eq(webhookEvents.id, eventId))
    .limit(1);

  if (!event) {
    return c.json({ error: "Event not found" }, 404);
  }

  await db
    .update(webhookEvents)
    .set({
      status: "received",
      error: null,
      attempts: 0,
    })
    .where(eq(webhookEvents.id, eventId));

  const message: InboundWebhookMessage = {
    type: "inbound",
    eventId: event.id,
    provider: event.provider,
    eventType: event.eventType,
    payload: event.payload,
  };

  await c.env.WEBHOOKS_QUEUE.send(message);

  return c.json({ success: true, eventId });
});

// ═══════════════════════════════════════════════════════════════════
// Outbound Webhook Endpoints
// ═══════════════════════════════════════════════════════════════════

/**
 * GET /webhooks/v1/events
 *
 * Get available event types for subscription
 */
app.get("/events", async (c) => {
  return c.json({ events: getAvailableEventTypes() });
});

/**
 * GET /webhooks/v1/endpoints
 *
 * List webhook endpoints for the current user/org
 */
app.get("/endpoints", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const url = new URL(c.req.url);
  const organizationId = url.searchParams.get("organizationId");

  // Build query conditions
  const conditions = [];
  if (organizationId) {
    const check = await requireOrgMember(c, organizationId, WEBHOOK_ADMIN_ROLES);
    if (!check.ok) return check.response;
    conditions.push(eq(webhookEndpoints.organizationId, organizationId));
  } else {
    conditions.push(eq(webhookEndpoints.userId, ctx.userId));
  }

  const endpoints = await db
    .select({
      id: webhookEndpoints.id,
      name: webhookEndpoints.name,
      url: webhookEndpoints.url,
      events: webhookEndpoints.events,
      enabled: webhookEndpoints.enabled,
      createdAt: webhookEndpoints.createdAt,
      updatedAt: webhookEndpoints.updatedAt,
    })
    .from(webhookEndpoints)
    .where(and(...conditions))
    .orderBy(desc(webhookEndpoints.createdAt));

  // Parse events JSON
  const data = endpoints.map(ep => ({
    ...ep,
    events: JSON.parse(ep.events),
  }));

  return c.json({ data });
});

/**
 * POST /webhooks/v1/endpoints
 *
 * Register a new webhook endpoint
 */
app.post("/endpoints", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const parsedBody = await parseJsonWithSchema(c.req.raw, endpointCreateSchema);
  if (!parsedBody.ok) {
    return c.json(parsedBody, 400);
  }
  const { url, events, name, organizationId } = parsedBody.data;

  // Validate URL (syntax + anti-SSRF)
  if (!isAllowedWebhookUrl(url)) {
    return c.json({ error: "Invalid or disallowed URL" }, 400);
  }

  if (organizationId) {
    const check = await requireOrgMember(c, organizationId, WEBHOOK_ADMIN_ROLES);
    if (!check.ok) return check.response;
  }

  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const id = `wep_${crypto.randomUUID().replace(/-/g, "")}`;
  const secret = generateWebhookSecret();
  const now = new Date();

  await db.insert(webhookEndpoints).values({
    id,
    organizationId: organizationId || null,
    userId: organizationId ? null : ctx.userId,
    name: name || null,
    url,
    secret,
    events: JSON.stringify(events),
    enabled: true,
    createdAt: now,
  });

  return c.json({
    id,
    name,
    url,
    events,
    enabled: true,
    secret, // Only returned on creation
    createdAt: now,
  }, 201);
});

/**
 * GET /webhooks/v1/endpoints/:id
 *
 * Get endpoint details (secret is partially masked)
 */
app.get("/endpoints/:id", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  // Mask secret (show first 10 chars)
  const maskedSecret = endpoint.secret.slice(0, 10) + "...";

  return c.json({
    ...endpoint,
    events: JSON.parse(endpoint.events),
    secret: maskedSecret,
  });
});

/**
 * PATCH /webhooks/v1/endpoints/:id
 *
 * Update endpoint
 */
app.patch("/endpoints/:id", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  const parsedBody = await parseJsonWithSchema(c.req.raw, endpointPatchSchema);
  if (!parsedBody.ok) {
    return c.json(parsedBody, 400);
  }
  const body = parsedBody.data;
  const updates: Record<string, any> = { updatedAt: new Date() };

  if (body.url !== undefined) {
    if (!isAllowedWebhookUrl(body.url)) {
      return c.json({ error: "Invalid or disallowed URL" }, 400);
    }
    updates.url = body.url;
  }

  if (body.events !== undefined) {
    updates.events = JSON.stringify(body.events);
  }

  if (body.name !== undefined) {
    updates.name = body.name;
  }

  if (body.enabled !== undefined) {
    updates.enabled = body.enabled;
  }

  await db
    .update(webhookEndpoints)
    .set(updates)
    .where(eq(webhookEndpoints.id, id));

  const [updated] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  return c.json({
    ...updated,
    events: JSON.parse(updated!.events),
    secret: updated!.secret.slice(0, 10) + "...",
  });
});

/**
 * DELETE /webhooks/v1/endpoints/:id
 *
 * Delete endpoint
 */
app.delete("/endpoints/:id", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  await db.delete(webhookEndpoints).where(eq(webhookEndpoints.id, id));

  return c.json({ success: true });
});

/**
 * GET /webhooks/v1/endpoints/:id/deliveries
 *
 * List delivery attempts for an endpoint
 */
app.get("/endpoints/:id/deliveries", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  // Check endpoint ownership
  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  const url = new URL(c.req.url);
  const limit = Math.min(parseInt(url.searchParams.get("limit") || "50"), 100);
  const offset = parseInt(url.searchParams.get("offset") || "0");

  const deliveries = await db
    .select()
    .from(webhookDeliveries)
    .where(eq(webhookDeliveries.endpointId, id))
    .orderBy(desc(webhookDeliveries.createdAt))
    .limit(limit)
    .offset(offset);

  return c.json({
    data: deliveries,
    pagination: { limit, offset, count: deliveries.length },
  });
});

/**
 * POST /webhooks/v1/endpoints/:id/test
 *
 * Send a test event to the endpoint
 */
app.post("/endpoints/:id/test", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  if (!isAllowedWebhookUrl(endpoint.url)) {
    return c.json({ error: "Invalid or disallowed URL" }, 400);
  }

  // Create test payload
  const testPayload = JSON.stringify({
    type: "webhook.test",
    data: {
      message: "This is a test webhook",
      timestamp: new Date().toISOString(),
    },
    createdAt: new Date().toISOString(),
  });

  // Sign and send immediately (not queued)
  const signature = await signPayload(testPayload, endpoint.secret);

  try {
    const response = await fetch(endpoint.url, {
      method: "POST",
      // SSRF: refuse to follow redirects so a registered HTTPS endpoint can't
      // 302 the signed test payload into an internal address. We mirror the
      // queued delivery path's behavior (see below) and surface a 3xx as a
      // failed test rather than transparently following it.
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
        "X-Webhook-Signature": signature,
        "X-Webhook-Event": "webhook.test",
      },
      body: testPayload,
    });

    if (response.status >= 300 && response.status < 400) {
      return c.json({
        success: false,
        status: response.status,
        statusText: response.statusText,
        error: "Endpoint responded with a redirect; webhooks won't follow redirects to internal addresses.",
      });
    }

    return c.json({
      success: response.ok,
      status: response.status,
      statusText: response.statusText,
    });
  } catch (error) {
    return c.json({
      success: false,
      error: error instanceof Error ? error.message : "Request failed",
    });
  }
});

/**
 * POST /webhooks/v1/endpoints/:id/rotate-secret
 *
 * Generate a new secret for the endpoint
 */
app.post("/endpoints/:id/rotate-secret", async (c) => {
  const ctx = c.get("ctx");

  if (!ctx.userId) {
    return c.json({ error: "Not authenticated" }, 401);
  }

  const id = c.req.param("id");
  const db = createWebhooksDb(c.env.WEBHOOKS_DB);

  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, id))
    .limit(1);

  if (!endpoint) {
    return c.json({ error: "Endpoint not found" }, 404);
  }

  const accessError = await assertEndpointAccess(c, endpoint);
  if (accessError) return accessError;

  const newSecret = generateWebhookSecret();

  await db
    .update(webhookEndpoints)
    .set({
      secret: newSecret,
      updatedAt: new Date(),
    })
    .where(eq(webhookEndpoints.id, id));

  return c.json({ secret: newSecret });
});

export default app;

// ═══════════════════════════════════════════════════════════════════
// Queue Consumer Handler
// ═══════════════════════════════════════════════════════════════════

/**
 * Process webhook queue messages
 * Called by the queue consumer in index.ts
 */
export async function handleWebhookMessage(
  message: WebhookMessage,
  env: CloudflareBindings
): Promise<void> {
  const db = createWebhooksDb(env.WEBHOOKS_DB);

  if (message.type === "inbound") {
    await handleInboundMessage(message, env, db);
  } else if (message.type === "outbound") {
    await handleOutboundMessage(message, env, db);
  }
}

async function handleInboundMessage(
  message: InboundWebhookMessage,
  env: CloudflareBindings,
  db: ReturnType<typeof createWebhooksDb>
): Promise<void> {
  const { eventId, provider, eventType, payload } = message;

  await db
    .update(webhookEvents)
    .set({ status: "processing" })
    .where(eq(webhookEvents.id, eventId));

  try {
    const data = JSON.parse(payload);
    const eventData = data.data?.object || data.data || data;

    await dispatchEvent(provider, eventType, eventData, env);

    await db
      .update(webhookEvents)
      .set({
        status: "processed",
        processedAt: new Date(),
      })
      .where(eq(webhookEvents.id, eventId));
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);

    const [event] = await db
      .select({ attempts: webhookEvents.attempts })
      .from(webhookEvents)
      .where(eq(webhookEvents.id, eventId))
      .limit(1);

    await db
      .update(webhookEvents)
      .set({
        status: "failed",
        error: errorMessage,
        attempts: (event?.attempts || 0) + 1,
      })
      .where(eq(webhookEvents.id, eventId));

    throw error;
  }
}

async function handleOutboundMessage(
  message: OutboundWebhookMessage,
  env: CloudflareBindings,
  db: ReturnType<typeof createWebhooksDb>
): Promise<void> {
  const { deliveryId, endpointId, eventType, payload } = message;

  // Get endpoint details
  const [endpoint] = await db
    .select()
    .from(webhookEndpoints)
    .where(eq(webhookEndpoints.id, endpointId))
    .limit(1);

  if (!endpoint) {
    // Endpoint deleted, mark delivery as failed
    await db
      .update(webhookDeliveries)
      .set({
        status: "failed",
        responseBody: "Endpoint not found",
        lastAttemptAt: new Date(),
      })
      .where(eq(webhookDeliveries.id, deliveryId));
    return;
  }

  if (!endpoint.enabled) {
    // Endpoint disabled, mark as failed
    await db
      .update(webhookDeliveries)
      .set({
        status: "failed",
        responseBody: "Endpoint disabled",
        lastAttemptAt: new Date(),
      })
      .where(eq(webhookDeliveries.id, deliveryId));
    return;
  }

  if (!isAllowedWebhookUrl(endpoint.url)) {
    await db
      .update(webhookDeliveries)
      .set({
        status: "failed",
        responseBody: "Endpoint URL is disallowed",
        lastAttemptAt: new Date(),
      })
      .where(eq(webhookDeliveries.id, deliveryId));
    return;
  }

  // Sign payload
  const signature = await signPayload(payload, endpoint.secret);

  // Get current attempts
  const [delivery] = await db
    .select({ attempts: webhookDeliveries.attempts })
    .from(webhookDeliveries)
    .where(eq(webhookDeliveries.id, deliveryId))
    .limit(1);

  const attempts = (delivery?.attempts || 0) + 1;
  const now = new Date();

  try {
    const response = await fetch(endpoint.url, {
      method: "POST",
      // SSRF: refuse to follow redirects so a public endpoint can't bounce
      // a signed payload into an internal address. 3xx is treated as a
      // terminal delivery failure (no retry) below.
      redirect: "manual",
      headers: {
        "Content-Type": "application/json",
        "X-Webhook-Signature": signature,
        "X-Webhook-Event": eventType,
        "X-Webhook-Delivery": deliveryId,
      },
      body: payload,
    });

    if (response.status >= 300 && response.status < 400) {
      const location = response.headers.get("location") || "<unknown>";
      await db
        .update(webhookDeliveries)
        .set({
          status: "failed",
          attempts,
          lastAttemptAt: now,
          nextRetryAt: null,
          responseStatus: response.status,
          responseBody: `Refused to follow redirect to ${location}`.slice(0, 1000),
        })
        .where(eq(webhookDeliveries.id, deliveryId));
      return;
    }

    const responseBody = await response.text().catch(() => "");

    if (response.ok) {
      // Success
      await db
        .update(webhookDeliveries)
        .set({
          status: "delivered",
          attempts,
          lastAttemptAt: now,
          responseStatus: response.status,
          responseBody: responseBody.slice(0, 1000), // Truncate
        })
        .where(eq(webhookDeliveries.id, deliveryId));
    } else {
      // HTTP error - calculate next retry with exponential backoff
      const nextRetryAt = new Date(now.getTime() + Math.min(Math.pow(2, attempts) * 1000, 3600000)); // Max 1 hour

      await db
        .update(webhookDeliveries)
        .set({
          status: "pending", // Keep pending for retry
          attempts,
          lastAttemptAt: now,
          nextRetryAt,
          responseStatus: response.status,
          responseBody: responseBody.slice(0, 1000),
        })
        .where(eq(webhookDeliveries.id, deliveryId));

      // Throw to trigger queue retry
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }
  } catch (error) {
    // Network error
    const errorMessage = error instanceof Error ? error.message : String(error);
    const nextRetryAt = new Date(now.getTime() + Math.min(Math.pow(2, attempts) * 1000, 3600000));

    await db
      .update(webhookDeliveries)
      .set({
        status: attempts >= 3 ? "failed" : "pending",
        attempts,
        lastAttemptAt: now,
        nextRetryAt: attempts >= 3 ? null : nextRetryAt,
        responseBody: errorMessage.slice(0, 1000),
      })
      .where(eq(webhookDeliveries.id, deliveryId));

    if (attempts < 3) {
      throw error; // Trigger retry
    }
    // Max retries reached, don't throw
  }
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
