--
-- Generated by quickback.dev
--
-- This file is managed by the Quickback Compiler — do not edit directly.
-- To make changes, update your config and feature definitions in the quickback/ folder,
-- then run `quickback compile` to regenerate.
CREATE TABLE `audit_events` (
	`id` text PRIMARY KEY NOT NULL,
	`request_id` text NOT NULL,
	`actor_user_id` text,
	`actor_user_role` text,
	`actor_org_id` text,
	`action_name` text NOT NULL,
	`resource` text NOT NULL,
	`operation` text NOT NULL,
	`target_scope` text NOT NULL,
	`target_org_id` text,
	`target_record_id` text,
	`unsafe_reason` text NOT NULL,
	`result` text NOT NULL,
	`row_count` integer,
	`error_code` text,
	`error_message` text,
	`metadata` text,
	`created_at` integer NOT NULL
);

CREATE INDEX `audit_events_request_idx` ON `audit_events` (`request_id`);
CREATE INDEX `audit_events_actor_org_idx` ON `audit_events` (`actor_org_id`);
CREATE INDEX `audit_events_target_org_idx` ON `audit_events` (`target_org_id`);
CREATE INDEX `audit_events_action_idx` ON `audit_events` (`action_name`);
CREATE INDEX `audit_events_result_idx` ON `audit_events` (`result`);
CREATE INDEX `audit_events_created_at_idx` ON `audit_events` (`created_at`);

-- Generated by quickback.dev
--
-- THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
-- THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
-- DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
-- OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
-- OR OTHER DEALINGS IN THE FILE.
