/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";

export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  requestId: text("request_id").notNull(),

  actorUserId: text("actor_user_id"),
  actorUserRole: text("actor_user_role"),
  actorOrgId: text("actor_org_id"),

  actionName: text("action_name").notNull(),
  resource: text("resource").notNull(),
  operation: text("operation").notNull(),

  targetScope: text("target_scope").notNull(),
  targetOrgId: text("target_org_id"),
  targetRecordId: text("target_record_id"),

  unsafeReason: text("unsafe_reason").notNull(),
  result: text("result").notNull(), // success | denied | error
  rowCount: integer("row_count"),

  errorCode: text("error_code"),
  errorMessage: text("error_message"),

  metadata: text("metadata"), // JSON string payload
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
}, (table) => ({
  requestIdx: index("audit_events_request_idx").on(table.requestId),
  actorOrgIdx: index("audit_events_actor_org_idx").on(table.actorOrgId),
  targetOrgIdx: index("audit_events_target_org_idx").on(table.targetOrgId),
  actionIdx: index("audit_events_action_idx").on(table.actionName),
  resultIdx: index("audit_events_result_idx").on(table.result),
  createdAtIdx: index("audit_events_created_at_idx").on(table.createdAt),
}));

export type AuditEvent = typeof auditEvents.$inferSelect;
export type NewAuditEvent = typeof auditEvents.$inferInsert;

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
