/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { drizzle } from 'drizzle-orm/bun-sqlite';
import { Database } from 'bun:sqlite';
import { migrate } from 'drizzle-orm/bun-sqlite/migrator';
import { mkdirSync, existsSync } from 'fs';
import { join } from 'path';
import * as authSchema from './auth-schema';
import * as featuresSchema from './features-schema';

// Re-export schemas
export { authSchema, featuresSchema };
export const schema = { ...authSchema, ...featuresSchema };

// Ensure data directory exists
const dataDir = 'data';
if (!existsSync(dataDir)) {
  mkdirSync(dataDir, { recursive: true });
  console.log('📁 Created data directory');
}

// Auth database
const authSqlite = new Database('data/auth.db');
export const authDb = drizzle(authSqlite, { schema: authSchema });

// Features database
const featuresSqlite = new Database('data/features.db');
export const db = drizzle(featuresSqlite, { schema: featuresSchema });

// Auto-apply migrations on startup
const authMigrationsFolder = join(import.meta.dir, '../../drizzle/auth');
if (existsSync(authMigrationsFolder)) {
  try {
    migrate(authDb, { migrationsFolder: authMigrationsFolder });
    console.log('✅ Auth database migrations applied');
  } catch (error: any) {
    if (!error.message?.includes('already exists')) {
      console.error('⚠️ Auth migration error:', error.message);
    }
  }
}

const featuresMigrationsFolder = join(import.meta.dir, '../../drizzle/features');
if (existsSync(featuresMigrationsFolder)) {
  try {
    migrate(db, { migrationsFolder: featuresMigrationsFolder });
    console.log('✅ Features database migrations applied');
  } catch (error: any) {
    if (!error.message?.includes('already exists')) {
      console.error('⚠️ Features migration error:', error.message);
    }
  }
}

export function createAuthDb() {
  return authDb;
}

export function createDb() {
  return db;
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
