/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { D1Database } from "@cloudflare/workers-types";
import { drizzle } from "drizzle-orm/d1";
import * as authSchema from "./auth-schema";
import * as featuresSchema from "./features-schema";
import * as webhooksSchema from "./webhooks-schema";

// Re-export schemas for convenience
export { authSchema, featuresSchema, webhooksSchema };

// Combined schema — re-exports auth + features for convenience
export const schema = { ...authSchema, ...featuresSchema, ...webhooksSchema };

// Export types for the database instances
export type AuthDatabase = ReturnType<typeof createAuthDb>;
export type FeaturesDatabase = ReturnType<typeof createDb>;
export type WebhooksDatabase = ReturnType<typeof createWebhooksDb>;

/**
 * Create auth database instance from AUTH_DB binding
 * Contains: users, sessions, accounts, organizations, members, invitations, etc.
 * @param d1 - The D1 database binding for auth (AUTH_DB)
 * @returns Drizzle database instance for auth tables
 */
export function createAuthDb(d1: D1Database) {
  return drizzle(d1, {
    schema: authSchema,
    logger: false,
  });
}

/**
 * Create features database instance from DB binding
 * Contains: application feature tables
 * @param d1 - The D1 database binding for features (DB)
 * @returns Drizzle database instance for feature tables
 */
export function createDb(d1: D1Database) {
  return drizzle(d1, {
    schema: featuresSchema,
    logger: false,
  });
}

/**
 * Create webhooks database instance from WEBHOOKS_DB binding
 * Contains: webhook events, endpoints, deliveries
 * @param d1 - The D1 database binding for webhooks (WEBHOOKS_DB)
 * @returns Drizzle database instance for webhook tables
 */
export function createWebhooksDb(d1: D1Database) {
  return drizzle(d1, {
    schema: webhooksSchema,
    logger: false,
  });
}

// Re-export drizzle-orm utilities for convenience
export * from "drizzle-orm";

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
