/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { sqliteTable, text, integer, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

/**
 * Webhook Events (Inbound)
 *
 * Stores incoming webhook events from external providers (Stripe, Paddle, GitHub, etc.)
 * Events are logged first, then processed via queue for reliability.
 */
export const webhookEvents = sqliteTable("webhook_events", {
  id: text("id").primaryKey(),

  /** Provider name: 'stripe', 'paddle', 'github', etc. */
  provider: text("provider").notNull(),

  /** Event type from provider: 'checkout.session.completed', 'invoice.paid', etc. */
  eventType: text("event_type").notNull(),

  /** Provider's event ID (for idempotency) */
  externalId: text("external_id"),

  /** Raw JSON payload from the webhook */
  payload: text("payload").notNull(),

  /** Processing status: 'received', 'processing', 'processed', 'failed' */
  status: text("status").notNull().default("received"),

  /** Number of processing attempts */
  attempts: integer("attempts").default(0),

  /** When the event was successfully processed */
  processedAt: integer("processed_at", { mode: "timestamp_ms" }),

  /** Error message if processing failed */
  error: text("error"),

  /** When the event was received */
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
}, (table) => ({
  providerIdx: index("webhook_events_provider_idx").on(table.provider),
  statusIdx: index("webhook_events_status_idx").on(table.status),
  externalIdIdx: index("webhook_events_external_id_idx").on(table.externalId),
}));

/**
 * Webhook Endpoints (Outbound)
 *
 * Customer-registered webhook endpoints for receiving events from your app.
 * Organizations or users can register URLs to receive specific event types.
 */
export const webhookEndpoints = sqliteTable("webhook_endpoints", {
  id: text("id").primaryKey(),

  /** Organization ID (for org-level webhooks) */
  organizationId: text("organization_id"),

  /** User ID (for user-level webhooks) */
  userId: text("user_id"),

  /** Display name for the endpoint */
  name: text("name"),

  /** The URL to send webhooks to */
  url: text("url").notNull(),

  /** Secret used to sign webhook payloads (HMAC-SHA256) */
  secret: text("secret").notNull(),

  /** JSON array of event types to subscribe to: ['user.created', 'subscription.*'] */
  events: text("events").notNull(),

  /** Whether the endpoint is enabled */
  enabled: integer("enabled", { mode: "boolean" }).default(true),

  /** When the endpoint was created */
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),

  /** When the endpoint was last updated */
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }),
}, (table) => ({
  orgIdx: index("webhook_endpoints_org_idx").on(table.organizationId),
  userIdx: index("webhook_endpoints_user_idx").on(table.userId),
  enabledIdx: index("webhook_endpoints_enabled_idx").on(table.enabled),
}));

/**
 * Webhook Deliveries (Outbound)
 *
 * Tracks delivery attempts for outbound webhooks.
 * Supports retry with exponential backoff.
 */
export const webhookDeliveries = sqliteTable("webhook_deliveries", {
  id: text("id").primaryKey(),

  /** The endpoint this delivery is for */
  endpointId: text("endpoint_id").notNull(),

  /** Event type being delivered */
  eventType: text("event_type").notNull(),

  /** JSON payload being sent */
  payload: text("payload").notNull(),

  /** Delivery status: 'pending', 'delivered', 'failed' */
  status: text("status").notNull().default("pending"),

  /** Number of delivery attempts */
  attempts: integer("attempts").default(0),

  /** When the last delivery attempt was made */
  lastAttemptAt: integer("last_attempt_at", { mode: "timestamp_ms" }),

  /** When to retry (for exponential backoff) */
  nextRetryAt: integer("next_retry_at", { mode: "timestamp_ms" }),

  /** HTTP status code from the last attempt */
  responseStatus: integer("response_status"),

  /** Response body from the last attempt (truncated) */
  responseBody: text("response_body"),

  /** When the delivery was queued */
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
}, (table) => ({
  endpointIdx: index("webhook_deliveries_endpoint_idx").on(table.endpointId),
  statusIdx: index("webhook_deliveries_status_idx").on(table.status),
  nextRetryIdx: index("webhook_deliveries_next_retry_idx").on(table.nextRetryAt),
}));

// Type exports
export type WebhookEvent = typeof webhookEvents.$inferSelect;
export type NewWebhookEvent = typeof webhookEvents.$inferInsert;

export type WebhookEndpoint = typeof webhookEndpoints.$inferSelect;
export type NewWebhookEndpoint = typeof webhookEndpoints.$inferInsert;

export type WebhookDelivery = typeof webhookDeliveries.$inferSelect;
export type NewWebhookDelivery = typeof webhookDeliveries.$inferInsert;

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
