/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Generated security helpers for customView
import { eq, and, isNull, type SQL } from 'drizzle-orm';
import type { Context } from 'hono';
import { customView } from './schema';
import type { AppContext } from '../../lib/types';

/**
 * Firewall conditions for customView
 * exception (no isolation)
 */
export function buildFirewallConditions(_ctx: AppContext): SQL | undefined {
  return undefined;
}

/**
 * Helper for manual routes — wraps handler with auth check and firewall
 */
export async function withFirewall<T>(
  c: Context,
  handler: (ctx: AppContext, firewall: SQL | undefined) => Promise<T>
): Promise<Response | T> {
  const ctx = c.get('ctx') as AppContext;
  if (!ctx?.userId) {
    return c.json({ error: 'Unauthorized', code: 'AUTH_REQUIRED' }, 401);
  }
  const firewall = buildFirewallConditions(ctx);
  return handler(ctx, firewall);
}

// CRUD Access
export const CRUD_ACCESS = {
  "create": {
    "access": {
      "roles": [
        "owner",
        "admin",
        "member"
      ]
    }
  },
  "update": {
    "access": {
      "roles": [
        "owner",
        "admin",
        "member"
      ]
    }
  },
  "delete": {
    "access": {
      "roles": [
        "owner",
        "admin",
        "member"
      ]
    }
  }
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
