/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { ActionExecutor, TransitionLostError } from "../../../lib/types";
import { interviews } from "../schema";
import { interviewScores } from "../interview_scores";

export const execute: ActionExecutor = async ({
  db,
  ctx,
  record,
  input,
  auditFields,
  whereTransition,
}) => {
  // 1) Flip the parent's status under the TOCTOU-safe transition guard.
  const [updated] = await db
    .update(interviews)
    .set({ status: "completed", modifiedAt: auditFields!.modifiedAt })
    .where(whereTransition!(interviews))
    .returning();
  if (!updated) throw new TransitionLostError("status", record.status, "completed");

  // 2) Insert the score row into the internal Drizzle table. The
  //    scoped `db` auto-stamps `organizationId`, `createdBy`,
  //    `createdAt`, etc. — we just supply the business columns and
  //    a generated id.
  await db.insert(interviewScores).values({
    id: crypto.randomUUID(),
    interviewId: record.id,
    scorerId: ctx.userId,
    rating: input.rating,
    recommendation: input.recommendation,
    comments: input.comments ?? null,
  });

  return updated;
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
