/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { ActionError, type ActionExecutor } from "../../../lib/types";
import { interviews } from "../schema";

export const execute: ActionExecutor = async ({
  db,
  record,
  input,
  auditFields,
  whereRecord,
}) => {
  // Refuse to reschedule once the interview is past its terminal state.
  // Belt-and-suspenders alongside the route's role gate — the access
  // policy admits owners + admins, but neither should be able to
  // reschedule a completed/cancelled interview.
  if (record.status !== "scheduled") {
    throw new ActionError(
      `Cannot reschedule a ${record.status} interview`,
      "INTERVIEW_NOT_RESCHEDULABLE",
      409,
    );
  }

  const [updated] = await db
    .update(interviews)
    .set({
      scheduledAt: input.scheduledAt,
      durationMin: input.durationMin ?? record.durationMin,
      modifiedAt: auditFields!.modifiedAt,
    })
    .where(whereRecord!(interviews))
    .returning();
  return updated;
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
