/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import type { ActionExecutor } from "../../../lib/types";
import { avg, count, desc } from "drizzle-orm";
import { interviewScores } from "../interview_scores";

export const execute: ActionExecutor = async ({ db }) => {
  // Org scoping is automatic — `db` is the scoped Drizzle client, so
  // the WHERE clause includes `organization_id = ctx.activeOrgId`
  // for every table touched, including the internal `interview_scores`
  // table. No explicit `where(eq(...))` needed.
  const avgRating = avg(interviewScores.rating).mapWith(Number);
  const rows = (await db
    .select({
      interviewId: interviewScores.interviewId,
      avgRating,
      scorerCount: count(),
    })
    .from(interviewScores)
    .groupBy(interviewScores.interviewId)
    .orderBy(desc(avgRating))) as Array<{
    interviewId: string;
    avgRating: number | null;
    scorerCount: number;
  }>;

  return {
    interviews: rows.map((r) => ({
      interviewId: r.interviewId,
      averageRating: r.avgRating ?? 0,
      scorerCount: r.scorerCount,
    })),
    totalScored: rows.length,
  };
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
