/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
// Generated actions for interviews
import { z } from 'zod';
import type { AppContext } from '../../lib/types';
import type { Services } from '../../lib/services';

// Handler imports
import { execute as completeExecute } from './handlers/complete';
import { execute as rescheduleExecute } from './handlers/reschedule';
import { execute as scoreSummaryExecute } from './handlers/score-summary';

export const actions = {
  "complete": {
    description: "Finalize an interview with a score and recommendation.",
    input: z.object({
      rating: z.number().int().min(1).max(5),
      recommendation: z.enum(["strong-no", "no", "neutral", "yes", "strong-yes"]),
      comments: z.string().max(2000).optional(),
    }),
    access: {
          "roles": [
                "admin",
                "owner",
                "recruiter"
          ],
          "record": {
                "scheduledBy": {
                      "equals": "$ctx.userId"
                }
          }
    },
    transition: {
          "field": "status",
          "to": "completed",
          "fromTo": {
                "scheduled": [
                      "completed"
                ]
          }
    },
    execute: completeExecute,
  },
  "reschedule": {
    description: "Move an interview to a new datetime.",
    input: z.object({
      scheduledAt: z.string().datetime(),
      // Optional duration override — falls through to the existing
      // value if omitted.
      durationMin: z.number().int().min(5).max(480).optional(),
    }),
    access: {
          "roles": [
                "admin",
                "owner",
                "recruiter"
          ],
          "record": {
                "scheduledBy": {
                      "equals": "$ctx.userId"
                }
          }
    },
    execute: rescheduleExecute,
  },
  "scoreSummary": {
    description: "Aggregate average rating per interview across the org.",
    input: z.object({}),
    access: {
          "roles": [
                "owner",
                "admin"
          ]
    },
    execute: scoreSummaryExecute,
  }
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
