/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";
import { sql } from 'drizzle-orm';
import { applications } from "../applications/schema";

// Generated schema for interviews
// Combined from 2 table definition(s)

// Table: interviewScores
/**
 * Interview scores — Drizzle interop demo.
 *
 * This file is in the `interviews/` feature directory but exports ONLY a
 * `sqliteTable`, not a `defineTable`. That makes it an *internal* child
 * table:
 *
 *  - No CRUD routes are generated (no `:id` GET/POST/PATCH/DELETE)
 *  - No security pillar config (no firewall, masking, guards)
 *  - It still participates in migrations and shows up in the schema
 *  - Audit fields (`createdAt` / `modifiedAt` / `deletedAt` / `*By`) are
 *    auto-injected by the compiler exactly as on `defineTable` features
 *  - `organizationId` is auto-injected because the parent feature
 *    (`interviews`) is org-scoped — so scoped queries from action
 *    handlers (`db` is already org-tenanted) work without ceremony
 *
 * Used by the `complete` action handler: when an interviewer finalizes
 * an interview, the handler INSERTs a row here and then flips the
 * parent's status. Reading happens via a custom standalone action
 * (`scoreSummary`) that aggregates per-interview averages.
 *
 * Why Drizzle interop and not q-DSL: this table doesn't need any
 * security config (it's only ever written from inside trusted action
 * handlers running with the scoped `db`), and writing it as a plain
 * `sqliteTable` keeps it lightweight + opens the door to dialect-only
 * Drizzle features (e.g. SQLite-specific column types) that the q DSL
 * doesn't surface.
 */

export const interviewScores = sqliteTable("interview_scores", {
  id: text("id").primaryKey(),
  // FK to interviews.id — declared as a plain `text` rather than via
  // `.references(...)` because the parent table object is generated by
  // the compiler from the q-DSL and isn't importable at this layer.
  // The column is still indexed below; cascade behavior comes from the
  // soft-delete cascade machinery the compiler synthesises for the
  // parent feature, not a SQL FK.
  interviewId: text("interview_id").notNull(),
  // The user who scored. NOT a `q.scope("owner")` because this is a
  // pure Drizzle interop file (no q DSL); we just write a plain text
  // column and the action handler stamps it from `ctx.userId` on
  // INSERT.
  scorerId: text("scorer_id").notNull(),
  // 1–5 rating. Bounded at the action layer (Zod input schema) — no
  // CHECK constraint because SQLite's `text() with enum` only works on
  // strings; we keep the column as an integer for arithmetic in the
  // aggregate query.
  rating: integer("rating").notNull(),
  recommendation: text("recommendation", {
    enum: ["strong-no", "no", "neutral", "yes", "strong-yes"] as const,
  }).notNull(),
  comments: text("comments", { length: 2000 }),

    createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    modifiedAt: text("modified_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text("deleted_at"),
    createdBy: text("created_by"),
    modifiedBy: text("modified_by"),
    deletedBy: text("deleted_by"),
      organizationId: text("organization_id").notNull(),
  }, (t) => ({
  interview_scores_organization_id_deleted_at_idx: index("interview_scores_organization_id_deleted_at_idx").on(t.organizationId, t.deletedAt),
}));

// Table: interviews
/**
 * Interviews — scheduled meetings between candidates and the hiring team.
 *
 * Exercises everything the existing 3 features don't:
 *
 *  - Two scope columns: `q.scope("organization")` AND `q.scope("owner")`.
 *    With two scopes, auto-derivation refuses ("which one isolates?") and
 *    the user must declare `firewall: [...]` explicitly.
 *  - Explicit predicate-array `firewall` form. Demonstrates that org-scope
 *    is the tenant boundary and the owner column rides as a *systemManaged*
 *    auto-populated field (so clients can't backdate ownership) while
 *    per-row owner gating happens at the access layer, not the firewall.
 *  - `firewallErrorMode: "hide"` — opaque 404 instead of the default 403
 *    for cross-tenant probes. Used here because interviewer notes are
 *    sensitive enough that we don't even want to leak "the row exists".
 *  - `access.or[]` combinator: any of `{ roles: ['admin'] }` /
 *    `{ userRole: ['admin'] }` / `{ roles: [...], record: { … } }`
 *    satisfies the gate. Three different ways to grant access.
 *  - `access.record` field-condition with `$ctx.userId` interpolation —
 *    the static-DSL equivalent of "only the owner can do this," authored
 *    declaratively so the access pre-record check still admits role-only
 *    callers and the per-row filter fires post-fetch.
 *  - `userRole: ["admin"]` — Better Auth platform-admin tier (distinct
 *    from org `roles: ["admin"]`). Read more at
 *    `marketing/docs/content/docs/compiler/definitions/access.mdx`.
 *
 * On the deliberately-NOT-demonstrated side: function-form access
 * (`access: async (ctx, record) => …`). The runtime supports it (see
 * `runtime-templates/runtime-helpers.ts:evaluateAccess`), but the
 * `feature()` source parser doesn't extract arrow functions, so it's
 * only authorable via paths that bypass static parsing. For the q-DSL
 * the static `access.record: { …: { equals: '$ctx.userId' } }` form is
 * the canonical "owner-only" expression, and that's what's used below.
 */
export const interviews = sqliteTable("interviews", {
  id: text("id").primaryKey(),
  applicationId: text("application_id").notNull().references(() => applications.id, { onDelete: "cascade" }),
  scheduledBy: text("scheduled_by").notNull(),
  organizationId: text("organization_id").notNull(),
  scheduledAt: text("scheduled_at").notNull(),
  durationMin: integer("duration_min").default(30).notNull(),
  location: text("location"),
  status: text("status", { enum: ["scheduled", "completed", "no-show", "cancelled"] as const }).default("scheduled").notNull(),
  privateNotes: text("private_notes"),

    createdAt: text("created_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    modifiedAt: text("modified_at").notNull().default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    deletedAt: text("deleted_at"),
    createdBy: text("created_by"),
    modifiedBy: text("modified_by"),
    deletedBy: text("deleted_by"),
  }, (t) => ({
  interviews_status_idx: index("interviews_status_idx").on(t.status),
  interviews_organization_id_deleted_at_idx: index("interviews_organization_id_deleted_at_idx").on(t.organizationId, t.deletedAt),
  interviews_application_id_idx: index("interviews_application_id_idx").on(t.applicationId)
}));

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
