/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
/// <reference types="@cloudflare/workers-types" />

export interface CloudflareBindings {
  /** Auth database - Better Auth tables (users, sessions, accounts, organizations, members, etc.) */
  AUTH_DB: D1Database;
  /** Features database - Application tables */
  DB: D1Database;
  KV: KVNamespace;
  BETTER_AUTH_SECRET: string;
  BETTER_AUTH_URL: string;
  ACCOUNT_URL?: string;
  CMS_URL?: string;
  /** Webhooks database */
  WEBHOOKS_DB: D1Database;
  /** Webhooks delivery queue */
  WEBHOOKS_QUEUE: Queue;
  /** Stripe webhook secret */
  STRIPE_WEBHOOK_SECRET?: string;
  /** Realtime worker URL (for external broadcast calls, optional) */
  REALTIME_URL?: string;
  /** Internal access token for broadcast worker (optional) */
  ACCESS_TOKEN?: string;

  // Cloudflare Email Service
  EMAIL?: { send(message: any): Promise<any> };
  EMAIL_FROM?: string;
  EMAIL_FROM_NAME?: string;
  APP_NAME?: string;
}

declare module "cloudflare:test" {
  interface ProvidedEnv extends CloudflareBindings {}
}

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
