/**
 * Generated by quickback.dev
 *
 * This file is managed by the Quickback Compiler — do not edit directly.
 * To make changes, update your config and feature definitions in the quickback/ folder,
 * then run `quickback compile` to regenerate.
 */
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { auth, TRUSTED_ORIGINS } from './lib/auth';
import { authMiddleware } from './middleware/auth';
import { dbMiddleware } from './middleware/db';
import { servicesMiddleware } from './middleware/services';
import type { AppContext } from './lib/types';
import type { Services } from './lib/services';
import { signJwt } from './lib/jwt';
import applicationsRoutes from './routes/applications';
import candidatesRoutes from './routes/candidates';
import jobsRoutes from './routes/jobs';

import schemaRegistry from '../schema-registry.json';
import openapiSpec from '../openapi.json';

// ═══════════════════════════════════════════════════════════════════
// App Configuration
// ═══════════════════════════════════════════════════════════════════

// Deploy timestamp (captured on first request)
let DEPLOYED_AT: string | null = null;

export const app = new Hono<{
  Variables: {
    ctx: AppContext;
    db: any;
    services: Services;
  };
}>();

// ═══════════════════════════════════════════════════════════════════
// Global Middleware
// ═══════════════════════════════════════════════════════════════════

// CORS - must be first
app.use('*', cors({
  origin: (origin) => {
    if (!origin) return undefined;
    return TRUSTED_ORIGINS.includes(origin as (typeof TRUSTED_ORIGINS)[number]) ? origin : undefined;
  },
  credentials: true,
  exposeHeaders: ['set-auth-token', 'ETag'],
}));

// Database middleware - sets up D1 connection
app.use('*', dbMiddleware);

// Auth middleware - extracts session into ctx
app.use('*', authMiddleware);

// Services middleware - creates service integrations
app.use('*', servicesMiddleware);

// Global error handler
app.onError((err, c) => {
  console.error('[ERROR] Unhandled:', err instanceof Error ? err.message : 'unknown error');
  return c.json({ error: 'Internal server error' }, 500);
});

// Security headers middleware
app.use('*', async (c, next) => {
  await next();

  // Strict Transport Security (HTTPS only)
  c.header('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');

  // Prevent MIME type sniffing
  c.header('X-Content-Type-Options', 'nosniff');

  // Referrer policy
  c.header('Referrer-Policy', 'strict-origin-when-cross-origin');

  // Permissions policy
  c.header('Permissions-Policy', 'geolocation=(), microphone=(), camera=()');
});

// ═══════════════════════════════════════════════════════════════════
// Health Check
// ═══════════════════════════════════════════════════════════════════

app.get('/health', (c) => {
  // Capture deploy time on first request (Workers freeze Date at module load)
  if (!DEPLOYED_AT) {
    DEPLOYED_AT = new Date().toISOString();
  }
  const emailConfigured = Boolean(
    process.env.CF_ACCOUNT_ID && process.env.CF_API_TOKEN
  );
  return c.json({ status: 'ok', deployedAt: DEPLOYED_AT, emailConfigured });
});

// Email configuration status (for account UI)
app.get('/api/v1/system/email-status', (c) => {
  const emailConfigured = Boolean(
    process.env.CF_ACCOUNT_ID && process.env.CF_API_TOKEN
  );
  return c.json({ emailConfigured });
});

// ═══════════════════════════════════════════════════════════════════
// Auth Routes (Better Auth)
// ═══════════════════════════════════════════════════════════════════

// Email status (for account UI to check if email is configured)
app.get('/auth/v1/ses/status', (c) => {
  const emailConfigured = Boolean(
    process.env.CF_ACCOUNT_ID && process.env.CF_API_TOKEN
  );
  return c.json({ emailConfigured, provider: 'cloudflare' });
});

// Mark email as verified (called after OTP verification)
app.post('/auth/v1/verify-email', async (c) => {
  const session = await auth.api.getSession({ headers: c.req.raw.headers });
  if (!session) {
    return c.json({ error: 'Not authenticated' }, 401);
  }
  // Email is already verified by OTP flow, just return success
  return c.json({ success: true, emailVerified: true });
});

// Token endpoint — mint JWT for current session context
app.post('/api/v1/token', async (c) => {
  const ctx = c.get('ctx');
  if (!ctx?.authenticated) {
    return c.json({ error: 'Not authenticated' }, 401);
  }
  try {
    const jwt = await signJwt({
      sub: ctx.userId!,
      orgId: ctx.activeOrgId,
      role: ctx.roles?.[0],
      userRole: (ctx as any).userRole,
      email: ctx.user?.email,
      name: ctx.user?.name,
    }, process.env.BETTER_AUTH_SECRET!);
    return c.json({ token: jwt });
  } catch (error) {
    console.error('[AUTH] Token mint error:', error);
    return c.json({ error: 'Failed to mint token' }, 500);
  }
});

app.all('/auth/v1/*', async (c) => {
  try {
    const response = await auth.handler(c.req.raw);

    // Patch CORS headers onto raw Response (bypasses Hono middleware)
    const origin = c.req.header('Origin');
    if (origin && TRUSTED_ORIGINS.includes(origin as (typeof TRUSTED_ORIGINS)[number])) {
      const patched = new Response(response.body, response);
      patched.headers.set('Access-Control-Allow-Origin', origin);
      patched.headers.set('Access-Control-Allow-Methods', 'GET, POST, PATCH, DELETE, OPTIONS');
      patched.headers.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
      patched.headers.set('Access-Control-Allow-Credentials', 'true');
      return patched;
    }
    return response;
  } catch (error: any) {
    console.error('[AUTH] Unhandled error:', error?.message || error);
    return c.json({ error: 'Internal auth error' }, 500);
  }
});

// ═══════════════════════════════════════════════════════════════════
// Admin Routes (Admin/Owner Only)
// ═══════════════════════════════════════════════════════════════════

// Admin middleware - check for admin user role (from user table, not org membership)
app.use('/admin/v1/*', async (c, next) => {
  const ctx = c.get('ctx');
  if (!ctx.authenticated) {
    return c.json({ error: 'Unauthorized' }, 401);
  }
  if (ctx.userRole !== 'admin') {
    return c.json({ error: 'Admin access required' }, 403);
  }
  return next();
});

// Admin: List all organizations (for subscription management)
app.get('/admin/v1/organizations', async (c) => {
  try {
    // Use Better Auth's internal method to list organizations
    const result = await (auth.api as any).listOrganizations({ headers: c.req.raw.headers });
    return c.json({ data: result || [] });
  } catch (error) {
    console.error('Error listing organizations:', error);
    return c.json({ error: 'Failed to list organizations' }, 500);
  }
});

// ═══════════════════════════════════════════════════════════════════
// Schema Registry (CMS Metadata Endpoint)
// ═══════════════════════════════════════════════════════════════════

app.get('/api/v1/schema', authMiddleware, (c) => c.json(schemaRegistry));
// OpenAPI spec
app.get('/openapi.json', (c) => c.json(openapiSpec));
// ═══════════════════════════════════════════════════════════════════
// Feature Routes
// ═══════════════════════════════════════════════════════════════════

app.route('/api/v1/applications', applicationsRoutes);
app.route('/api/v1/candidates', candidatesRoutes);
app.route('/api/v1/jobs', jobsRoutes);

// ═══════════════════════════════════════════════════════════════════
// Start Server
// ═══════════════════════════════════════════════════════════════════

const port = process.env.PORT || 3000;
console.log(`Server running on http://localhost:${port}`);

export default {
  port,
  fetch: app.fetch,
};

/**
 * Generated by quickback.dev
 *
 * THE FILE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS OR DISTRIBUTORS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE FILE OR THE USE
 * OR OTHER DEALINGS IN THE FILE.
 */
